### ISSUE TITLE
Delete emails

### ISSUE THREAD

**Issue by grobie** [KartikTalwar/gmail.js#1]
Please add a function to delete emails. I have some folders with several tens of thousands of emails and gmail will always eventually respond with some error code if I try to delete them all at once.

A way to run a loop which 1. select all emails on a page 2. deletes them, until there are no more emails in this folder/label would finally help me to get rid of them.

The corresponding shortcut would be `*a#`.

**Comment by josteink** [comment]
Seeing as nothing has been done on this in over 3 years, I'm closing this for now.

Anyone who really wants this functionality are advised to issue a PR :)
