### ISSUE TITLE
Added ability to trigger a search

### ISSUE THREAD

**Issue by yellowandy** [KartikTalwar/gmail.js#117]
Not sure if you want a pull request but I had a need to search for something specific and trigger a search, happy to submit a pull request but the code is fairly simple:

```
    var searchVal = 'foobar';
    var el = gmail.dom.search_bar();
    //Populate the text field with the value
    el.find('.gbqfif').val(searchVal);

    //Trigger an event to preform the actual search
    var searchButton = $(".gbqfb")[0];

    //Trigger click event
    var mouseUp = document.createEvent('MouseEvents');
    mouseUp.initEvent( 'click', true, false );
    searchButton.dispatchEvent(mouseUp)
```

**Comment by josteink** [comment]
Seeing as this old issue has yet to result in any PR, I'm closing it.

If anyone else feels like picking it up, testing it and and submitting it as a PR, I'm more than happy to merge.
