### ISSUE TITLE
Q. Can I use gmail.js in a firefox addon for gmail?

### ISSUE THREAD

**Issue by rinkudas** [KartikTalwar/gmail.js#129]
I have already used this cool script to create a gmail extension for chrome. I want to port that same feature to a firefox add-on for the gmail. Can I use this script as it is?

**Comment by rinkudas** [comment]
@KartikTalwar  Thanks for your reply. I have used it in firefox and it is working perfectly till now with my requirements. You may close this issue.

**Comment by rinkudas** [comment]
Anyone needed a starting point how to use gmail.js in firefox addon can check https://github.com/rinkudas/gmail-firefox-addon-boilerplate. It provides basic functionality to inject gmail.js within gmail for using in an addon.

**Comment by KartikTalwar** [comment]
@rinkudas thank you so much for actually getting this to work! If you'd like to make a pull request and add a link to your repo on the README, I'd be happy to merge it

**Comment by josteink** [comment]
It should work fine. I'm using it as we speak. :)

Closing.
