### ISSUE TITLE
How to get all contact emails?

### ISSUE THREAD

**Issue by imemohit** [KartikTalwar/gmail.js#133]
I wanted to get the addon to get all contact emails and compare it with all the emails in the 'primary' tab only and hide the rest.

I can of course do the comparing,hiding etc. I just don't know how I can use your script to get all contact emails, and look for emails only in 'primary' tab.

Any help would be greatly appreciated.

**Comment by KartikTalwar** [comment]
Hi @imemohit, can you clarify this a bit. Are you referring to all your gmail contacts or contacts in a particular email thread?

**Comment by imemohit** [comment]
Hi, sorry for being vague. I am talking about all the gmail contacts. Thanks

On Jan 7, 2015 2:38 AM, Kartik Talwar <notifications@github.com> wrote:
Hi @imemohit, can you clarify this a bit. Are you referring to all your gmail contacts or contacts in a particular email thread?

---

**Comment by KartikTalwar** [comment]
Thanks for the clarification. Unfortunately, this library only dealing with basic UI manipulation and gmail actions (send, mark as read, delete, etc). You'd have to use the google contacts api to get that list but you can this gmail.js to get a list of all the emails that are visible in the inbox and the participants of that email

**Comment by imemohit** [comment]
Oh! Okay. Well, thanks anyways :)
Congrats on the great work.
