### ISSUE TITLE
Get Attachment Download URL or build download URL 

### ISSUE THREAD

**Issue by PANCAKES** [KartikTalwar/gmail.js#134]
I am developing a Chrome extension that allows the user to select emails in a thread and forward those, with attachments if desired, to our SaaS product. I download the file locally and upload to our service with the email body, subject, sender, etc. Pretty basic.

Is there a way to get the download URL of the attachments in an email? I see each thread can have an attachments array, but each element in the array is simply the filename. Is there a way to fetch the download url from the gmail server and include that with the filename? I can parse the message body HTML for inline images/URLs, but I do not see a way to get the download URL from the attachments section.

If this is not possible, do you know how to form the download URL similar to how you built the URL to fetch the email data? Big ask, but I figure it can't hurt if you happen to know.

Thanks in advance.

**Comment by PANCAKES** [comment]
Looks like I can get the raw HTML for the message with 
```
gmail.dom.email('id').email_body();
```
and parse it from there. Is this the best we can do at present?

**Comment by brentkelly** [comment]
@PANCAKES I've built a chrome extension similar to what you are doing here. Basically I inject some elements with the ``view_thread`` and ``view_email`` observers into the interface for composing an email, or for reading an email thread, which allows the user to select elements in our CRM to attach the specified email to.

I use a different approach to you - if they do it for an existing email thread, I simply call ``api.get.email_source`` for the relevant ``email_id`` which gives me the full source of the message - attachments and all and pass this to our server over AJAX.

The application then uses relevant server side libraries to parse the email source & extract all the email information - to, from, subject, body etc. I don't see why this wouldn't be able to extract attachments too provided the library being used supported it.

Hope that helps.

**Comment by PANCAKES** [comment]
Thanks @brentkelly, but our API accepts a JSON payload with fields for subject, sender, etc, so I am very hesitant to add another endpoint that is specific to this single application. We do not store the entire raw email at this time. I would like to keep the email parsing on the client side and keep the API clean for our 3rd party developers, as well as ourselves.

I will circle back to this on the weekend, but for now it looks like my best option is to use gmail.js to get the emails I want (is_expanded, etc) and then, with those email ids, fetch the DOM and parse out the attachment data. I have to parse the message body for any inline images, so this is just a touch more code to get the attachment section as well.

Thanks for your comments and ideas. I will watch this issue for updates, @KartikTalwar. Thanks!

**Comment by KartikTalwar** [comment]
@PANCAKES So turns out that fetching attachments follows a nice convention:


**https://mail.google.com/mail/u/0/?ui=2&ik={ik_value}&view=att&th={message_id}&attid=0.{atachment_index}&disp=safe&zw**

`attachmment_index` is just the index of the attachment. If there are 3 attachments and you want to get the 3rd file, the index value will be `3`. This URL is a 302 header that acts like a link shortener for the download file. Opening this link will lead you to the attachment data

```js
var ik = gmail.tracker.ik;
var id = gmail.get.email_id();
var aid = 1; // gets the first attachment

var url = "https://mail.google.com/mail/u/0/?ui=2&ik=" + ik + "&view=att&th=" + id + "&attid=0." + aid + "&disp=safe&zw";

console.log(url);
```

**Comment by PANCAKES** [comment]
@KartikTalwar Awesome, thanks! I was hoping it would be that easy, but I got stuck trying to find the realattrid value (which is in the download URL of the file in the DOM), but was unaware it was not required. Thanks for taking a look!

**Comment by KartikTalwar** [comment]
np :-)

**Comment by VaibhavJhunjhunwala** [comment]
var id = gmail.get.email_id(); is giving me 'null'. Please Help! 

![untitled](https://cloud.githubusercontent.com/assets/8027334/11656909/5ecb9578-9dde-11e5-86ef-de6a9a8607f7.png)

**Comment by VaibhavJhunjhunwala** [comment]
I want to get the URL of the attachment when an attachment is uploaded in the compose window and before sending the mail.
I was able to get the 'ik' parameter, but the gmail.get.email_id() returns null.

**Comment by KartikTalwar** [comment]
@VaibhavJhunjhunwala are you running `get.email_id()` on the compose window? `email_id()` only works when an already sent email is in the view. To get information about the compose box, please see `dom.compose` related methods. If that does not resolve your problem, please create a new issue with details on what is visible on the screen

**Comment by VaibhavJhunjhunwala** [comment]
@KartikTalwar I've raised a new issue about it. Please check it.

https://github.com/KartikTalwar/gmail.js/issues/212

**Comment by ianhi** [comment]
Hi,

@KartikTalwar I'm experiencing a similar issue to VaibhavJhunjhunwala  except it occurs when I have an already received or sent email in view as seen here:
![null_id](https://cloud.githubusercontent.com/assets/10111092/19617191/7f94f082-97f8-11e6-8414-9bb2a9cf7fd5.png)

I can get the email data when I've selected the same email from the inbox but not when the email is up:

![email_data](https://cloud.githubusercontent.com/assets/10111092/19617224/dd0ac304-97f8-11e6-8400-101386f7d63f.png)

any advice on how to get the id when the email is open would be much appreciated.

Thanks.

(also I'm so glad this library exists :)

**Comment by josteink** [comment]
We have this covered through the email_data element. 

Closing.

**Comment by chrassendk** [comment]
Kamino closed and cloned this issue to RogerAI/Roger-Backend

**Comment by purtiAggarwal** [comment]
How to get ik parameter please help...

**Comment by josteink** [comment]
You shouldn’t need the ik parameter for anything really. 

If you explained what you are trying to do, it might be easier to offer alternative approaches.
