### ISSUE TITLE
Ability to register for page change events

### ISSUE THREAD

**Issue by yellowandy** [KartikTalwar/gmail.js#137]
Hi, looking through the code base looks like we can easily get the current page but how about listening to page change events (say user clicks into a conversation and then back on the inbox).  Could just listen for the onhashchange event?

**Comment by KartikTalwar** [comment]
This was discussed a couple of days ago #135 
Sadly hashchange or dom mutation is the best way to do this but it's currently not natively part of gmail.js

I might do a more general observer (building on top of @brentkelly's work) but a custom solution would have to do for now.

**Comment by yellowandy** [comment]
Great thanks, went the hashchange route and works pretty well.  Will try and contribute something over the next couple of days if I can.  Thanks!

**Comment by KartikTalwar** [comment]
Awesome! Yeah hash change works really well but fails when you have preview
panes enabled
