### ISSUE TITLE
How do you add a drop-down toolbar button, like "More"

### ISSUE THREAD

**Issue by catmanjan** [KartikTalwar/gmail.js#143]
Is this possible with the content_html? Judging by the DOM there needs to be additional DIVs following the toolbar button.

**Comment by KartikTalwar** [comment]
@catmanjan you can right click on an existing drowpdown, inspect element and copy its html

**Comment by catmanjan** [comment]
Yes I know, but the content of the drop-down is not contained within the button, and if it is it displays incorrectly

Also the drop-down click event does not bind correctly

**Comment by KartikTalwar** [comment]
> Yes I know, but the content of the drop-down is not contained within the button, and if it is, it displays incorrectly.

Unfortunately, the goal of this library is to not focus on the UI implementations but instead do observers and provide helpful 'boolean' functions to make integrating with gmail easier. As terrible as this implementation sounds, the best way to get this done is to know the html for both states (inspect element after the click). You can either use jquery to do a full swap or diff to see what the onclick patter is.

> Also the drop-down click event does not bind correctly.

Need more details on this but again, not specific to gmail.js. If you are trying to bind an event before the div class/id exists in the dom it wont work. Similarly, if you successfully added an event to an id/class and it got removed from the dom, reinserting it won't bring back the event
