### ISSUE TITLE
api.get.visible_emails() not working correctly? 

### ISSUE THREAD

**Issue by moinc** [KartikTalwar/gmail.js#144]
1) It works ok when you look at the inbox.
2) When selecting another tab, let's say "Updates" it still returns the emails from the "Primary" tab.
3) When doing a search the hash turns into: #apps/{keyword}:{query} where keyword can be "from" or "date-begin" for example. And query is the text being searched for. In this case the method just throws an error. api.get.current_page() seems to be unable to deal with this and returns null. visible_emails() then simply blows up.
4) When you use the pager to load the next "page" of messages then the visible_emails() still starts at the first message (that was on the previous page). In other words: The method does not take paging into account.

On a side note: When switching tabs or when paging, gmail does a "load" event and this triggers the "refresh" event. Even though no one clicked the reload button. So it's not just related to reload/refresh when clicking a button. It's related to an event where gmail requests data from it's servers.

**Comment by KartikTalwar** [comment]
@moinc looking into this now. Sorry for the late response

**Comment by moinc** [comment]
Maybe this helps:

1. Found that when using Google Apps (for Business) the "place" for the search result is #apps/... and not #search/... slight difference.
2. Also in Google Apps (for Business) there may be a different layout of the page where the list is split into categories ("Primary", "Social", "Promotions" etc. and these are optional). Not sure if this is available in the free gmail also.
3. The problem is that GmailJS has it's own representation of what is on the page and it's very different from what the user actually sees.
4. For Paging, GmailJS does not take paging into account at all causing issue# 3.

**Comment by chanpory** [comment]
any updates on this?

**Comment by jimmaay** [comment]
Why not try and get the email information or ID's from DOM or wherever the information is held?

**Comment by josteink** [comment]
This issue is old and haven't had any activity for a long time. I'm therefore closing it. If this is still an issue, feel free to re-open.
