### ISSUE TITLE
Event for when selecting/deselecting email(s)

### ISSUE THREAD

**Issue by catmanjan** [KartikTalwar/gmail.js#146]
If you add a button to the toolbar, then select an email, the buttons are removed.

In particular, I want a set of buttons to only appear while emails are selected.

Is there a trigger to listen for, for these events?

**Comment by KartikTalwar** [comment]
@catmanjan unfortunately there isn't a direct trigger to do this. You can use mutation observers or even a settimeout function to execute the function to add the buttons if `gmail.check.is_inside_email()` returns true
