### ISSUE TITLE
Add permanent button to toolbar

### ISSUE THREAD

**Issue by rebelok** [KartikTalwar/gmail.js#153]
Hi!
I want to add a permanent button to toolbar so it would stay there despite of my actions in the inbox.
Now it disappears on any http_request, even page change.
Is it possible to subscribe to any http_request?

**Comment by brentkelly** [comment]
I'm sure it's possible but, as far as I am aware, not without modifying gmail.js core. I would suggest the easiest (dirty as it may be) option would be to simply set a setInterval to run 2 or 3 times a second to check that your button is still there & if not add it back. You'd obviously want to write it efficiently.

**Comment by KartikTalwar** [comment]
Hey @rebelok as @brentkelly mentioned, `setInterval` would be the safest and best way to kinda have the additional buttons up there, but I do think it'd be nice to have a generic observer type to handle all http request. I'll add that this weekend :-)
