### ISSUE TITLE
how can I turn off xhr logging

### ISSUE THREAD

**Issue by glebovilya** [KartikTalwar/gmail.js#158]
I have called one gmail.tools.xhr_watcher()
 and now I can't figure out what have I do to turn off constant xhr logging. Page reload and closing was not helpfull

**Comment by KartikTalwar** [comment]
hi @glebovilya you shouldnt be using the `tools.xhr_watcher()` to do anything. That function is what the `observe` functions use in the library. If you still want to manually turn it off, you can run `gmail.observe.off()`

**Comment by glebovilya** [comment]
My issue was not connected with using of gmail.js. It was a chrome developers tools standard xhr logging.
