### ISSUE TITLE
gmail.observe .on(action, callback) not working?

### ISSUE THREAD

**Issue by skaern** [KartikTalwar/gmail.js#16]
I have put together some code for using gmail.js as part of a chrome extension. It all seems to work just fine, however none of the gmail.observe functions seem to do anything. I have tried entering them into the console just as you have outlined in the readme.

Example:

```
gmail.observe.on("star",function() {
   console.log("it worked"); 
} );
```

When I then star an email, nothing happens. Am I using this wrong or is it a bug?

**Comment by keyur1110** [comment]
I am creating a chrome extension to filter gmails when a new email is found but the function given below is not working.

`var main = function(){
    gmail = new Gmail();
    console.log('Hello,', gmail.get.user_email())
    filterapi = new Gmail_Filter_Api();
    filterapi.set_gmail_params();
    console.log("Filters set!");
    gmail.observe.on('new_email', function(obj) {
        var data = gmail.get.email_data(email_id=obj),
            content = data['threads'][obj]['content_plain'];
			console.log(gmail.get.email_data);
        if(content.indexOf(keyword) > -1){
            filterapi.createGmailFilter({"has":keyword,
                                         "markread":true,
                                         "skipinbox":true,
                                         "labelas":labelname});
            console.log("Creating filter with id: " + filterapi.filterid);
        }
    });
}

refresh(main);`
