### ISSUE TITLE
view_thread and view_email observers are ONLY called when clicking into the thread from the inbox

### ISSUE THREAD

**Issue by whather** [KartikTalwar/gmail.js#162]
I have an issue where if I load a thread from a hard page refresh, and then start opening emails from the conversation view, the view_email observers don't fire. Is there a way to force the thread observers to work when loading a thread from a hard page refresh (without clicking on it from the inbox view)?

These are my observers:

```
gmail.observe.on("view_thread", function($thread) {
  window.setTimeout( function() {
    onThreadLoaded($thread.$el);
  }, 0);
})

gmail.observe.on("view_email", function($email) {
  window.setTimeout( function() {
    addEmailReplyDropdown($email);
  }, 0);
})

gmail.observe.on("load", function() {
  if(gmail.check.is_inside_email()) {
    onThreadLoaded($('div.if'));
  }
})
```

Do I need to initialize the thread somewhere in the load() observer or something? BTW I've seen BOTH view_thread and load observers fire on a page refresh, but it's sporadic and rarely happens.

Has anyone run into this issue and do you know if there's a workaround? Thanks!

**Comment by KartikTalwar** [comment]
Hey @whather the observer actions are all based on http sniffing. A specific http action request gets called for each of those tasks (viewing thread, polling, pressing buttons) therefore the callback functions are only triggered for the threads when you click an email in the inbox view.

The actions are also not exclusive, `load` is a DOM action and `view_email` is a http action. When the DOM item fully loads see [1], the `load` callback fires and if in that time, a thread http request is requested from the server, that callback will trigger too. If you want things to run on hard refresh, you can just do a check for `is_thread()` and run your function

[1] https://github.com/KartikTalwar/gmail.js/blob/master/src/gmail.js#L1285

**Comment by whather** [comment]
This is the issue I'm trying to fix. When you hard load a thread view (without clicking into it), it works fine for the most recent email:

![screen shot 2015-04-09 at 2 47 58 pm](https://cloud.githubusercontent.com/assets/148534/7077703/dc221d48-dec7-11e4-89c5-59a00e825d02.png)

But then when clicking into an older email within the thread, the view_email observers don't fire (notice how the blue icon doesn't appear for this email):

![screen shot 2015-04-09 at 2 48 11 pm](https://cloud.githubusercontent.com/assets/148534/7077714/f88f4a14-dec7-11e4-9f39-9db9444b28f0.png)

Note that this works perfectly however when clicking into the thread and expanding emails. Is there something else I need to do within the load callback to register these observers?

**Comment by catmanjan** [comment]
I think because there is no AJAX request when you expand a message in a thread these listeners would not work. Best bet is to use a DOM onclick event. 

@KartikTalwar it would be nice to have hooks into the listeners for these cases, but I think they warrant their own event type.

**Comment by mrflibble57** [comment]
I'm having the same issue, and it's not because there's no AJAX call as catmanjan has said. It seems like something isn't hooked in when you load gmail with an open email vs loading it via inbox. 

gmail.observe.on("http_event", (obj) => {
                    console.log(obj);
                })

gmail.observe.on("open_email", , (obj) => {
                    console.log(obj);
                })

will both work for loading an email in the thread after loading it from the inbox, but it won't work at all for any of the thread's emails opened if the initial url is https://mail.google.com/mail/u/1/#inbox/1234567890123456

**Comment by josteink** [comment]
This functionality has worked for me on any build I've used the last 6 months.

Please note: I've used NodeJS require() style loading and bundled it all together to one script-file using Browserify. The effect of this is that Gmail.js loads *instantly* with no delay, and this might make a difference.

Anyone affected willing to give this a go?

**Comment by josteink** [comment]
I've created this repo as a sample people can build on and explore:

https://github.com/josteink/gmailjs-node-boilerplate

Hope that helps.

**Comment by steelx** [comment]
I was facing same issue. I wanted to get emails of `people_involved` from `gmail.get.displayed_email_data_async`. But it depends on email HASH id, which the function was executing before the page was ready.

Hence below solution worked fine for me.

```
if ((/inbox/.test(window.location.hash.split("/").pop().replace(/#/, "").split("?")[0]))) {
        // wait until you find email hash
        setTimeout(appendRightSide, 10);
        return;
    }
```

**Comment by josteink** [comment]
Issue filed on a 2 year old version. Assuming this is no longer an issue, and closing.

Feel free to re-open if you still need this issue addressed.
