### ISSUE TITLE
safer alternative to eval() for parsing Gmail's response

### ISSUE THREAD

**Issue by keven425** [KartikTalwar/gmail.js#169]
In gmail.js, eval() is currently used to parse JSON-like response. Is there any safer alternative to using eval(), in order to minimize the risk of script injection, etc. ?

**Comment by KartikTalwar** [comment]
@keven425 seems like `eval()` can be eliminated. I'll try tackling that along with a couple other open issues this weekend :-)

**Comment by keven425** [comment]
That will be amazing. Thank you @KartikTalwar !

Here's what I've tried: using regex to replace:
1. ',,' with ',null,'
2. single quotes with double quotes

But then we ran into issues where double quotes were used inside a single-quote string, such as css font style.
