### ISSUE TITLE
can not change xhr.xhrParams.body_params.body before send_message

### ISSUE THREAD

**Issue by shaosongli** [KartikTalwar/gmail.js#170]
Hi,

I am developing a Google Chrome Extension and want to encrypt the message before sending. When I use the gmail.js and run the example to change to subject of the send_message, it works. However, I cannot change the body parameter. Does anyone know how to change the body of message before sending, such as replace it with the encrypted body? Some examples would be perfect, thanks.

**Comment by shaosongli** [comment]
By the way, I can change the compose dom, but when sending, the change has no effect. What is the relationship between the compose dom and xhr or email_data. The latter two record exactly what I input in the compose box. I am know to this, thanks for any explanation.

**Comment by KartikTalwar** [comment]
Hello @shaosongli unfortunately gmail hashes the message data before sending and this is a common issue with this library (you can search this in issues). The solution to this is to get the message content and modify that before the send action

**Comment by keven425** [comment]
If I remember correctly, there's a cmml parameter that represents length of gmail message. You could update that parameter to reflect the new body length.

**Comment by shaosongli** [comment]
Thanks for the reply @KartikTalwar Do you mean the solution in issue #86 . which means making the update to the body on the mousedown event for the send button rather than the click event. Sorry I am new to this area and do not even know how to catch the mouse down event of the send button.

**Comment by shaosongli** [comment]
Hi @keven425 , I think you have a similar problem to modify the body in issue #90, any luck for that. And could you give me some refer or example code, thanks.

**Comment by keven425** [comment]
@shaosongli sorry I don't have any sample code. But you can approach this in two ways:

1. modify url parameter "cmml" to reflect updated length of body. Length will be `body.length`. `body` you can get from the post data. However, cmml is passed in xhr open() call. Last time I checked gmail.js didn't provide a way to intercept the open().
2. modify body in dom before send API request happens. There are two places body lives. Inside content-editable div (`$('.M9 [contenteditable=true]')` which user can see), and in a form input with name="body" (`$('.M9 input[name=body]')`). I believe the form input reflects what's in content-editable div. But to guarantee your change takes effect, you can update both places.

**Comment by kolczagy** [comment]
Here is my solution and it works fine:

gmail.observe.before('send_message', function(url, body, data, xhr) {

        var oldCmml = xhr.xhrParams.url.cmml;

        var body_params = xhr.xhrParams.body_params;
        var string = '<div dir="ltr"><div>hello</div></div>';

        if (string.length > oldCmml) {
            xhr.xhrParams.url.cmml = string.length;
        } else {
            string += '<div>';
            while(string.length<oldCmml){
                string += ' ';
            }
            string += '</div>';
            xhr.xhrParams.url.cmml = string.length;
        }

        body_params.body = string;

        console.log(oldCmml, xhr.xhrParams.url.cmml, string);

    });

So if the oldCmml is less then the new newCmml (the body's length) then you simply set the newCmml. Otherwise if the oldCmml is greater then the newCmml then you can't reduce the cmml value, you have to add (oldCmml-newCmml) characters to the body. This is what the while cycle do.

You can replace the "string" variable with your new body string value.

Best Regards,
Gyozo

**Comment by danieltigse** [comment]
@kolczagy Great solution!! It Works! Thanks. This example should be in the documentation.

**Comment by josteink** [comment]
Seems this one is already solved. Closing.
