### ISSUE TITLE
Is there a minified version?

### ISSUE THREAD

**Issue by onassar** [KartikTalwar/gmail.js#173]
Thanks for your contribution with this library @KartikTalwar  
Any chance there's a minified version somewhere that has all t's crossed and i's dotted (as in, no syntax issues with missing semi-colons, etc?)

**Comment by KartikTalwar** [comment]
You can just run the file on jscompress and use it

**Comment by onassar** [comment]
You mean something like [jscompress.com](http://jscompress.com/)?

**Comment by KartikTalwar** [comment]
Yes

**Comment by onassar** [comment]
Gotcha. Thought there may be syntax issues, but all good.
