### ISSUE TITLE
gmail.get.loggedin_accounts() returning incorrect data: gmail for work account

### ISSUE THREAD

**Issue by amitg87** [KartikTalwar/gmail.js#180]
Currently account info is extracted based on 
{name : GLOBALS[17][23][1][i][4], email : GLOBALS[17][23][1][i][0]}

In one of a Gmail managed account (link:https://www.gmail.com/intl/en_us/mail/help/work.html)
I observed account info resides in 
{name : GLOBALS[17][24][1][i][4], email : GLOBALS[17][24][1][i][0]}

Can this be generalized? Only if tested across many accounts.
Comments?

**Comment by josteink** [comment]
I can't reproduce. Is this still an issue with the latest version?

Because this is an old issue, I'll close this for now, but please re-open and provide more details if you can still reproduce this.
