### ISSUE TITLE
Detect whether compose is in HTML vs. plain text mode

### ISSUE THREAD

**Issue by keven425** [KartikTalwar/gmail.js#181]
In the compose form, there is `$('input[name=ishtml]')`. However, its value is always set to 0. 

Is there a way to detect if a composed email is in HTML vs. plain text mode before send? My application allows user to insert a block of HTML. We want to basically stop users from doing that if email is in plain text mode.

**Comment by keven425** [comment]
@KartikTalwar Turns out there's a bit buried in GLOBALS object. Add function to check:

https://github.com/KartikTalwar/gmail.js/pull/185

**Comment by josteink** [comment]
Because this is an old issue, and it seems you've solved in the form of a PR, I'll close this for now, but please re-open if you still feel there is something you need resolved.
