### ISSUE TITLE
Boomerang compatibility problem: Cannot read property 'extend' of undefinedGmail @ gmail.js:2078

### ISSUE THREAD

**Issue by aliparlar** [KartikTalwar/gmail.js#184]
If Boomerang and Gmail.js are both installed:

Uncaught TypeError: Cannot read property 'extend' of undefinedGmail @ gmail.js:2078

**Comment by lievenjanssen** [comment]
Same problem here

**Comment by KartikTalwar** [comment]
@aliparlar @lievenjanssen sadly this is a known issue. This happens because there are 2 jqueries being used on the page. Because this library's examples don't focus much on the implementation, a common solution is to use requirejs to sanbox the dependencies.

**Comment by lievenjanssen** [comment]
@KartikTalwar could you give me some pointers on what I need to change to make the gmail-chrome-extension-boilerplate work the way you suggested?

**Comment by KartikTalwar** [comment]
@lievenjanssen you can see an example here https://github.com/salsita/chrome-extension-skeleton/tree/legacy/code/js

**Comment by lievenjanssen** [comment]
@KartikTalwar I solved it by using the jQuery.noConflict function and the localJQuery parameter to initialize gmail.js.

gmail = new Gmail($.noConflict(true));

**Comment by KartikTalwar** [comment]
Oh awesome! Much easier than requirejs :-)
ᐧ

**Comment by josteink** [comment]
Sorry about the extremely late reply. From what I can tell, this should now be fixed.

Because this is an old issue, I'll close this for now, but please re-open if you still feel there is something you need resolved.
