### ISSUE TITLE
Can I create a label and apply it to the emails? If no, what is needed to be done?

### ISSUE THREAD

**Issue by rajeshyogeshwar** [KartikTalwar/gmail.js#189]
I want to create a label when the extension is first installed, then based on my content script  I want that the newly created label is applied to the emails.

**Comment by KartikTalwar** [comment]
Currently, there isn't support for creating and mimicking various actions as the goal of the library is to be more on the passive side of observing whats going on in gmail. If you'd like to trace what requests are made when a label gets created and single out how to replicate it, we can perhaps make it part of the library

**Comment by catmanjan** [comment]
@KartikTalwar what about all of the ```api.tools``` functions? 

I think the kind of functionality @rajeshyogeshwar describes should be part of that group of functions.

**Comment by josteink** [comment]
The question answered (a long time ago!) so closing issue.

If anyone really wants this functionality, the best way to get it is by submitting a PR. Cheers!
