### ISSUE TITLE
Get 'from' field in the Compose window, when available.

### ISSUE THREAD

**Issue by mavidser** [KartikTalwar/gmail.js#191]
The api.dom.compose has almost all the attributes except the 'from' data, which is displayed when aliases are enabled.

![Example](https://cloud.githubusercontent.com/assets/4343949/8720499/b2128442-2bd0-11e5-920a-09cd880b098e.png)

**Comment by josteink** [comment]
Sorry about the extremely late reply. From what I can tell, this should now be implemented in the form of `from()`.

Because this is an old issue, I'll close this for now, but please re-open if you still feel there is something you need resolved.
