### ISSUE TITLE
Make it work with inbox.google.com

### ISSUE THREAD

**Issue by saintmac** [KartikTalwar/gmail.js#196]
A lot of people are moving from gmail to inbox. If this library could provide functionality for both it would be great

**Comment by jameskerr** [comment]
@KartikTalwar is there any library like this for inbox.google.com?  This is an awesome tool by the way.

**Comment by josteink** [comment]
A quick answer, almost a year late I admit, is no.

Inbox is a fundamentally different web-application, and none of the techniques and reverse-engineering put into this library will work on inbox.google.com.

Sorry. Closing :)
