### ISSUE TITLE
"Send mail as...". Does gmail.js can handle it?

### ISSUE THREAD

**Issue by orrion** [KartikTalwar/gmail.js#197]
Hi @KartikTalwar . As you know, Gmail has an option to add some additional accounts (that you own) so you can use them to send emails by still being logged in under your current Gmail account... Also user can specify POP settings to get emails for this specified additional account...

As I understand gmail.get.loggedin_accounts() will return only the list of Gmail accounts that user is signed in, right? 

I have two cases:

1. Get the 'from' value before user sends the email.
2. When user opens the received email it is required to get the actual 'to' value (the email address that this email was sent to).

There is no problem with first case, I think I won't have any troubles in getting this 'from' value. But in second case I don't think that I can use simple gmail.dom.email.to() method because there may be more than one recipient + receiver may be specified in cc or bcc.... 

Do you know if there is any other way of achieving case '2' ?

Thanks.

**Comment by yellow-beard** [comment]
1. is now provided by `gmail.dom.compose.from()`

e7c6deec6991a5bac25cda6a81fee05bfb158e91

**Comment by orrion** [comment]
@yellow-beard Thanks for the response. It will help me to get the 'from' value from the compose window. 
Regarding item 2:
I managed to get the receiver email address by parsing the email headers (from email source). In case when email was sent to one of the pop accounts there would be 'X-Gmail-Fetch-Info:' header present inside the email source. This field contains the information about the pop account that received this email...
