### ISSUE TITLE
Is it possibile to add some functions to the email from text box?

### ISSUE THREAD

**Issue by AminaG** [KartikTalwar/gmail.js#200]
I need to get notified when the user change the "mail from" select box.
I also need to be able to change it manually.

Where should I start to do that? or someone can help/

**Comment by KartikTalwar** [comment]
Hey @AminaG currently a observer for that specific action does not exist but you can use the `dom.compose` method to get and manipulate the information

Here is an example:

```js
var drafts = gmail.dom.composes()
var draft = drafts[0]

draft.dom().find('#\\:110').find('span').text() // returns "Kartik Talwar <hi@kartikt.com>"
```

**Comment by AminaG** [comment]
Thank you.

I am still not find out, how to do what I am trying.
What I am trying to do is this. I have two mail addresses (in one gmail
account):

private@gmail.com
myname@mycompany.com

I want, that every time I send message to someone at *@mycompany.com*, it
will automatically will change the FROM input box, to *myname@mycompany.com*

So, now I have two question:

1. How I can get notified about new "TO" address in the input box?
2. How to change the "FROM" input box?

using the code in the previous comment, I can inspect the "from" address,
but I cannot change it.

ᐧ

**Comment by KartikTalwar** [comment]
`dom.compose` gives you a dom representation of the compose window. Each compose object has access to these parameters https://github.com/KartikTalwar/gmail.js/blob/master/src/gmail.js#L2177-L2191

You can get the TO from `{dom_object}.to`. Everything else is standard dom manipulation in javascript
