### ISSUE TITLE
get draftid with gmail.js

### ISSUE THREAD

**Issue by SfayhiKarim** [KartikTalwar/gmail.js#202]
Hello , 
I want to detect the id of the draft with gmail.js .
It's possible ?

Thanks .

**Comment by KartikTalwar** [comment]
Hey @SfayhiKarim you can get the id by using the dom methods from the documentation:

```js
// get all compose windows
var drafts = gmail.dom.composes();

// get the first draft's id
console.log(drafts[0].email_id())
```

**Comment by SfayhiKarim** [comment]
thanks for your reply.

but I have this error whent i execute this code in the console :

Uncaught TypeError: gmail.dom.composes is not a function(…)

**Comment by KartikTalwar** [comment]
@SfayhiKarim please take a look at https://github.com/KartikTalwar/gmail-chrome-extension-boilerplate to see how to get gmail.js running inside gmail. 

My example wasn't meant to be run verbatim and the `var gmail = Gmail()`

**Comment by SfayhiKarim** [comment]
Thanks @KartikTalwar.

I solved it by using "gmail.get.compose_ids()" . 
:)

**Comment by SfayhiKarim** [comment]
the solution is : 
$(document).on('click', function(evt) {
     
     var compose_id;
     
      if ($(evt.target).is('[id="clone8"]'))
     {
         compose_id = $(evt.target).closest('.AD').find('.aoC').find("[name='draft']").val();
     
     }
     
     });

NB : clone8 is the id of the red button .
