### ISSUE TITLE
How to hide the compose 

### ISSUE THREAD

**Issue by SfayhiKarim** [KartikTalwar/gmail.js#203]
hi,

I want to hide the compose when i click in the button "envoyer ultiérement" with gmail.js.

Thanks.

![boitemail](https://cloud.githubusercontent.com/assets/15380361/10878435/d5a3b9b2-814d-11e5-87fd-b52d92486319.png)

**Comment by josteink** [comment]
Because this is an old issue, I'll close this for now, but please re-open and provide more details if you can still reproduce this.

You may though be interested in this: https://github.com/KartikTalwar/gmail.js/issues/373
