### ISSUE TITLE
gmail.observe.before is not a function

### ISSUE THREAD

**Issue by irtzaqc** [KartikTalwar/gmail.js#204]
I'm trying to use the gmail.observe.before function but I keep getting the error Uncaught TypeError: gmail.observe.before is not a function. gmail.get.user_email() works fine, so I know that Gmail.js is okay. But why is observe.before giving me this error then?

**Comment by KartikTalwar** [comment]
![screen shot 2015-11-03 at 12 39 44 am](https://cloud.githubusercontent.com/assets/461702/10901820/699300f4-81c3-11e5-8f1e-6a128ab06cec.png)


Working fine here. How are you using gmail.js?

**Comment by irtzaqc** [comment]
apologies. I was using an older version of the gmail.js file.

**Comment by irtzaqc** [comment]
apologies. I was using an older version of the gmail.js file.
