### ISSUE TITLE
Uncaught TypeError: gmail.observe.register is not a function

### ISSUE THREAD

**Issue by SfayhiKarim** [KartikTalwar/gmail.js#206]
Hello , 

When i execute this function 

```
gmail.observe.register('compose_email_select', {
  class: 'Jd-axF',
  selector: 'div.Jd-axF:first-child'
});
```

I have this error : 
Uncaught TypeError: gmail.observe.register is not a function

what is the problem ? 
 thanks .

**Comment by KartikTalwar** [comment]
@SfayhiKarim how are you using gmail.js? This error likely implies that gmail.js is not being loaded in gmail's dom. Please check out the boilerplate chrome extension in the readme to see a sample of how to install it

**Comment by josteink** [comment]
Because this is an old issue, I'll close this for now, but please re-open and provide more details if you can still reproduce this.
