### ISSUE TITLE
Why there is no gmail.set.search_query (you have get/)

### ISSUE THREAD

**Issue by Aminadav** [KartikTalwar/gmail.js#208]

**Comment by KartikTalwar** [comment]
The goal of gmail.js was to only focus on get methods so that the focus of the library stayed at knowing when things happen vs manipulating the UI. For this specific case, if you'd like to make a PR and add the functionality, I'd be happy to merge it!

**Comment by josteink** [comment]
Because this is an old issue, I'll close this for now, but please re-open and provide more details if you can still reproduce this.
