### ISSUE TITLE
before events replace %20 in + in xhrParams body

### ISSUE THREAD

**Issue by lievenjanssen** [KartikTalwar/gmail.js#209]
This is due to the jquery $.param() implementation, see http://bugs.jquery.com/ticket/3400

Due to this behaviour there is a conflict between gmail.js and hubspot sidekick. (spaces are replaced by +'s in the email body)

I solved this by adding ```.replace(/\+/g, "%20")``` to this line:

```
body = arguments[0] = this.xhrParams.body_is_object ? this.xhrParams.body_params : $.param(this.xhrParams.body_params,true);
```

@KartikTalwar if you want I can do a pull request on it?

**Comment by KartikTalwar** [comment]
Sure, that'd be great!
