### ISSUE TITLE
Example of using gmail.observe.http_requests() ?

### ISSUE THREAD

**Issue by skaern** [KartikTalwar/gmail.js#21]
Would you be able to give an example of how to use this and access the different parameters of the requests? I'm presuming it can be used to access the details of the most recently sent email?

Thanks for creating this btw, it is really useful!

**Comment by itsazzad** [comment]
`gmail.observe.http_requests()` worked for me.
But can you please state that the order ASC or DESC?

**Comment by KartikTalwar** [comment]
The order is reverse chronological - the first entry will be the lastest http request
