### ISSUE TITLE
Possible bug in api.get.current_page()

### ISSUE THREAD

**Issue by Navega** [KartikTalwar/gmail.js#211]
When the hash is, for example, #label/xxxx/123123b, the function "api.get.current_page() returns "null" correctly; but when the hash is #label/xxxx, it returns "null", and I think that it should return label/xxxx. Is that correct?

**Comment by KartikTalwar** [comment]
@Navega yes, it is a bug. Fixing it in the next commit

**Comment by Navega** [comment]
Thanks. But, one thing more. In the last commit I have problems to return the contents of an open mail. I Use this code and there are no problems. What do you think?

api.get.current_page = function() {
    var hash  = window.location.hash.split('#').pop().split('?').shift();
    if (hash.split("/").length>2){
      return null;
    }

    var pages = ['sent', 'inbox', 'starred', 'drafts', 'imp', 'chats', 'all', 'spam', 'trash', 'settings'];

    var page = null;

    if($.inArray(hash, pages) > -1) {
      page = hash;
    }

    if(hash.indexOf('label/') == 0 || hash.indexOf('category/') == 0 || hash.indexOf('search/') == 0 || hash.indexOf('settings/') == 0) {
      if(hash.split('/').length < 3) {
        page = hash;
      }
    }

    return page;
  }

**Comment by KartikTalwar** [comment]
If you are inside an email, the function will now return `email`

**Comment by Navega** [comment]
Ok, thanks again. Before of your commit, I get the content of opened mail through "gmail.get.selected_emails_data()[0].last_email" and now it doesn't work, I meant that.

Certainly, the library is great! Thanks.

**Comment by KartikTalwar** [comment]
@Navega sorry I missed this comment, a new pr was merged that handled this bug. Thanks for pointing it out!
