### ISSUE TITLE
Get the download URL of an attachment before sending a new email from the compose window

### ISSUE THREAD

**Issue by VaibhavJhunjhunwala** [KartikTalwar/gmail.js#212]
![untitled](https://cloud.githubusercontent.com/assets/8027334/11680999/17cb7946-9e82-11e5-9920-8a07565446cc.png)
Temporary Link of the file that is attached in the compose window, during compose mail : 

ui=2&ik=1a4d5636bc&view=att&th=151855ae74353ac0&attid=0.1&disp=safe&realattid=f_ihyf03z70&zw

Permanent Download Link of the file once that same compose email has been sent : 

ui=2&ik=1a4d5636bc&view=att&th=151855bbe2a11a9d&attid=0.1&disp=safe&realattid=f_ihyf03z70&zw

I want the value of the 'th' parameter in the URL of the temporary link and NOT the permanent link,
ie. When the user attaches or drops a file into the compose window, the file gets attached to it. After that it gets a href value which is the temporary download URL. I want that URL since i want to read the bytes of the file and make changes accordingly on my server before sending the email.

**Comment by VaibhavJhunjhunwala** [comment]
ui=2&ik=1a4d5636bc&view=att&th=151855ae74353ac0&attid=0.1&disp=safe&realattid=f_ihyf03z70&zw

I have been able to retrieve the values of the parameters 'ik', 'realattid' using the observe.on('upload_attachment') callback. But there is no trace of retrieving the value of the parameter 'th'.

NOTE : The 'th' value of the download URL of the attachement changes once we send the same email. Rest all parameter values remain the same.

**Comment by josteink** [comment]
Because this is an old issue, I'll close this for now, but please re-open and provide more details if you still need help.

Since the filing of this issue, we've added attachment details and download URL to the `email_data().threads[]` elements. If you fetch up the email-ID once an email has been sent, this should be all you need.
