### ISSUE TITLE
add local scope of 'var' for iterator

### ISSUE THREAD

**Issue by walty8** [KartikTalwar/gmail.js#213]
hi,

As advised by Firefox Reviewer, in line 49 of `gmail.js` (inside `api.get.loggedin_accounts`),  

`for(i in data[1]) {` 

better changed to 

`for(var i in data[1]) {`

thanks

**Comment by KartikTalwar** [comment]
Thanks for pointing that out, would you like to submit a pull request? I believe you should get the credit in the fix/git history
