### ISSUE TITLE
Work-arounds for on 'compose' not being called fast enough?

### ISSUE THREAD

**Issue by sbrudz** [KartikTalwar/gmail.js#215]
I've developed a Chrome extension based on the [boilerplate](https://github.com/KartikTalwar/gmail-chrome-extension-boilerplate) that uses Gmail.js to highlight text in the compose window.  In general it works well, but we've had some users report that the plugin doesn't work.  

After further investigation, we found that these users had refreshed the page and then clicked the 'Compose' button before the page had time to fully load.  

We're using `gmail.observe.on('compose', ...);` so what I think is happening is that the compose window is being opened before the observer is set up.

Since loading speed is a hard thing to control, I'm wondering if there's an alternative way to use Gmail.js to watch for changes to the body area of the compose window.  If there's a faster method of loading Gmail.js in an extension, that would work too.

The extension code is [here](https://github.com/cyrusinnovation/just-not-sorry), in case that helps.

Thanks in advance for your help.

-Steve Brudz

**Comment by brentkelly** [comment]
Hi Steve - I've tried to make this happen on my implementation & can't make an error occur. I've tried:

  * Reloading the interface & clicking the compose button the moment it becomes visible.
  * Reloading the interface & pressing 'c' multiple times as it loads
  * Creating a compose window & then reloading the interface so it pops up with one

In all instances the observer fires for me.

The only way I can see it not registering the observer in time is if your script is not loading before the interface has managed to completely load and create the content window ... which shouldn't be the case given the interface generally takes 1-2 seconds to load (for me at least) and the gmail.js script should be local in the extension (unless you are referencing the gmail.js file remotely - that could be the problem?)

**Comment by brentkelly** [comment]
FYI the way the observer works is the first time you register any DOM related event, gmail.js then observers every element being injected into the DOM .. in this case watching for the appropriate elements for a compose window appearing.

With that in mind, if your app were to not call your ``gmail.observe.on('compose', ...);`` as soon as the script loads, that could potentially cause some kind of timing issue like you are having?

**Comment by sbrudz** [comment]
Hi @brentkelly, thanks for the fast response!  gmail.js is local and `gmail.observe.on('compose', ...)` is one of the first things called.

I think I may have found the problem.  Inspired by your comment about "your script is not loading before the interface has managed to completely load", I put some console.log statements in to see what was happening during the load process.

I've been using this refresh function from the boilerplate:
```js
function refresh(f) {
  if( (/in/.test(document.readyState)) || (undefined === Gmail) ) {
    setTimeout('refresh(' + f + ')', 10);
  } else {
    f();
  }
}
```
The RegEx matches `loading` and `interactive`, so the function keeps looping until `document.readyState === complete` and `new Gmail()` isn't getting called until after the Gmail page completely loads.

If I change the refresh function to run the callback when readyState is `interactive`, Gmail() is getting initialized sooner and my problem appears to be fixed.

Do you see any potential dangers with this approach?

**Comment by sbrudz** [comment]
FYI for others who might hit this problem:  I found that I needed to add checks to my refresh method to make sure that other key objects have been loaded (e.g., window.jQuery === undefined) or else I'd see sporadic failures.

Thanks again for the help, @brentkelly !
