### ISSUE TITLE
get.visible_emails_async throws when inside email

### ISSUE THREAD

**Issue by gberger** [KartikTalwar/gmail.js#216]
```
Uncaught TypeError: Cannot read property 'indexOf' of null
api.helper.get.visible_emails_pre @ gmail.js:1427
api.get.visible_emails_async @ gmail.js:
```

Workaround: use `check.is_inside_email` before calling `get.visible_emails_async`

**Comment by KartikTalwar** [comment]
Hey @gberger a PR was merged that handles this. If its still an issue for you, you can pull the recent version. Otherwise, thanks for originally reporting it!
