### ISSUE TITLE
How to get total number of emails in inbox?

### ISSUE THREAD

**Issue by gberger** [KartikTalwar/gmail.js#217]
`get.visible_emails` and `get.unread_emails()` provide similar functionality, but not what I need.

I need the number next to the navigation arrows.

**Comment by KartikTalwar** [comment]
I haven't tied to look total number of emails inside any JS variable yet but for any given page (main inbox view, labels, search, etc), you can get the total amount of emails from this DOM field

```js
$('.Di').text()
```

**Comment by KartikTalwar** [comment]
Looks like this exists in the `VIEW_DATA` variable so you should be able to access it via:

```
gmail.tracker.view_data[1][2]
```
