### ISSUE TITLE
using grunt on gmail.js throwing so many errors.

### ISSUE THREAD

**Issue by itsazzad** [KartikTalwar/gmail.js#223]
line 8    col 41    Strings must use singlequote.
  line 10   col 43    Strings must use singlequote.
  line 27   col 32    Strings must use singlequote.
  line 29   col 0     Identifier 'view_data' is not in camel case.
  line 30   col 55    Strings must use singlequote.
  line 34   col 0     Identifier 'last_active' is not in camel case.
  line 39   col 0     Identifier 'mac_address' is not in camel case.
  line 40   col 0     Identifier 'time_relative' is not in camel case.
  line 41   col 13    Missing semicolon.
  line 42   col 4     Missing semicolon.
  line 45   col 0     Identifier 'loggedin_accounts' is not in camel case.
  line 50   col 64    Missing semicolon.
  line 54   col 4     Missing semicolon.
  line 57   col 0     Identifier 'user_email' is not in camel case.
  line 93   col 0     Identifier 'is_thread' is not in camel case.
  line 94   col 0     Identifier 'check_1' is not in camel case.
  line 94   col 49    Strings must use singlequote.
  line 94   col 79    Strings must use singlequote.
  line 95   col 0     Identifier 'check_2' is not in camel case.
  line 95   col 0     Identifier 'email_ids' is not in camel case.
  line 97   col 0     Identifier 'check_1' is not in camel case.
  line 97   col 0     Identifier 'check_2' is not in camel case.
  line 101  col 0     Identifier 'inbox_content' is not in camel case.
  line 103  col 4     Missing semicolon.
  line 106  col 0     Identifier 'is_preview_pane' is not in camel case.
  line 107  col 0     Identifier 'inbox_content' is not in camel case.
  line 108  col 35    Strings must use singlequote.
  line 118  col 4     Missing semicolon.
  line 120  col 0     Identifier 'is_multiple_inbox' is not in camel case.
  line 123  col 4     Missing semicolon.
  line 126  col 0     Identifier 'is_horizontal_split' is not in camel case.
  line 127  col 0     Identifier 'inbox_content' is not in camel case.
  line 128  col 33    Strings must use singlequote.
  line 130  col 25    Expected '===' and instead saw '=='.
  line 131  col 4     Missing semicolon.
  line 134  col 0     Identifier 'is_vertical_split' is not in camel case.
  line 135  col 0     Identifier 'is_horizontal_split' is not in camel case.
  line 135  col 46    Expected '===' and instead saw '=='.
  line 136  col 4     Missing semicolon.
  line 139  col 0     Identifier 'is_tabbed_inbox' is not in camel case.
  line 140  col 20    Strings must use singlequote.
  line 140  col 31    Expected '===' and instead saw '=='.
  line 141  col 4     Missing semicolon.
  line 144  col 0     Identifier 'is_right_side_chat' is not in camel case.
  line 145  col 61    Expected '===' and instead saw '=='.
  line 146  col 4     Missing semicolon.
  line 149  col 0     Identifier 'is_google_apps_user' is not in camel case.
  line 150  col 0     Identifier 'user_email' is not in camel case.
  line 151  col 76    Expected '===' and instead saw '=='.
  line 152  col 4     Missing semicolon.
  line 152  col 4     Too many errors. (6% scanned).

**Comment by KartikTalwar** [comment]
Hi @itsazzad, most of the library code does not follow JS conventions, therefore grunt and other tooling libraries will show these errors. I currently do not have any plans to address these issues. Hope you understand
