### ISSUE TITLE
Maximum call stack size exceeded

### ISSUE THREAD

**Issue by itsazzad** [KartikTalwar/gmail.js#226]
Using observer `gmail.observe.on` throwing error. `Retry now` also not working. 
Only DOM observers are not throwing any error.

```
Uncaught CustomError: Error in protected function: Maximum call stack size exceeded
c @ rs=AHGWq9BDMLHtg5ZxdS1KbHbJyXMcPAJDmw:157
Hd.Hb @ rs=AHGWq9BDMLHtg5ZxdS1KbHbJyXMcPAJDmw:135
```

![screen shot 2016-01-06 at 7 51 54 pm](https://cloud.githubusercontent.com/assets/54909/12144005/0400a1f0-b4af-11e5-812e-7b3c18a5fc9a.png)

```
Oops… the system encountered a problem (#009) - Retrying in 9s…
```

![screen shot 2016-01-06 at 7 49 01 pm](https://cloud.githubusercontent.com/assets/54909/12144006/0bb15804-b4af-11e5-8aa9-675631cf0c4e.png)

```
Some Gmail features have failed to load. If this problem persists, try reloading the page or using the basic HTML version. Learn More.
```

![screen shot 2016-01-06 at 7 49 21 pm](https://cloud.githubusercontent.com/assets/54909/12144008/121d7952-b4af-11e5-9bf1-b2261aa1757f.png)

**Comment by KartikTalwar** [comment]
@itsazzad can you tell me:

- what the browser url is when you are running this
- what is the observe method being used
- what is your callback function
- what you are trying to do
- when does the error happen

An error like this does not make sense without any context on what you are doing. This seems highly dependent on your code and is therefore not reproducible without knowing everything that is going on

**Comment by itsazzad** [comment]
Thanks for asking the questions. Here are the answers:
Url: https://mail.google.com/mail/u/0/#inbox
Testing with all of the methods.
Using the default examples provided by you.
I am trying to add new tab in the tablist and will need to inject another external WooCommerce admin site using one iframe in the tab  and finally will need to communicate in between the injected site and the GMail UI during initiating an order from a particular mail and creating the order in a modal which will have interface provided from the WooCommerce admin. Upon saving the order will return to the GMail and will label the mail with the order id just generated from the WooCommerce.
Have found that error is happening during I am using `"all_frames": true` in the `"content_scripts"`.
```
  "content_scripts": [
    {
      "matches": [
        "*://mail.google.com/*",
	    "*://*.example.com/*",
        "*://192.168.169.170/*"
      ],
      "js": [
        "scripts/contentscript.js"
      ],
      "run_at": "document_end",
      "all_frames": true
    }
  ],
```

**Comment by KartikTalwar** [comment]
Well, from what you described, gmail.js is being loaded into all the iframes in the page even though it should only load into the main window. `all_frames` is making the content scripts load in all the frames and when you call an observer method, all frames are running that code hence exceeding the depth.

In your content script you should check if the `window.location` is in fact gmail and only run the observer methods if it the current location is the main gmail interface. Other than that I would recommend looking up/searching how to pass data between frames and communicating accordingly. 

Unfortunately this is not a bug in the gmail.js - the goal of the library is to provide a basic framework to build on top of gmail but the rest is dependent on the developer.

**Comment by josteink** [comment]
I can't reproduce. Is this still an issue with the latest version?

Because this is an old issue, I'll close this for now, but please re-open and provide more details if you can still reproduce this.
