### ISSUE TITLE
How to access body of reply/compose new email?

### ISSUE THREAD

**Issue by markon1** [KartikTalwar/gmail.js#231]
I'm trying to access and fill body of message, if "compose new email" is opened then my extension should populate body of it with some text, and if it's not open, and an conversation is opened, my extension should populate the body of reply email.

What I don't know how to do, is how to access the div element in which message is input? It's id is changed each time I access gmail. I thought about using gmail.dom.compose() but can't find any documentation on it. So, basically, I only need an method which returns div element storing text of email message, for both "Compose new email" and replying to an open conversation.

**Comment by KartikTalwar** [comment]
You should be able to access these properties for a dom compose method

https://github.com/KartikTalwar/gmail.js/blob/master/src/gmail.js#L2277-L2292

doing `.body` will give you the content

**Comment by markon1** [comment]
I don't think I understand this code, can you give me the line of code which selects the body of message (both for compose new and reply), like this pseudo code:

document.getElementByWhatever('divforenteringmessage').innerHTML = "mytext";
