### ISSUE TITLE
Can I send multiple email on 'before send' condition?

### ISSUE THREAD

**Issue by shaharpan** [KartikTalwar/gmail.js#232]
I am trying to make email tracking extension using this script. And its working great. Thanks for gmail.js. :)
So what basically I am doing is adding pixel image just before sending email. but issue is when there is multiple "to", I have only 1 pixel to send to all "to"s. So when any of the recipient open email. I cant tell exactly who opened the mail. (PS: Each pixel is unique and I get the unique pixel code from my server while I am in compose part) .So I want to add an condition that if there are multiple "to"s. I will req for multiple pixel in before send function. But if I try to make any XMLHttpRequest req from 'before send' mail is not getting sent and throwing error. 
I maybe doing everything wrong. Is there any way I can send multiple "to"s. with single email? 

Thanks in advance. :)

**Comment by shaharpan** [comment]
@KartikTalwar

**Comment by KartikTalwar** [comment]
I don't think this is possible. If there are multiple recipients, it will
still be a single email through gmail. It is going to be very hard to
distinguish between who opened the email. You can possibly use the ip
address from the pixel to see if you can distinguish the email address
ᐧ

**Comment by shaharpan** [comment]
https://mixmax.com/pricing/
In starter pack this guys are doing it. And I have investigated they send multiple pixel once you hit send.

**Comment by JerryBels** [comment]
@shaharpan I installed their extension just to test but as you said, this multiple identification is available only for paid (starter) plans, so I can't check it by myself. The thing I can see is that when I send a mail, there is only one mail sent in my "sent emails" list (so no different mail sent to each person) with a tracker in it - if I'm not wrong the same tracker seems to be sent to both the people I sent that mail to.

So, I'm really wondering HOW they would be able to identify who opens the mail ? It seems impossible to me ! If you have more informations I would gladly hear it.

**Comment by shaharpan** [comment]
@JerryBels : Nop they have only 1 email in sent emails, but on the receiving end all have different tracking code. 
PS: You can invite few people or dummy emails to get starter pack to try it out. I was just getting started so I haven't investigated much after it.

**Comment by JeroenCorthout** [comment]
They send a different email to every person, but fake in the header that
the email is also sent to the others.

In the sent items they probably post yet another email using the API.

Question remains: can you arrange this with Gmail.js?

Co-Founder
+32 499 21 77 82
salesflare.com

**Comment by shaharpan** [comment]
@JeroenCorthout : As far as I can understand I don't think Gmail.js can manipulate headers. Also  are you sure they are sending multiple emails and faking headers, . Also I would love to learn how headers can be manipulated with API.

**Comment by KartikTalwar** [comment]
Hey everyone, sorry for the long absence. I'll be able to start looking at all open issues and PRs starting Monday

**Comment by JeroenCorthout** [comment]
I'm not sure, but that's how it looks. Just try it for yourself: send one
email to two people, ask them to send you the original message ("Show
original" in Gmail). You'll see that it's different emails to each person,
but with the same header in terms of to, cc, etc..

Co-Founder
+32 499 21 77 82
salesflare.com
<http://llink.to/s?u=http://salesflare.com&e=48ed6e5d837775fca3cccff01e5025a9>

📰 here's what De Tijd wrote about Salesflare [dutch]
<http://llink.to/s?u=http://downloads.salesflare.com/press/SalesflareInDeTijd.pdf&e=48ed6e5d837775fca3cccff01e5025a9>

**Comment by JerryBels** [comment]
@JeroenCorthout hey, I just tried this, sent an email to two of my email accounts, and the tracker in it is exactly the same. No difference ! So I still don't get how they could identify which person opened the email.

@KartikTalwar that's a great news ! We need you badly :)

**Comment by shaharpan** [comment]
@JerryBels : Nop buddy. I also tried mixmax what I came to know is they use gmail HTTP Rest API. In sent there will be pixel for first id(mostly they are deleting multiple sent with API), but when I checked in other accounts there are diff tracking code/pixel.

**Comment by JeroenCorthout** [comment]
@shaharpan That sounds like a logical way of going about it. Only thing we need to be able to do is send multiple emails on 'before send' (and not send the original email of course, just add it to 'sent items').

**Comment by shaharpan** [comment]
I think message is being sent from the server using API, Any idea on how to change headers in such a way that email is sent to one person but shows to multiple. 
I think google groups works on the same logic. 
http://stackoverflow.com/questions/6378773/correct-email-headers-for-delivering-mailing-list-mail

**Comment by josteink** [comment]
> I don't think this is possible.

And thus I'm closing it.
