### ISSUE TITLE
api.get.current_page returns wrong value

### ISSUE THREAD

**Issue by WimRoose** [KartikTalwar/gmail.js#235]
Hi

I'm working on an extension that migrates e-mail messages to a google group, using api.get.selected_emails_data method. I've noticed that it uses a faulty URL to get the id's when not in inbox, because  api.get.current_page() returns only 'label', and not 'label/<label>'.

Quick fix could be

page = hash.join("/");

in stead of current 

if($.inArray(hash[0], pages) > -1) {
      page = hash[0];
}

Thanx for the good work! We had a company developing a gmail extension, but I wanted to add some features myself, so I'm integrating it with this great library

**Comment by KartikTalwar** [comment]
Hi @WimRoose could you clarify this a bit further? The goal of the current page is to return the type of the given view. In that context, `label` is the group, instead of `label/`. I would be interested in knowing how this affects your usecase

**Comment by WimRoose** [comment]
@KartikTalwar 

For instance: select a label in inbox, check some e-mails, and then trying to get ID's of selected ones:

api.helper.get.visible_emails_pre() {
var page = api.get.current_page();
.....
if(page.indexOf('label/') == 0) {
      url += '&cat=' + page.split('/')[1] +'&search=cat';
.....
}
Problem is that current_page returns only type ("label" in this case), while api.helper.get.visible_emails_pre() is expecting "label/<whichlabel>", to build a correct URL

api.get.current_page()  {
....
if($.inArray(hash[0], pages) > -1) {
      page = hash[0];   // comment by me: hash[1] contains <whichlabel>, but isn't returned
    }
}
....

Does this makes sense?
