### ISSUE TITLE
Multiple compose not working

### ISSUE THREAD

**Issue by shaharpan** [KartikTalwar/gmail.js#236]
When you have more than one compose window at time issues are coming. 
gmail.js works only for one compose window. Am I doing something wrong here? 
![1](https://cloud.githubusercontent.com/assets/14907693/13143489/4a075c48-d66a-11e5-9db0-a76d280ac28b.PNG)
![22](https://cloud.githubusercontent.com/assets/14907693/13143490/4a6fe72c-d66a-11e5-8249-8a5835dffee0.png)

**Comment by KartikTalwar** [comment]
Can you post your code?






On Thu, Feb 18, 2016 at 4:33 AM -0800, "shaharpan" <notifications@github.com> wrote:












When you have more than one compose window at time. gmail.js works only for one compose window.

**Comment by shaharpan** [comment]
var compose_ref = gmail.dom.composes()[0];
gmail.tools.add_compose_checkbox1(compose_ref,'checkbox','')
					gmail.tools.add_compose_checkbox(compose_ref,'checkbox',
					function(){
						console.log(email_link);
						var x = document.getElementById("saleshandy_crm_checkbox").checked;
						
						if(x==false)
						{
						$('#shtracking').remove();
						}
					    else
						{
						$( "<img id='shtracking' src_wait='"+email_link+"'  border='0' width='1' height='1'>" ).appendTo( ".Am" );}
					}
					,'')

----------------------------------------------------------------------------------------------------------------------
I was making a mistake, now If I change "var compose_ref = gmail.dom.composes()[0];" to "var compose_ref = gmail.dom.composes()[gmail.dom.composes().length-1];" . 
Buttons are visible to each compose window but variables get overwritten with last one. Maybe I have to find some solution. 
Thanks for the reply :)

**Comment by KartikTalwar** [comment]
Great!






On Thu, Feb 18, 2016 at 5:04 AM -0800, "shaharpan" <notifications@github.com> wrote:












var compose_ref = gmail.dom.composes()[0];

gmail.tools.add_compose_checkbox1(compose_ref,'checkbox','')

                    gmail.tools.add_compose_checkbox(compose_ref,'checkbox',

                    function(){

                        console.log(email_link);

                        var x = document.getElementById("saleshandy_crm_checkbox").checked;

                    if(x==false)
                    {
                    $('#shtracking').remove();
                    }
                    else
                    {
                    $( "<img id='shtracking' src_wait='"+email_link+"'  border='0' width='1' height='1'>" ).appendTo( ".Am" );}
                }
                ,'')






I was making a mistake, now If I change "var compose_ref = gmail.dom.composes()[0];" to "var compose_ref = gmail.dom.composes()[gmail.dom.composes().length-1];" . 

Buttons are visible to each compose window but variables get overwritten with last one. Maybe I have to find some solution. 

Thanks for the reply :)
