### ISSUE TITLE
How to get compose id ?

### ISSUE THREAD

**Issue by bhaveshvaghela32** [KartikTalwar/gmail.js#241]
I am trying to make email tracking extension using this script,I need a button on every compose window,when the button is clicked it will open popup window with some content,but problem is that it works on single compose box but not work on when multi compose box is opened.please check attachment

![gmailll](https://cloud.githubusercontent.com/assets/2259675/13671020/657d6924-e6f3-11e5-8b39-5c26451f7c41.png)

Problem may be solved if i get compose id, but i am not sure how to get compose id and integrate code with multi compose box

Thanks in advance :)

**Comment by KartikTalwar** [comment]
Please see https://github.com/KartikTalwar/gmail.js/issues/202

You can also search previous issues for more examples

**Comment by bhaveshvaghela32** [comment]
unfortunately it is not working for me,what i have done to append in gmail.js file as below 

     api.tools.add_compose_button =  function(composeWindow, content_html, onClickFunction,    styleClass) {

    var button = $(document.createElement('div'));
    var buttonClasses = 'T-I J-J5-Ji aoO L3 ';
    if(styleClass != undefined){
      buttonClasses += styleClass;
    }
    button.attr('class', buttonClasses);

    button.html(content_html);
    button.click(onClickFunction);

    composeWindow.find('.gU.Up  > .J-J5-Ji').append(button);

    return button;   }
  
  it defiantly work fine with multi compose open when clicked on compose button but not work when reply to email compose window if any main compose box is opened before replied to email

![mail](https://cloud.githubusercontent.com/assets/2259675/13703403/ec10dc00-e7bb-11e5-9239-a20dc233bb26.png)

**Comment by KartikTalwar** [comment]
I unfortunately do not have enough time at the moment to look into this but you can somehow use the `get.current_page()` to see if you are inside an email and try to find the dom yourself instead of relying on the library. That is the best I can help you out with. Sorry!
