### ISSUE TITLE
Uncaught ReferenceError: Gmail is not defined

### ISSUE THREAD

**Issue by amidave** [KartikTalwar/gmail.js#243]
For below line of code, the error is thrown: "Uncaught ReferenceError: Gmail is not defined"  :--
var gmail = Gmail();

Kindly provide me solution ASAP

**Comment by KartikTalwar** [comment]
How are you using this? I would recommend that you use the following sample chrome extension to get the example up and running https://github.com/KartikTalwar/gmail-chrome-extension-boilerplate

**Comment by amidave** [comment]
Hello Kartik,
Thank you so much for prompt response.
And You have built a great thing "Gmail.js".Congratulations from Me & My team. Proud to be an Indian.
Would like to keep in touch with you. Thanks once again !
-Ami

**Comment by cclambie** [comment]
I am following the instructions as per the [site quick usage](https://www.npmjs.com/package/gmail-js#quick-usage---chrome-console) to use it in Developer Console. 
I have injected the <script> into the <body> and also tried into the <head>

![Annotation 2020-01-16 091831](https://user-images.githubusercontent.com/877921/72510391-43d0ab80-3841-11ea-9968-1218517924e5.jpg)

I then try the next line
`var gmail = Gmail();`
However I get that same error.

**Comment by josteink** [comment]
That guide is obsolete.

Is the nodejs boilerplate-project linked in the project README.

https://github.com/josteink/gmailjs-node-boilerplate
