### ISSUE TITLE
Getting email details from folders other than Inbox

### ISSUE THREAD

**Issue by jocstar** [KartikTalwar/gmail.js#248]
Is this library intended to restrict you just to the inbox, or should you be able to fetch mail details from other folders?
Calling some of the get methods from a folder other than the inbox fail because the is_inside_email check prevents it, 
e.g. calling api.get.email_id, api.get.email_ids or api.get.email_data all fail if called from the sent items.
If I remove some of the checks, it does appear to fetch email details from the sent items folder too,  but I am nervous that there may be a reason this is normally prevented, and am unsure what purpose the current_page check serves, and what the preview pane actually refers to.

**Comment by josteink** [comment]
I think they're actually intended to be used inside the email-view, not inbox or sent-folder. If trying inside a email-thread inside either inbox or sent-items, I get the expected results.

So if you're still interested:

* Are you doing this from the list view or from email-view?
* And can you reproduce if this is still an issue?

**Comment by josteink** [comment]
Since I haven't heard anything new on this issue, I'm closing it.

Please re-open it if you still have an issue you need resolved.
