### ISSUE TITLE
Get cursor position during compose?

### ISSUE THREAD

**Issue by tayre** [KartikTalwar/gmail.js#250]
Is it possible to get the current position (similar to `selectionStart` and `selectionEnd` of a textarea) of a compose body?

**Comment by shaharpan** [comment]
Any solutions to this?

**Comment by stevelow1983** [comment]
+1

**Comment by shaharpan** [comment]
compose_ref.find("div[aria-label='Message Body']").focus();
//Get cursor position
var range = getSelection().getRangeAt(0);
var clone = range.cloneRange();
var node = $("<div>some content to add at cursor position</div>");
clone.insertNode(node[0]);

Hope this helps :)

**Comment by josteink** [comment]
While this is definitely a valid question, it's not something we'll add to the core API.

Closing this issue for now. Please re-open if you have anything you still need addressed.
