### ISSUE TITLE
Cannot read property 'pop' of null

### ISSUE THREAD

**Issue by danieltigse** [KartikTalwar/gmail.js#255]
I got this error:
gmail.js:2342 Uncaught TypeError: Cannot read property 'pop' of null

I write this quick fix:
```js
if(this.id_element.attr('class').match(/(^|\s)m([\S]*)/) != null)
        this.id = this.id_element.attr('class').match(/(^|\s)m([\S]*)/).pop();
```

**Comment by brentkelly** [comment]
@danieltigse this has been caused by a gmail update to their DOM which affects where they store an email id. Your fix will solve the js error but still mean the email id is not known. I've released a fix for my app so will submit a pull request shortly.
