### ISSUE TITLE
Gmail.js error: Cannot read property 'pop' of null

### ISSUE THREAD

**Issue by levis012** [KartikTalwar/gmail.js#259]
i'm using gmail.js for my chrome extension but today: 5/16/2016 it not working.
When i check on dev tool i have found error:
Uncaught TypeError: Cannot read property 'pop' of null
api.dom.email

Image: http://i.imgur.com/EH0tl8J.png

Please help me!
Thanks

**Comment by brentkelly** [comment]
@levis012 please look at other issues before posting new ones.

#255 is identical.
#256 & #257 should fix any issues.

**Comment by levis012** [comment]
Thanks for help.
