### ISSUE TITLE
new_email event takes 2 minutes delay after new email receives

### ISSUE THREAD

**Issue by aakankshabhujbal** [KartikTalwar/gmail.js#263]
I want to perform some operations as soon as new email receives in Inbox of Gmail. But new_email event is triggered after 2 minutes of email received. Is there any way we can remove this delay?

**Comment by aakankshabhujbal** [comment]
@KartikTalwar

**Comment by josteink** [comment]
Since I haven't heard anything new on this issue, I'm closing it.

Please re-open it if you still have an issue you need resolved.
