### ISSUE TITLE
Prevent compose box to close on Send button click

### ISSUE THREAD

**Issue by aakankshabhujbal** [KartikTalwar/gmail.js#264]
Is it possible to not to close compose box on Send button click of compose box. I want to perform some operations before sending email on Send button click. I am able to stop email sending process on button click but couldn't stop compose box to close. If anybody knows please help me.

**Comment by shaharpan** [comment]
prevent default action of click on send button and perform your operations. once done call dispatch event on send button.

**Comment by josteink** [comment]
You can probably use `gmail.dom.compose.dom("send_button")` to get the button here: https://github.com/KartikTalwar/gmail.js/blob/master/src/gmail.js#L2576

Closing this for now. Please re-open if you still have things you need addressed.

**Comment by cancan101** [comment]
Is this what you are suggesting:
```ts
    compose.dom('send_button')[0].addEventListener('click', (e: any) => {
      e.stopImmediatePropagation();
      // e.preventDefault();
    });
```

I had to use `stopImmediatePropagation`  rather than `preventDefault`, however then I am not sure how to call the original send as `send` just wraps click. I assume I have to clone the send button?
