### ISSUE TITLE
how to inject gmail.js direct in contentscript.js

### ISSUE THREAD

**Issue by VirendraNaruka** [KartikTalwar/gmail.js#274]
manifest.json
=-=======================
"content_scripts": [
        {
            "all_frames": true,
            "css": [ "css/gab.css" ],
            "js": ["js/jquery-1.10.2.min.js","js/content.js"],
            "matches": [ "https://mail.google.com/mail/*" ],
            "run_at": "document_end"
        }
    ],
# 
# Content Script Code is like 

var g = document.createElement('script');
g.src = chrome.extension.getURL('js/gmail.js');
(document.head || document.documentElement).appendChild(g);

console.log(':: g Src ::'+g.src);

var gmail;

g.onload = function() {
    console.log('::: Gmail .Js is Loaded ');
     gmail = new Gmail();
    console.log('::INitialized ::'); 
}

I getting "inject.js:11 Uncaught ReferenceError: Gmail is not defined"  Exception   please help

**Comment by VirendraNaruka** [comment]
Anybody can help help. Its urgent and I m waiting to get it resolve ASAP

**Comment by KartikTalwar** [comment]
Have you tried using the boilerplate from the readme?






On Thu, Jun 16, 2016 at 8:42 PM -0700, "VirendraNaruka" <notifications@github.com> wrote:












Anybody can help help. Its urgent and I m waiting to get it resolve ASAP

**Comment by JerryBels** [comment]
As @KartikTalwar said, use the boilerplate, it will help you a lot.

**Comment by djacobow** [comment]
The boilerplate example works through script injection. The OP asked how he can get gmail.js to run in a content script. If I understand the comments in the README, the answer is it can't. 

This has complications. For example, in Chrome, you can use sendMessage to communicate between your content script and your background script. sendMessage AFAICT does not work between the site script and the background script, so you need to figure out some alternate way to do it. I think a custom event can be used.

**Comment by jonathanalbangoodman** [comment]
Having this issue too. Using `postMessage` between the content script and web page to run various functions in this library (after injecting it to the web page). I do think it would be allot easier if this library was content script importable as it would be easier to call.

**Comment by djacobow** [comment]
Yeah, I resorted to postMessage, too. It's fine, but it's another twist. 

In my extension, I use a postMessage from the injected script to the the content script's message eventListener, which in turn fires a sendMessage to my background script, which catches it with an onMessage. Seems pretty janky, but works.

**Comment by ismailman** [comment]
Hey guys, the way to do this is to download the gmail.js through AJAX and then eval the download result. You do need to update your extension's manifest's content security policy to allow evaling.

Also, you need to do an indirect eval so that the gmail script gets executed in the global context instead of local context (https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/eval)

**Comment by josteink** [comment]
Another way to solve this is to use NodeJS type `require()` in your scripts and bundle them using WebPack or Browserify.

Either way I'm closing this issue as this seems to be a solved issue.

**Comment by anilreddyr7** [comment]
> Another way to solve this is to use NodeJS type `require()` in your scripts and bundle them using WebPack or Browserify.
> 
> Either way I'm closing this issue as this seems to be a solved issue.

Can we load gmail.js as one of the modules in content script? As per documentation, it should be loaded directly via script tag into Gmail DOM.

**Comment by josteink** [comment]
> Can we load gmail.js as one of the modules in content script? As per documentation, it should be loaded directly via script tag into Gmail DOM.

It can be loaded as a node module and then bundled (like it does in the boilerplate project), but the resulting script must be injected into regular DOM. 

Loading it as a content-script won’t work.

**Comment by anilreddyr7** [comment]
> > Can we load gmail.js as one of the modules in content script? As per documentation, it should be loaded directly via script tag into Gmail DOM.
> 
> It can be loaded as a node module and then bundled (like it does in the boilerplate project), but the resulting script must be injected into regular DOM.
> 
> Loading it as a content-script won’t work
Ok. Thanks for the update @josteink  May I know what exactly makes Gmailjs doesn't work if it is loaded as content script?

**Comment by anilreddyr7** [comment]
> > Can we load gmail.js as one of the modules in content script? As per documentation, it should be loaded directly via script tag into Gmail DOM.
> 
> It can be loaded as a node module and then bundled (like it does in the boilerplate project), but the resulting script must be injected into regular DOM.
> 
> Loading it as a content-script won’t work.

Ok. Thanks for the update @josteink May I know what exactly makes Gmailjs doesn't work if it is loaded as content script?

**Comment by josteink** [comment]
It hijacks Gmails XHR requests, and to do so it needs to be in the same security-context/namespace.

**Comment by anilreddyr7** [comment]
> context

Thanks @josteink. This information is helpful.

**Comment by cancan101** [comment]
@josteink as far as:
>It hijacks Gmails XHR requests, and to do so it needs to be in the same security-context/namespace.

are there any permissions that could be set in the manifest (v3) that would allow gmail.js to work when loaded as a content-script?

**Comment by josteink** [comment]
No idea. Not that I know off.

But injecting a regular script-bundle and a Gmail.js bundle is a fairly easy workaround, so I haven't really been looking either.
