### ISSUE TITLE
On before_send, add a attachment in mail ?

### ISSUE THREAD

**Issue by nmarques-ext-delfingen** [KartikTalwar/gmail.js#276]
Hi,

I was wondering if there was a way to attach a file before sending a composing mail ?

**Comment by dariospadoni** [comment]
I'm also looking for a way to add attachments to an email, is there a way to achieve this?

**Comment by OriAmir** [comment]
Hey , did you find a solution for this issue maybe ?
Did we can change the attachment content after gmail.observe.on("upload_attachment", function(**file**, xhr) {..}  method ? I try to make some changes to **file** argument but nothing change  ( for example change the name of file for start ,later complex things... )

**Comment by KartikTalwar** [comment]
I have not put too much effort into this (tried it once a year ago) but wasn't able to trigger a file upload programmatically. From my side at least, there is currently no way to do this (yet)

**Comment by OriAmir** [comment]
Thanks for your answer @KartikTalwar  . If it's nos possible yet to  upload a new file progrmmatically maybe there is some way to change the current file that already upload - name , content e.t.c  . I don't find any relevant information in the internet about this ):

**Comment by OriAmir** [comment]
I put this question also in [stackoverflow](http://stackoverflow.com/questions/40017977/add-change-attachment-in-gmail-compose-new-message)

I hope that we can get some answer for this

**Comment by whather** [comment]
How does inboxsdk do this then? I tested myself using their api and it works flawlessly. Both for inline images and external attachments. https://www.inboxsdk.com/docs/#Compose

**Comment by josteink** [comment]
> How does inboxsdk do this then? I tested myself using their api and it works flawlessly. Both for inline images and external attachments. https://www.inboxsdk.com/docs/#Compose

As someone completely unfamiliar with InboxSDK, that's hard to answer.

From my cursory glance, it seems that the InbocSDK is completely closed source and that the `InboxSDK.js` you are provided as a registered application-developer/API-consumer is merely a shim which loads the *actual* InboxSDK code dynamically.

Without someone providing me with the loaded InboxSDK code, I cannot answer that question.

**Comment by josteink** [comment]
Since I haven't heard anything new on this issue, I'm considering closing it.

Unless anyone has anything new to offer, this will be closed in the near future.

**Comment by shashikiran-im** [comment]
Hi,
I was looking for attachment feature from gmailJS. 
Could you please let me know if anybody had implemented it. 
Thanks in Advance.
