### ISSUE TITLE
Potential DOM Based Cross Site Scripting in gmail.js

### ISSUE THREAD

**Issue by gursev** [KartikTalwar/gmail.js#281]
The gmail.js library dynamically creates functions out of response data and executes them, leading to potential DOM based XSS issues.

Instance 1:

``` js
  api.tools.parse_response = function(response) {
      var parsedResponse = [],
          data, dataLength, endIndex, realData;

      try {

        // gmail post response structure
        // )}]'\n<datalength><rawData>\n<dataLength><rawData>...

        // prepare response, remove eval protectors
        response = response.replace(/\n/g, ' ');
        response = response.substring(response.indexOf("'") + 1, response.length);

        while(response.replace(/\s/g, '').length > 1) {

          // how long is the data to get
          dataLength = response.substring(0, response.indexOf('[')).replace(/\s/g, '');
          if (!dataLength) {dataLength = response.length;}

          endIndex = (parseInt(dataLength, 10) - 2) + response.indexOf('[');
          data = response.substring(response.indexOf('['), endIndex);

          var get_data = new Function('"use strict"; return ' + data); // DOM XSS when data is 'alert(1);'

```

Instance 2:

``` js
  api.helper.get.visible_emails_post = function(get_data) {
    var emails = [];

    var get_data = get_data.substring(get_data.indexOf('['), get_data.length);
        get_data = '"use strict"; return ' + get_data;
        get_data = new Function(get_data); // DOM XSS when data is 'alert(1);'
```

Instance 3:

``` js
  api.helper.get.email_data_post = function(get_data) {
    var get_data = get_data.substring(get_data.indexOf('['), get_data.length);
        get_data = '"use strict"; return ' + get_data;
        get_data = new Function(get_data); // DOM XSS when data is 'alert(1);'
```

@KartikTalwar

**Comment by gursev** [comment]
@KartikTalwar Can you please review this and provide your feedback? Also, if possible, can you please add security label to this bug?

**Comment by gravis** [comment]
Any chance to see this addressed?

**Comment by josteink** [comment]
Right now I don't see any proposed solution or substitute for the existing code and as such it's hard to come up with a way to address this issue. 

If we receive patches which address this will be happy to accept them though.

**Comment by josteink** [comment]
It's been suggested to me that we could use `JSON.parse` instead of creating a new `Function`-object, and in general that seems reasonable.

Based on the *extremely limited* testing I've done with `api.tools.parse_response`, this works for me. 

To facilitate more thorough testing, I can create a feature-branch where all use of `new Function()` is replaced by `JSON.parse`. Interested parties can then test this code and report back if that works for them.

If so, we can merge this back to master. Sounds like a plan?

**Comment by josteink** [comment]
And consider it done!

I've [created some basic unit-tests](https://github.com/KartikTalwar/gmail.js/commit/21148fdf63753d87ab753a1a82bd53bf8a237be8) for data-parsing on all functions where `new Function()` is used to process incoming data. On the current master-branch, all tests pass.

I've also created a [new feature-branch called `jsonparse`](https://github.com/KartikTalwar/gmail.js/tree/jsonparse) where all instances of `new Function()` is replaced with `JSON.parse()`. On this branch too, all tests currently pass.

So I'm decently confident that this will be a non-breaking change, but I would appreciate it if you guys would be willing test it first, and report back if you have any issues or not before we merge to `master`.

Ladies and gentlemen, the fate of this issue now lies in your hands. Make the most of it :)

**Comment by josteink** [comment]
Fixed in https://github.com/KartikTalwar/gmail.js/commit/a83436f499f9c01b04280af945a5a81137b6baf1.

Closing.
