### ISSUE TITLE
Consider using Google's official Gmail API

### ISSUE THREAD

**Issue by tedb** [KartikTalwar/gmail.js#282]
You may be interested to know Google has an official REST API and associated Javascript library.  https://developers.google.com/gmail/api/
https://developers.google.com/gmail/api/quickstart/js

**Comment by KartikTalwar** [comment]
Thanks for the links! Although the gmail api exist with a supporting js library, the gmail of this repo is to provide an abstraction on the mail actions and UI additions to gmail with the sole purpose of making chrome extensions on top of gmail easier. This is not a javascript library for gmail data
