### ISSUE TITLE
Is it currently possible to add a "One-Click Action" to an email thread?

### ISSUE THREAD

**Issue by tzusman** [KartikTalwar/gmail.js#283]
I'd like to parse emails for certain content, and if found, add a [One Click Action button](https://developers.google.com/gmail/markup/actions/actions-overview#in-app_actions) to the thread.

Is this currently supported?  If not, I'd be interested in implementing, but a finger in the right direction would help a ton.

**Comment by brentkelly** [comment]
Should definitely be doable with a ``view_email`` dom observer and calling the ``data`` method on a passed ``api.dom.email`` object.

**Comment by tzusman** [comment]
@brentkelly I'm not seeing a method for adding an "Action" button though.  I'm sure its pretty straight forward to determine which emails I want to add the button to, it's the actual adding of the button that I'm unsure about.

**Comment by brentkelly** [comment]
@tzusman I just use standard DOM injection to do that. We centralise access to various elements of an email using the ``dom`` method for the ``api.dom.email`` object. If you call that method without any elements you can than just use jQuery ``.find`` to access nodes & insert as normal.

**Comment by tzusman** [comment]
@brentkelly Okay cool.  I'm gonna close out the issue.  Might re-open if I run into troubles.  Thanks for the help!
