### ISSUE TITLE
get.email_id() not working

### ISSUE THREAD

**Issue by uri3000** [KartikTalwar/gmail.js#288]
It always returns null, even when I am definitely in an open email view.
This is happening because api.check.is_inside_email() returns false.
That is happening because inside is_inside_email() we have this condition: 

 if(api.get.current_page() != null && !api.check.is_preview_pane()) {
      return false;
  }

current_page = "email" and is_preview_pane() = false

How can I get the email_id without subscribing to email_open?? (I need to receive the Id even when the page is refreshed on the email view, that's why subscribing to the event will not work).

Thanks

**Comment by KartikTalwar** [comment]
hey @uri3000 would you be able to confirm which version of the library you are using? I updated it a few days ago and `get.email_id()` should be working fine

**Comment by uri3000** [comment]
Yes it is working thanks!! It happened because I downloaded the extension boilerplate which appearantly was not updated.
