### ISSUE TITLE
Get gmail.dom.email on onload event

### ISSUE THREAD

**Issue by volodyad** [KartikTalwar/gmail.js#302]
I want to access to viewed email $el on load event,
I can not use event 'view_email', because when I reload detail email page, this event is not executed.
Here is my code

gmail.observe.on("load", function() {
     var  mailId = gmail.get.email_id();
     var  email = gmail.dom.email(mailId);
     var  el = email.$el;
}

This solution only works for page with single email, but when I try to reload detail page with thread of emails I got the error -  'api.dom.email called with invalid element/id'.
How can I access dom.email inside thread?

**Comment by michi88** [comment]
FYI this is what I do on load:

```javascript
    if (gmail.check.is_inside_email()) {
      checkAttachments();
    }

    gmail.observe.on('open_email', function () {
      checkAttachments();
    });

    gmail.observe.on('view_thread', function(obj) {
      checkAttachments();
    });

    gmail.observe.on('view_email', function(obj) {
      checkAttachments();
    });

    gmail.observe.on('show_newly_arrived_message', function(obj) {
      checkAttachments();
    });

    $('.kv').on('click', function () {
      // click on the email to expand (needed for hard page load on refresh)
      checkAttachments();
    });
```
Although I don't really care if `checkAttachments()` is called too often. Might not be like that in your case...

**Comment by josteink** [comment]
Considering OP hasn't responded to this issue since filing it, I'm going to assume this is no longer a problem.

Because of that, I'm closing this issue. Please re-open if you still have something you need to resolve.
