### ISSUE TITLE
view_thread and view_email on load

### ISSUE THREAD

**Issue by JerryBels** [KartikTalwar/gmail.js#313]
Hello,

I'm trying to apply some transformations to the dom every time an email is opened. It works great when the email is clicked...

    gmail.observe.on('view_thread', function(obj) {
        console.log('view_thread', obj);
    });
    gmail.observe.on('view_email', function(obj) {
        console.log(obj.from());
        var tmp = $("<span>").text("Owaks").css("background-color", "red");
        $(obj.dom("star")).after(tmp);
    });

But when the window opens directly on an email, it doesn't work - expected since the XHR didn't happened after gmail.js has finished loading or anything like that. I tried to 

    if(gmail.check.is_inside_email()) {
        var email = gmail.dom.email(gmail.get.email_id());
        console.log(email.from());
    }

And well... 

    api.dom.email called with invalid element/id
    Uncaught (in promise) TypeError: email.from is not a function(…)

Any idea ? Thanks ahead

**Comment by KartikTalwar** [comment]
@JerryBels what is returned if you just console log `email` in that if statement. Is that a valid dom email object? Does `email.from` work?

**Comment by JerryBels** [comment]
I don't know why, but in the `email_id` get function, it checks for

    if(api.check.is_preview_pane()) {

before trying to get the ID from the dom. So it's always returning the thread id from the URL, which doesn't work with `gmail.dom.email(id)` - that's for the first error. I did a little workaround in my code to get the real email_id using 

    if(gmail.check.is_inside_email()) {
        var mIdArr = gmail.dom.email_contents();
        if(mIdArr.length) {
            for(i = 0; i < mIdArr.length; i++) {
                var mId = mIdArr[i].getAttribute('class').split(' ')[2];
                mId = mId.substring(1, mId.length);
                console.log(mId);

                var email = gmail.dom.email(mId);
                console.log(email);
                console.log(email.from());
            }
        }
    }

Here is the console : 

    Object {id: "15724ffc32c29dde", id_element: n.fn.init[1], $el: n.fn.init[1]}
    Uncaught (in promise) TypeError: email.from is not a function(…)

If I expand the `email` object, it doesn't have any `from` function in its prototype. 

	$el : n.fn.init[1]
	compose : (element)
	composes : ()
	email : (element)
	email_body : ()
	email_contents : ()
	email_subject : ()
	get_left_sidebar_links : ()
	id : "1573ead5b1463c8d"
	id_element : n.fn.init[1]
	inbox_content : ()
	inboxes : ()
	search_bar : ()
	thread : (element)
	toolbar : ()

The `email()` function of the `email` object (managing to follow ? ^^) HAS a `from()` function, but if I try to call `email.email()` I have the error popping again

    api.dom.email called with invalid element/id

**Comment by JerryBels** [comment]
I really don't get it. If I `console.log`  in `api.dom.email` to see if everything went fine when doing 

    var email = gmail.dom.email(mId);

Everything is great. So why when I `console.log` the `email` variable after that it has functions that are linked to the `api.dom` object, and not the ones from `$.extend(api.dom.email.prototype` ?! It doesn't make any sense :/

**Comment by JerryBels** [comment]
Solved by a nide guy [on Stackoverflow](http://stackoverflow.com/questions/39723118/jquery-extend-not-returning-expected-functions/39723207#39723207) 

Basically to access the extended prototype we need to create an instance with `new`

    var email = new gmail.dom.email(mId);

**Comment by yogita3279** [comment]
Hi there how can i retrieve the email id from to field at the time of composing email.

**Comment by josteink** [comment]
You can't. Search closed issues for possible workarounds. 

Closing as duplicate.
