### ISSUE TITLE
Get methods return undefined / empty string

### ISSUE THREAD

**Issue by OriAmir** [KartikTalwar/gmail.js#315]
Hi all , I  have 2 questions 
**1.** I just use your [hello world extension for gmail ](https://github.com/KartikTalwar/gmail-chrome-extension-boilerplate) and it's work fine ( i updated the gmail.js file) . Now, I try to get some information about mails and when I use the methods gmail.get.email_subject() & gmail.get.email_id() and many others it's return undefined or just empty string . Did I need to do something special ? I just add this methods in the function main on main.js .

this is the main.js code:

 var gmail;
function refresh(f) {
        if( (/in/.test(document.readyState)) || (typeof Gmail === undefined) ) {
                             setTimeout('refresh(' + f + ')', 10);
        } else {
        f();
   }
}

var main = function(){
    gmail = new Gmail();
    console.log('Hello,', gmail.get.user_email()) ----> **ok**
    console.log(gmail.get.email_subject());  ----> **return empty string**
    console.log(gmail.get.email_id()); ---> **return undefined (when I am  into mail)**
    
}
refresh(main);  

**2**. I want to add some little button behind the red button of 'compose new button' . I see that you have a function that add a button to the toolbar and it's work great. I try to do some similar method and to add there a button (I take the id of the div with inspect ) in the same way but it's not add it! someone maybe know how to add button to there?

**Thanks all .**

**Comment by bravin8** [comment]
To get email_id and email_subject you should open the email in the DOM. Read the documentation in the gmail.js API read me file.

**Comment by OriAmir** [comment]
**Thank you** for your anewer @bravin8 but I don't understand how to :

> you should open the email in the DOM

I read the documentation and i see this : 

> DOM
> 
> These methods return the DOM data itself . . . 

But how this connect with other methods to get the email_subject or something else? I want full access to the message .. 

Thanks again .

**Comment by bravin8** [comment]
You can't get those information in the inbox view. You should open the email thread or email conversation to get email_subject or email_id details.

**Comment by OriAmir** [comment]
thanks!
