### ISSUE TITLE
Add special mark to new message and than read this mark

### ISSUE THREAD

**Issue by OriAmir** [KartikTalwar/gmail.js#318]
Hey , I try to create a gmail extension that encrypt / decrypt gmail messages . I want to add some additional mark when sending a new message . Then, in 'read mode' I could know if the current message is actually encrypted . 
I think on adding some attribute or something in gmail.observe.before('send_message' ... ) but I don't know if it's possible and if yes how could I check this mark when I read some message with observe 'view thread' / 'view email'  ...

**Thanks** for your helping , this library is just amazing .

**Comment by AltafUrRehman** [comment]
You can send custom attributes to Gmail but google will not save any custom attribute on their server.
However you can save ids of marked emails in chrome's localStorage or in your own server via some API.
And then in read mode you can match email id with saved marked emails ids, to check email is encrypted or not.

**Comment by OriAmir** [comment]
Tnx , but I need to save this id when I send the message ..And when I am in new compose window this message still not get ID ( not draft message ) so I don't have what to save

**Comment by josteink** [comment]
What I've done (and which works for now) is to await the "Email is sent" toast. This toast contains a link which contains the ID of the newly sent email message. You can then connect that to your compose-ID somehow.

You cannot persist "extended MAPI properties" like you can with Microsoft Exchange... So if you need some other form of permanent marker, you'll have to figure that out and implement it yourself.

**Comment by josteink** [comment]
Since I've received no feedback on this issue, I will assume this problem has been settled one way or another.

Please re-open if you still have anything you need resolved.
