### ISSUE TITLE
gmail.observe.before() not working

### ISSUE THREAD

**Issue by chetanbuddh** [KartikTalwar/gmail.js#319]
gmail.observe.before('send_message', function(url, body, data, xhr){
  var body_params = xhr.xhrParams.body_params;

  // lets cc this email to someone extra if the subject is 'Fake example'
  if(data.subject == 'Fake example') {
    if(body_params.cc) {
      if(typeof body_params.cc != 'object') body_params.cc = [ body_params.cc ];
    } else {
      body_params.cc = [];
    }
    body_params.cc.push(xyz@gmail.com');
  }

  // now change the subject
  body_params.subject = 'Subject overwritten!';
  console.log("sending message, url:", url, 'body', body, 'email_data', data, 'xhr', xhr);
});

**Comment by OriAmir** [comment]
for me it's work great . try to explain more...

**Comment by shaharpan** [comment]
When some other plugin is enabled. this method does not fire.

**Comment by abhijitflomio** [comment]
I currently use 0.5 version of gmail.js

manifest.json
{
    "name": "demo",
    "version": "0.1",
    "description": "",
    "content_scripts": [
    {
        "matches": ["https://mail.google.com/*"],
        "js": ["content.js"]
    }
    ],
     "permissions": [
  "contextMenus",
	"tabs", "storage"],
    "web_accessible_resources": [
        "jquery-1.10.2.min.js",
        "gmail.js",
        "filterapi.js",
        "webservice.js",
        "main.js"
        
    ],
    "manifest_version": 2
}

**Comment by chetanbuddh** [comment]
I currently use 0.5 version of gmail.js

below my manifest.json code
{
    "name": "new demo",
    "version": "0.1",
    "description": "",
    "content_scripts": [
    {
        "matches": ["https://mail.google.com/*"],
        "js": ["content.js"]
    }
    ],
     "permissions": [
  "contextMenus",
	"tabs", "storage","https://app.xyz.com/*"],
    "web_accessible_resources": [
        "jquery-1.10.2.min.js",
        "gmail.js",
        "filterapi.js",
        "webservice.js",
        "main.js"
        
    ],
    "manifest_version": 2
}

**Comment by josteink** [comment]
> I currently use 0.5 version of gmail.js

Can you still reproduce this on latest version?

**Comment by bersonsteve** [comment]
Hi, I am having the same issue while using the latest version of gmail.js

When using gmail.observe.before('send_message' ..... the email is being sent prior of executing the code.

**Comment by josteink** [comment]
@bersonsteve: I think `on.before('send_message')` is a bit of a special case.

There have been numerous issue filed for that where people have had different needs and found different workarounds.

I advice you check the closed issues and see if you can find anything working for you.
