### ISSUE TITLE
Adhere to objective code-quality metrics as per eslint

### ISSUE THREAD

**Issue by josteink** [KartikTalwar/gmail.js#327]
Currently, editing gmail.js in any editor which tries to do code-linting through `eslint` or `jslint` is just painful.

````bash
$ npm install -g eslint
$ wc -l src/gmail.js
2626 src/gmail.js
$ eslint src/gmail.js| wc -l
1989
````

So almost one warning per code-line, or at least pretty close when you count out comments and code-doc.

The amount of warnings and inconsistencies causes some editors (like Emacs) to disable linting all together.

The good news is that most of these warnings are due to inconsistent tab-size and quote-type usage or simple things like that. Eliminate these through basic document-reflowing and search & replace, and we get something much more manageable:

````
$ eslint src/gmail.js| wc -l
51
````

Now we're talking! That's *much* better.

My proposal, if you accept it, is that I'll clean up entire gmail.js for all linting-warnings. I'll present the result as a PR, with each cleanup-step as its separate commit, so you can inspect them as you like.

If we do this, we can afterwards setup a Travis CI-build for gmail.js (it's simple and free), which all new commits and PRs trigger, which ensures that we keep a consistent code-quality from this point on.

@KartikTalwar: Does that sound like an interesting proposition? Should I proceed with this work?

**Comment by KartikTalwar** [comment]
Sounds good to me, thanks for prioritizing this!

**Comment by josteink** [comment]
Cool. Obviously this kind of reformatting would create impossible merges for all existing PRs, so I've taken the liberty to agressively merge, complete or close pretty much all of the open ones.

Right now there's one remaining, and when that is landed, I'll see what I can get done on this issue.

**Comment by josteink** [comment]
I've created a new branch called eslint:

https://github.com/KartikTalwar/gmail.js/tree/eslint

Running `npm run test` in that branch tests the code using eslint, with a [slightly modified default config](https://github.com/KartikTalwar/gmail.js/commit/f969d61df2df71748ec00a2ef156b8555deef014).

The results can be seen below:

````bash
$ npm run test

> gmail-js@0.5.3 test /home/jostein/build/gmail.js
> eslint src/*.js


/home/jostein/build/gmail.js/src/gmail.js
   650:66  warning  'j' is defined but never used          no-unused-vars
   691:48  warning  'xhr' is defined but never used        no-unused-vars
   942:85  warning  'password' is defined but never used   no-unused-vars
  1086:44  warning  'response' is defined but never used   no-unused-vars
  1122:65  warning  'callbacks' is defined but never used  no-unused-vars
  1442:86  warning  'sub' is defined but never used        no-unused-vars

✖ 6 problems (0 errors, 6 warnings)
````

I've kept no-unused-vars as a `warning` because it can [highlight actual errors](https://github.com/KartikTalwar/gmail.js/commit/77fd32ea99884d99e6e6b7a82ba5955c413ea2e9).

But apart from that eslint now returns 0 errors on the current config.

That makes me happier, but not happy enough.

Running `jshint` on the same code still shows we have lots to improve:

````bash
jshint gmail.js 
gmail.js: line 41, col 88, Use '!==' to compare with 'null'.
gmail.js: line 42, col 92, Use '!==' to compare with 'null'.
gmail.js: line 192, col 27, Use '===' to compare with '0'.
gmail.js: line 197, col 48, Use '===' to compare with 'false'.
....
snip
....
gmail.js: line 1868, col 32, The Function constructor is a form of eval.
gmail.js: line 1868, col 32, Too many errors. (69% scanned).

51 errors
````

I'll see if I can find out how to tweak `.eslintrc.json` to report similar errors, so that I can get those cleaned up as well.

But for now, that should give you something to look at. I think this is getting a lot better quite quickly :)

**Comment by josteink** [comment]
I've pushed some more. Let me know what you think :)

**Comment by KartikTalwar** [comment]
Going to test this out later today!
