### ISSUE TITLE
Need to setup CI-build.

### ISSUE THREAD

**Issue by josteink** [KartikTalwar/gmail.js#331]
To enforce the code-standard set by `eslint`, we need a CI-build to verify incoming patches and PRs.

To do this, the repo owner (that's you @KartikTalwar ) need to log into [Travis CI](https://travis-ci.org/) and enable CI for this repo.

After that we'll need to create a `travis.yml` file and setup a script/job to be run by the CI-build.

@KartikTalwar:  If you can get Travis setup for this repo, I can handle the rest.

**Comment by KartikTalwar** [comment]
done!

**Comment by josteink** [comment]
To follow up on this issue (which again is a follow up for [this issue](https://github.com/KartikTalwar/gmail.js/issues/327)), I've done the following things:

* Added a travis configuration file: https://github.com/KartikTalwar/gmail.js/commit/59c8d46157b04b4ca2cab0ecc2e17283d7e2c271
* Modified gmail.js to not *strictly* depend on `window` and `jQuery`. This allows it to run in a server-side unit-test harness, and thus as part of the CI-build: https://github.com/KartikTalwar/gmail.js/commit/3339c190f5eec34ddf771a949a72115536a15ae3
* Add a `mocha`-based unit-test setup, a few unit-tests. Use CI-build to also validate TypeScript-compilation and Unit-tests: https://github.com/KartikTalwar/gmail.js/commit/33fa7af1a00db012033e3e76c913dbd2729e41bf
* Add build-status badge to README.md. It looks nice :) https://github.com/KartikTalwar/gmail.js/commit/8baa2b496218450cbffc819618115a4fd0659a8a

With that in place, I'm starting to be happy about the state of affairs. I'll obviously want to add more unit-tests in the future, but you have to start somewhere :)

What do you think? Is this all OK to you, or do you feel like I am running amok without your approval at this point?

**Comment by KartikTalwar** [comment]
>What do you think? Is this all OK to you, or do you feel like I am running amok without your approval at this point?

I think this is wonderful! I really can't thank you enough for taking charge - I'm glad that all this is being worked on. If you think something else can be improved, please feel free to work on it. Since you are already making issues instead of directly pushing changes, I am/will comment and contribute as needed :-)

**Comment by josteink** [comment]
> I think this is wonderful! I really can't thank you enough for taking charge - I'm glad that all this is being worked on. If you think something else can be improved, please feel free to work on it.

Awesome. Will do.

> Since you are already making issues instead of directly pushing changes, I am/will comment and contribute as needed :-)

To be honest I cheated on [this one](https://github.com/KartikTalwar/gmail.js/issues/332), but it seemed like a small enough change not to warrant too much noise.

Anyway. Glad to be of service!

**Comment by KartikTalwar** [comment]
It's all good, I still keep up with what gets committed and talked about :-)
