### ISSUE TITLE
Window.opener === null when registering xhr_watcher

### ISSUE THREAD

**Issue by michi88** [KartikTalwar/gmail.js#336]
I've see some (not a lot) errors coming in from my extension in production.

Happens when `api.tools.xhr_watcher` is called and this line is executed:

`var win = top.document.getElementById("js_frame") ? top.document.getElementById("js_frame").contentDocument.defaultView : window.opener.top.document.getElementById("js_frame").contentDocument.defaultView;`

So the question really is in which cases don't we have `js_frame` and what exactly do we want to do in that case?

**Comment by josteink** [comment]
I think I would try to decompose that section into its own function interspersed over several lines of code. 

That way you could put a breakpoint on the line where window.opener is probed (and fails!) and from that breakpoint you should be able to inspect the conditions under which this error occurs. 

That would probably be a good start  before we decide on which changes we need to make. 

Sounds like a plan?

**Comment by michi88** [comment]
Yeah, so this is the error I found:

![image](https://cloud.githubusercontent.com/assets/1010260/20531525/571cf7b0-b0d7-11e6-9b00-a7d7d62ab772.png)

As the url is `https://mail.google.com/` and not `https://mail.google.com/mail/u/0/` maybe I'm calling the watcher too soon?

This is what I do currently:

```javascript
var initSRforGmail = function initSRforGmail() {

  var gmail;

  var refresh = function refresh(f) {
    if (/in/.test(document.readyState) || typeof Gmail === 'undefined' || typeof window.jQuery === 'undefined') {
      setTimeout(function () {
        refresh(f);
      }, 10);
    } else {
      f();
    }
  };

  var main = function main() {

    gmail = new Gmail();
    gmail.observe.on('open_email', function () {
      someFunc();
    });
    // .... other stuff including more gmail.observe.on calls
  }
  refresh(main);
};

try {
  initSRforGmail();
} catch (e) {
  SRErrorHandler.captureException(e);
}
```

**Comment by michi88** [comment]
Oh and by the way... I can't reproduce it :)

I don't see this error often and I have nobody complaining that it doesn't work (no big deal) but we might have some logic here that needs to be changed.

**Comment by michi88** [comment]
Ah maybe I should use `gmail.observe.on("load")` first before I register the other watchers as gmail needs to have loaded the `top.document.getElementById("js_frame")` iframe. 

```javascript
        else if(action === "load") {

            // wait until the gmail interface has finished loading and then
            // execute the passed handler. If interface is already loaded,
            // then will just execute callback
            if(api.dom.inbox_content().length) return callback();
            var load_count = 0;
            var delay = 200; // 200ms per check
            var attempts = 50; // try 50 times before giving up & assuming an error
            var timer = setInterval(function() {
                var test = api.dom.inbox_content().length;
                if(test > 0) {
                    clearInterval(timer);
                    return callback();
                } else if(++load_count > attempts) {
                    clearInterval(timer);
                    console.log("Failed to detect interface load in " + (delay*attempts/1000) + " seconds. Will automatically fire event in 5 further seconds.");
                    setTimeout(callback, 5000);
                }
            }, delay);
            return true;
        }
```

The line btw changed in this commit 5a9d8c8760dafb8ada96d6de194945d7ca5949fb this was probably done as when gmail opens in a popup it doesn't need to include that "js_frame" iframe and thus we cannot find it.

I assume we need to bind to that window as gmail sends xhr from that iframe. Right?

**Comment by josteink** [comment]
I don't know what the best approach is here.

What I've done is a NodeJS-based approach where I simply `require("gmail-js")` in my extension and use `browserify` to bundle it all up to one JS-file.

That way, when I `require("gmail-js")` (which in turn will self `require("jquery")`) I don't have to worry about if or when these libraries are loaded. They are loaded synchronously from the same bundled file, the second I request them. Simple.

It makes bootstrapping an extension a lot easier and you don't have to worry about these things.

**Comment by josteink** [comment]
I'm also using the DOM event `"load"` before I initialize any of my code. This at least works for me.

**Comment by michi88** [comment]
About the gmail-js/jquery require stuff, yes you are right. That is definitely better.

Don't you think we should do some checks in the `api.tools.xhr_watcher` function when library users do not wait for gmail to be loaded? Because I think it just fails because the "js_frame" iframe is not created yet by gmail.

Looking at the gmail-js api (from a distance) I would consider it expected behaviour that when I call `gmail.observe.on('open_email')` without waiting for 'load' it should just work (and it does most of the time).

IMO we should at least document it more prominently that one should wait for load first OR fix that we wait for load (of the js_frame) internally when we init the watchers.

What do you think?

**Comment by josteink** [comment]
Agreed that something could be done to make things more obvious.

Right now I think having better documentation would probably be a acceptable short term approach, and the least risky of the two options.

**Comment by josteink** [comment]
We could also make the failure mode more obvious by adding logging to function when window cannot be located with a helpful suggestion about the load event. 

That way we should cover the case of people not to reading the documentation as well.

**Comment by michi88** [comment]
Agreed, we should still throw an error though as else I for example wouldn't have noticed in the first place if it would only log to the console. As I've seen this error in my error tracking in production.

Also, we should probably set `api.tracker.xhr_init = false;` when that happens so that it can be called again. Now it fails and you cannot call it again.

**Comment by josteink** [comment]
> Agreed, we should still throw an error though as else I for example wouldn't have noticed in the first place if it would only log to the console. As I've seen this error in my error tracking in production.

Agreed.

> Also, we should probably set api.tracker.xhr_init = false; when that happens so that it can be called again. 

Disagree on this one. I think we should encourage correct use, rather than trying to make things work when we're clearly in an incorrect state.

That is the way of PHP (continue rolling forward, no matter what) and I don't think that's a good design-philosophy.

**Comment by michi88** [comment]
In general I agree and probably they won't be able to recover from the error anyway.

From a gmail-js internal state standpoint I would argue that `api.tracker.xhr_init = true;` is not 'true' anymore when it fails.

But again, they will probably not recover from it anyway.

So:

- We update the documentation (and maybe https://github.com/KartikTalwar/gmail-chrome-extension-boilerplate to wrap `console.log('Hello,', gmail.get.user_email())` in the load event?) to have people wait for the 'load' event.
- We throw a more describing error when we can't find the window that has js_frame iframe

**Comment by josteink** [comment]
Yeah. That sounds exactly like what I had in mind.

**Comment by michi88** [comment]
Cool, will make a PR

**Comment by michi88** [comment]
What would a good message be?

```javascript
throw "Cannot register the xhr watcher as mail.google.com is not fully loaded yet. Please wrap your code in `gmail.observe.on(\"load\")`";
```

Too specific maybe?

**Comment by josteink** [comment]
I think that's good. let's keep it until somebody has a better suggestion.
