### ISSUE TITLE
Find what connected gmail user's number is linked to a specific email address

### ISSUE THREAD

**Issue by JerryBels** [KartikTalwar/gmail.js#345]
Hello guys !

Gmail address looks like 

    https://mail.google.com/mail/u/X/

Where X is a number, depending on what account you logged first into this browser. If you login into your google account as user@gmail.com , and then opens a window to log in with another account - say userone@gmail.com , it will be like this : 

    https://mail.google.com/mail/u/0/ => user@gmail.com
    https://mail.google.com/mail/u/1/ => userone@gmail.com

I want to know if there is any way, using gmail.js or not, to find the X by providing the email. If I have userone@gmail.com to provide, I want to get "1" so I can open a new tab with the relevant account !

Thanks ahead !

**Comment by KartikTalwar** [comment]
@JerryBels `api.get.loggedin_accounts` response contains the `index` key which should tell you the value

**Comment by JerryBels** [comment]
Hum... Thanks @KartikTalwar , that's already nice, but what if I want to get that from the background page, when a push notification comes in for example ? Is it even possible ?

**Comment by JerryBels** [comment]
I found a way ! When a gmail page loads, simply get the list and send it over with a customEvent to background page, and store it in `localStorage` :)
