### ISSUE TITLE
using Gmail Api in content script

### ISSUE THREAD

**Issue by OriAmir** [KartikTalwar/gmail.js#350]
Hey all  , I need to use some functionally of gmail api in my extension .
I create oauth2 in background file and I am trying to use the gapi.client in my content script without success...
I post[ my question is stackoverflow](http://stackoverflow.com/questions/41012489/using-gmail-api-in-chrome-extension-in-content-scripts)
Hope that someone could help me please..

thanks!

**Comment by josteink** [comment]
You cannot use the Gmail.js API inside a content-script.

If you need to do separate processing in the browser context, content-script and background-scripts, you will need to rely on corss-context messaging.

Basically from content-script you need to post a message to your browser-context, where you invoke the gmail.js API, and that should again post the results pack to the content-script.

It's no fun, but that's the only option the current browser security model allows us.
