### ISSUE TITLE
API for attachments

### ISSUE THREAD

**Issue by josteink** [KartikTalwar/gmail.js#352]
I'm working on adding functionality for accessing attachments. So far I'm pushing my changes to the [attachments](https://github.com/KartikTalwar/gmail.js/tree/attachments) branch.

Is this something you'd like to review, or should I just push to master when it's good enough for my needs?

Any opinion?

cc: @KartikTalwar

**Comment by KartikTalwar** [comment]
Feel free to push to master if its a feature that helps others as well :-)

**Comment by josteink** [comment]
Thanks. Consider it done :)
