### ISSUE TITLE
Need to get current message ID in conversation view

### ISSUE THREAD

**Issue by ConnGator** [KartikTalwar/gmail.js#354]
I am trying to get the message ID of the currently expanded message of a thread in conversation view but gmail.get.email_id() is returning the message ID of the first message in the thread.  Is there a different way of getting the current message?

Thanks for a wonderful library.

**Comment by josteink** [comment]
Bind on the view email event.  the parameters passed into that function is the current email.

**Comment by ConnGator** [comment]
Many thanks, worked like a charm.
