### ISSUE TITLE
Update inbox event

### ISSUE THREAD

**Issue by markjerz** [KartikTalwar/gmail.js#355]
Hi,

I'm adding an extra td in to the gmail inbox rows so as to add an extra button. Now Gmail seems to update those rows every now and then which loses my extra td. I'm currently observing the following events to re-add my td but am missing something else:

new_email
refresh
poll

Any ideas?

**Comment by josteink** [comment]
I've used something like the following to ensure my code runs when *something* happens in the main UI:

````javascript
function onWindowEvent(e) {
  // your (re-)init code here.
}

window.onhashchange = onWindowEvent;
window.onpopstate = onWindowEvent;
````

If you don't already have something like that in place, I'd suggest adding it and see if that works for you.

**Comment by markjerz** [comment]
Thanks, sadly that doesn't do it. I'm seeing requests to "https://mail.google.com/mail/u/0" with the following params:

ui:2
ik:e856gfgh3c
rid:a51d..
at:AF6bupOfghjdtPnaqgm2KaCm3Pp5bgJEnIw
view:tl
start:0
num:70
avw:1565
ntlv:100
auto:1
ver:3ib5BRz78no.en_GB.
am:!L7dmO1m_QuapjnbhfsdfgdfJDx6eebvg1Hq9dVLnAOAS8Nnk71Wfj0KBaJv2WinIopGE9ZMYru-Gc
ari:120
sstart:0,0
iosc:^u|
ioss:50,50
_reqid:4535634
pcd:1
mb:0
rt:j
search:mbox

Looking at the gmail.js code that doesn't appear to match any of the known events? I would have thought it was like a poll?? The response appears to contain just about everything you'd want to know about the state of the inbox (at a glance I can see folders/emails.)

Note: I've changed a few of the values above (the ones that look like random strings) just in case they're sensitive.

**Comment by josteink** [comment]
Then I honestly have no idea. If you figure it out, please submit a patch with the appropriate glue.

Good luck :)

**Comment by markjerz** [comment]
Yes, will do... is there anywhere (other than the code) that explains what all the various url parameters mean?

**Comment by josteink** [comment]
I think @KartikTalwar will have to answer that one :)

**Comment by josteink** [comment]
For now this is not a priority, and unless we receive a PR for this feature, we're not going to implement it.

Considering that, I'll close this issue. If you still have things you need resolved, please re-open.
