### ISSUE TITLE
Is it possible to trigger a draft save that would save the draft to gmail

### ISSUE THREAD

**Issue by kwbock** [KartikTalwar/gmail.js#356]
I'm wondering if it is possible to manually trigger gmail to save the draft. there are some plugins that modify the body of the email, in a compose view, but however they do it does not trigger the draft to save.

**Comment by josteink** [comment]
I took a brief look at this, and the answer "yes, but I'd rather not".

Basically it's easy for us to intercept calls made by Gmail itself to save a draft, but this happens somewhere quite inaccessible in the obfuscated Gmail Javascript codebase.

That means we have the following semi-realistic options:

* Try to find the exact function causing the saving of a draft and invoking that. (How do we know it wont change?)
* Fake the XML HTTP requeset and trigger out own. (Can we rely on the server-side API to be stable?)
* Determine the event/timer used by Gmail to detect change and invoke an upload and trigger that. This seems to me to be the least intrusive and most reliable way to get it done.

I have no plans to do this myself, but if anyone sends in a patch which works, I'm more than happy to merge it.

You can get the editable region of of a compose-window using the following code:

````javascript
var composes = gmail.dom.composes();
var compose = composes[0];
var editRegion = compose.dom("body");
````

Although I was not successful triggering a change-detection (when updating body-text) nor an draft upload based on this, it might help get you started.

Good luck :)

**Comment by josteink** [comment]
**Update:**

I've dabbled with the following code and it seems to work:

````javascript
function updateAndSaveDraft(compose_ref, html) {
    compose_ref.body(html);
    var element = compose_ref.dom("body")[0];
    var e = new KeyboardEvent("keydown", {bubbles : true, cancelable : true, key : "Q", char : "Q", shiftKey : true});
    element.dispatchEvent(e);
}
````

From what I can see that reliably:

* Update the body contents
* Invalidates Gmail's built in "has this changed?" state.
* Causes saving to drafts folder

You can fool around with it, and if you find it works reliably, you can prepare a patch to add it to the core library.

Sounds like a plan?

**Comment by kwbock** [comment]
@josteink you're a legend

**Comment by josteink** [comment]
Since I haven't received any updates on this, I'll assume the case has been settled by now.

Feel free to open if you still have anything you feel need getting resolved.
