### ISSUE TITLE
XMLHttpRequest override conflicts with InboxSDK

### ISSUE THREAD

**Issue by patrickriordan** [KartikTalwar/gmail.js#358]
I'm using an old version of gmailjs which attaches the xhr watcher the same way as the newest src and the xhr watchers do not watch anymore when an extension using the newest InboxSDK is in gmail as well.

AnyPerk extension that fails xhr_watch:
https://chrome.google.com/webstore/detail/anyperk-extension/hibhcpjgdocamgallhmphmmjeahifgof?hl=en-US

EDIT: This is wrong, not sure why it's failing->
It has to do with monkey patching on js_frame versus some other way of monkey patching that InboxSDK uses which seems to override ours instead of monkey patching it.

**Comment by josteink** [comment]
Do you have a link to the InboxSDK or example usage of it? Right now I'm lacking a bit context.

**Comment by patrickriordan** [comment]
Testing it some more it might not be InboxSDK itself. But the anyperk extension uses inboxSDK (gmail extension framework https://www.inboxsdk.com/) and it's not triggering the xhr watcher for my app. Not sure if it will also break the newest version of gmailjs.

here's the link to the extension. If the xhr trigger still works on send when this is installed after reloading gmail then it's my app specific.

https://chrome.google.com/webstore/detail/anyperk-extension/hibhcpjgdocamgallhmphmmjeahifgof?hl=en-US

**Comment by patrickriordan** [comment]
I think it's actually just any perk or a different library. Uses some js file called gmail_main.js
