### ISSUE TITLE
GLOBALS is not defined

### ISSUE THREAD

**Issue by SiddharthMantri** [KartikTalwar/gmail.js#36]
api.tracker.globals   = GLOBALS;

Uncaught ReferenceError: GLOBALS is not defined. What should I be doing to fix this?

**Comment by richygit** [comment]
Using the example from  @KartikTalwar, I kept getting:

Uncaught ReferenceError: Gmail is not defined

I had to add the following into my manifest:

"permissions": ["activeTab"]

And that seemed to fix it.

**Comment by chiragsatapara** [comment]
Hello KartikTalwar,

it always display error when call var gmail = new GMAIL() from other js files. when i call it from the main.js file then it is working , but it is not working for my file. 

I put a same code which is in main.js file , but doesn't work, it display a error like GLOBALS is not defined.

Note: I am using a angularjs

**Comment by chiragsatapara** [comment]
Hello @KartikTalwar 

It is necessary to inject all the js file in to the load.js which you describe above ,  i can not use without that ?
becuase in my extension there is lots of js files is included.

**Comment by mmccallum** [comment]
Not sure if I am thick or what, but from KartikTalwar's example above, load.js the line:

port.postMessage({ type: "save_email_id", id: event.data.message_id});

What is port?

--Uncaught ReferenceError: port is not defined

**Comment by KartikTalwar** [comment]
@mmccallum looks like I missed a line in the example.

```js
var port = chrome.runtime.connect();
```

https://developer.chrome.com/extensions/content_scripts#host-page-communication

**Comment by mmccallum** [comment]
Thanks.  Still not sure if I'm thick no not knowing what it should have been.  No one else noticed something missing for a year and a half?  :)
