### ISSUE TITLE
provider.observe.before('send_message') is very dangerous

### ISSUE THREAD

**Issue by JerryBels** [KartikTalwar/gmail.js#360]
Hello guys,

in my plugin I'm modifying some of the content before any mail is sent. For that I'm using

    provider.observe.before('send_message', function(url, body, data, xhr) { ... }

The problem is, if there is a javascript error here (like an undefined variable used like an object, for example...) the mail is simply never sent ! Gmail keeps displaying "sending" but never goes past that.

Is there a safer way to update a mail body that can't make Gmail fail a send ?

Thanks,
JB

**Comment by josteink** [comment]
Check out api.dom.composes() and the related body() function. 

This is done outside the actual sending process so probably safer.

**Comment by JerryBels** [comment]
Hey, thanks for helping :)

I guess, yes, but how to know when to change it ? I mean it needs to be changed just before sending so the user can't do anything more after that... And I guess it won't be available after the "send" button has been clicked. Plus, there are a lot of ways to send a Gmail message (like ctrl + enter) and I'm not sure to know them all...

**Comment by josteink** [comment]
In that case the XHR hook will be your best bet. Try to use something to validate your JS like jshint, eslint or even Typescript. 

That will highlight a lot of these possible error conditions before you ever run the code.

**Comment by josteink** [comment]
This issue documents a aspect of the API but it's not realistically going to be addressed.

Closing.

**Comment by JerryBels** [comment]
Actually  Iwill add something that "could" be added to the docs eventually : WHENEVER using this event, be sure to throw a `try/catch` in it so even if your code fails the JS don't stop and the UX is not degraded by your plugin.
