### ISSUE TITLE
current_page() function get wrong result 

### ISSUE THREAD

**Issue by HangYang** [KartikTalwar/gmail.js#362]
Go to another page in some label like page 2 in sent label, the URL will be
https://mail.google.com/mail/u/0/#sent/p2

The[ first line in the function](https://github.com/KartikTalwar/gmail.js/blob/master/src/gmail.js#L1758) will get "sent/p2", and the function will return
"email", which should return "sent".

fix:
change the first line from 
`var hash = window.location.hash.split("#").pop().split("?").shift() || "inbox";`
to 
`var hash = window.location.hash.split("#").pop().split("?").shift().split("/").shift() || "inbox";`

**Comment by HangYang** [comment]
Did

**Comment by josteink** [comment]
Fixed in https://github.com/KartikTalwar/gmail.js/commit/a89afcb68b9477efd1dca2b8b83d22aae5ef7236.
