### ISSUE TITLE
api.dom.email().attachments() only works in Chrome

### ISSUE THREAD

**Issue by josteink** [KartikTalwar/gmail.js#364]
`api.dom.email().attachments()` is based on extracting info from the DOM, and Gmail only emits the information we need to work with in Chrome.

In other browsers, like Firefox, we don't get the required attributes and meta-data which we need to get useful information about the attachment. With the current implementation, this causes the parser to fail and return nothing.

We should do two things to address this:

* ensure parser does not fail *completely* in browsers not Chrome.
* provide a cross-browser compatible way to get this information in a more reliable way.

**Comment by michi88** [comment]
just a quick note here, I'm using the raw email source to parse attachment data. Might be an option if you encounter other troubles.

**Comment by josteink** [comment]
For now, just parsing the meta-data returned with the email in the XHR response seems sufficient for my needs, but thanks for the tip.

Feel free to take a look at the patch I've provided, to see if that can cover your needs to, or if you think it needs modifications.
