### ISSUE TITLE
is_converstation_view() returns wrong value after switching before reload

### ISSUE THREAD

**Issue by patrickriordan** [KartikTalwar/gmail.js#365]
Seems like the globals[17][4][1] doesn't update the conversation view flag until after reload

**Comment by josteink** [comment]
I'm not intimately comfortable in this part of the codebase, but from what I can see, `api.tracker.globals` (and `api.tracker.globals[17]` too) doesn't really ever get updated except on reload.

I've tried just fiddling in the browser (without gmail.js) loaded, and from what I can tell, this flag is only updated by Gmail itself on reload. And there's nothing we can do about that.

Given how changing this preference is something people do once and never again, I'm fine with this short-coming. I don't think this is going to be a massive problem.

**Comment by josteink** [comment]
What I did find while looking into this, was this odd one out: https://github.com/KartikTalwar/gmail.js/blob/master/src/gmail.js#L313

Everywhere in the codebase we refer to our instance-variable `api.tracker.globals`, but here we access `GLOBALS` directly. To me that looks like a bug worth fixing. Anyone have any opinions on this matter?

cc: @keven425 @KartikTalwar

**Comment by patrickriordan** [comment]
@josteink Makes sense.

Btw seems like the GLOBALS direct access will cause NPE in popup window.

**Comment by KartikTalwar** [comment]
Makes sense to me too. Don't believe there's any particular reason - we can use `api.tracker.globals` instead

**Comment by josteink** [comment]
Thanks for the feedback. I've fixed the potential NPE in https://github.com/KartikTalwar/gmail.js/commit/8f45519f3639f812b3e8503b3f0a6cc897bd3f49.

In the meantime, I think this issue is not something which is worthwhile trying to find a work-around for. I vote close, unless ofcourse @patrickriordan has some really good arguments for why we should keep it open.

Patrick: We are all ears :)

**Comment by patrickriordan** [comment]
Looks like get.displayed_email_data is also affected by conversation view not updating, it probably won't give the right data back after updating conversation before reloading. Best argument i got haha.

I'm fine with closing it though. Low priority for me as well.

**Comment by josteink** [comment]
Great. Closing this one then.
