### ISSUE TITLE
issue with check.is_conversation_view

### ISSUE THREAD

**Issue by EliseoAzpeitia** [KartikTalwar/gmail.js#374]
1) Go to setting
2) Change mode on/off
3) Save changes 
4) Execute is_conversation_view
and this we return the old value. Is necessary reload page for that correct result

**Comment by josteink** [comment]
This is a duplicate of this known issue: https://github.com/KartikTalwar/gmail.js/issues/365

It's rated to have a low importance and has no known fix, so it won't be investigated further by the core team. 

Closing for now. Please comment further on the original issue. 

If you find a fix, or feel it should be rated higher, feel free to argue your case.  As always, the best argument is a PR :)
