### ISSUE TITLE
issue when apply multiple label

### ISSUE THREAD

**Issue by EliseoAzpeitia** [KartikTalwar/gmail.js#375]
I have an observer to "label". When apply multiple labels to a email in the observer method only received the last label applied

**Comment by josteink** [comment]
I've done some basic testing, and I can confirm this bug.

The bad news: From the way we intercept Gmail's XHR it seems this is the absolutely best we can extract of information.

The good: If you just need the current set of labels, the following seems to work for me as a workaround:

````javascript
gmail.observe.on("label", (emailId) => {
    gmail.get.email_data_async(emailId, (thread) => {a
        console.log(thread.threads[emailId].labels);
    });
});
````

If you just need the diff however, I'm honestly not sure if we can provide a solution.

Let me know if this works out for you.

**Comment by josteink** [comment]
Due to inactivity I'll assume that the workaround is sufficient, and closing it for now.

Please re-open if you still need something resolved.
