### ISSUE TITLE
`get.user_email()` not working?

### ISSUE THREAD

**Issue by apopiak** [KartikTalwar/gmail.js#376]
When I call `gmail.get.user_email()` in my code it returns undefined. I got curious and hat a look at `gmail.tracker.globals` and it seems to be empty. Did I not initialize sth or is there a bug in gmailjs?

Do I have to do jquery selector magic to get the image from the page?

EDIT:
So if I'm right (and not missing something) it should be super simple to reproduce with a call to initialize `gmail.js` and then a call to  `gmail.get.user_email()` upon interface load.

**Comment by josteink** [comment]
This exact piece of code is already in place in [gmailjs-node-boilerplate](https://github.com/josteink/gmailjs-node-boilerplate/). The code works perfectly fine there. Can you try that and see if you can reproduce?

Also: Are you sure you are loading gmail.js correctly? Remember it needs to be injected into the DOM of the actual page, and cannot be run inside your content-script.

**Comment by apopiak** [comment]
I can't believe I overlooked having to inject gmail.js into the page -.-
I was instantiating it in a content script...
Thanks for the help!
