### ISSUE TITLE
Very strange issue with gmail.observe.after('send_message')

### ISSUE THREAD

**Issue by JerryBels** [KartikTalwar/gmail.js#378]
Hello !

I'm using the 

    gmail.observe.after('send_message', function (url, body, data, xhr) { 
        console.log(JSON.stringify(xhr));
        // Some code
     } );

event in order to get the email id, like I explained in the end of [this topic](https://github.com/KartikTalwar/gmail.js/issues/179).

There is a VERY strange behavior I'm not able to debug successfully. Sometimes, apparently randomly when I forward or answer to a mail containing an image signature, the returned xhr is much shorter than usual. And it doesn't contains the data I need for the email ID... 

All the beginning of the xhr is the same, it's just shorter. And I don't get it. How come the answer from Google's server is not the same just because something changes in the mail body ?!

If someone has any idea on how to debug that or why is it happening, I will gladly take it.

Thanks,
JB

**Comment by josteink** [comment]
If what you need to do is just get the email-id, what I've used to (seemingly reliably) get the ID of the sent email is one of the following two things:

* from an "inline" reply or forward compose window, simply get the latest email-data for the thread and pick out the latest email ID after email is sent.
* observe for the "email sent" toast presented on top of the screen. It will contain a link with the final email ID in it.

None of this is entirely clean, but I can't see how it's worse than relying on the XHR line-format directly in "application-level" code :)

**Comment by JerryBels** [comment]
@josteink thanks I will try to use that, will update the question with a solution when I find one !

**Comment by JerryBels** [comment]
@josteink how do you reliably observe for the email sent toast ? I tried to look for an event but the only one I find is `sm` which is mapped to `send_message` and occurs a condition race (will it be in the dom before or after the `gmail.observe.after('send_message'` happens).

**Comment by josteink** [comment]
I probed the GUI after the appropriate CSS classes :)

**Comment by JerryBels** [comment]
Worked (kinda), thanks
