### ISSUE TITLE
We should review our jQuery-dependency

### ISSUE THREAD

**Issue by josteink** [KartikTalwar/gmail.js#379]
Currently we say we depend on jQuery 1.10. This is also declared in our [package.json](https://github.com/KartikTalwar/gmail.js/blob/master/package.json#L25-L28)-file, meaning that is what a `npm install gmail-js` will pull in.

But this version is *ancient*. It's from [November 15th, 2013](https://jquery.org/history/) and [supports MSIE6](https://blog.jquery.com/2014/04/02/browser-support-in-jquery-1-12-and-beyond/) for crying out loud!

Are there any technical reasons why we should discourage using a modern version of jQuery with this library? The only browsers we need to support are up to date Firefox, Chrome and MS EDGE. All of which are all supported by [latest jQuery](https://jquery.com/browser-support/).

As far as I can see, upgrading shouldn't represent any obvious issues, but I'd like to double-check before doing any "radical" changes with regard to core dependencies :)

Anyone for? Anyone against?

**Comment by KartikTalwar** [comment]
No objections. Since selectors and ajax are the only thing we rely on, I don't think there should/would be any problems with using the latest jQuery

**Comment by josteink** [comment]
The only thing I could think of, if I were to try to think *real hard* is that we use jQuery for AJAX requests. In *theory*, there could be some change in behaviour which may or may not work out well for us.

I think if we test that a few basic operations (`api.get.email_data()` etc) works out, it should be fairly risk free.

I'll try to get this batched in and released together with the CORS fix before pushing a new version to npm.

**Comment by josteink** [comment]
Doing some basic testing, I get this:

![image](https://cloud.githubusercontent.com/assets/411338/23316404/8c94d0c4-faca-11e6-8f7d-18e1c2c0ba51.png)

Basically it works, but something new inside jQuery decides to try to interpret everything as JSON, no matter what. Failing at that, it makes ugly log-statements in the console.

![image](https://cloud.githubusercontent.com/assets/411338/23316446/c0b0c764-faca-11e6-93d8-6067ede630ba.png)

If I were to take a guess, it would probably cause less panic among library-users, if we figured how to avoid triggering those errors before making the change. I'll defer it to later, I guess.

**Comment by josteink** [comment]
So almost one year passed, and now GitHub is flagging the version of jQuery we ship as insecure:

![image](https://user-images.githubusercontent.com/411338/35260948-458ac95a-000e-11e8-9f96-b15a3f85d3fc.png)

As far as I can tell, jQuery is still doing that parsing where it shouldn't, so that leaves us the following options:

* upgrade to a non-vulnerable version of jQuery and live with the log-noise
* issue a bug for jQuery to change this behaviour
* rewrite our code to not depend on jQuery for XHR.

Any opinions?

**Comment by josteink** [comment]
The jQuery console errors should be fixed by #436, so that means we should now be free to upgrade to a version not deemed "insecure".
