### ISSUE TITLE
Can't get the Inline images

### ISSUE THREAD

**Issue by bb-swapnil** [KartikTalwar/gmail.js#380]
I am developing a gmail gadget which will generate a pdf of any conversation and attach to my site. To do so I am converting the html to string and with help of python's wkhtml2pdf I am converting the string to pdf.
Every thing works fine when it deals with text conversations, but if there is an inline image in the conversation, while generating pdf I only get redirect url instead of a url with image extension. Is there a way to to get the image url with extension.

**Comment by josteink** [comment]
The images in the email is part of your email and secured by the same authentication cookies as any other part of your Gmail-experience.

That means that when you extract the HTML via Gmailjs and feed it to another application *outside the authenticated browser context*, that application won't be able to access anything referenced via hyperlinks. This can't be fixed or changed, by us and I see no point trying to work around it.

What I supposed may work (although I have not tried it) is to do the following:

* Use the `api.dom.email`-classes to extract the HTML. Within this HTML, locate `<img>`-tags (which in the browser are actual, rendered images) and use "some JS magic" to convert these into [Data URI-encoded image-tags](https://css-tricks.com/data-uris/) instead. (I'm sure there are libraries or jQuery-plugins to do this for you somewhere.)

Then when you export *that* HTML the images should be accessible from anywhere, and should render fine in your PDF.

**Comment by bb-swapnil** [comment]
Will try today or tomorrow and get back again. Thanks

**Comment by bb-swapnil** [comment]
The thing is the following thing:-

`<img src="?ui=2&amp;ik=a0e839e943&amp;view=fimg&amp;th=159dfd9f60af3ad3&amp;attid=0.0.1&amp;disp=emb&amp;realattid=ii_159dfcf2ddfcd784&amp;attbid=ANGjdJ_-5-IaTg_3EaA16Ps5_m4jbjygi25cQDsqWNfb7_loHrQMx7EUdgkMjNjzNT61oNPxu5NSDcLgdrj_LqKPfktWCsP2_XnQX4XXpu8exUidHqYW0JrP9l0lq0k&amp;sz=w908-h130&amp;ats=1488975110868&amp;rm=159dfd9f60af3ad3&amp;zw&amp;atsh=1" alt="Inline image 1" width="454" height="65">`

redirects to :- `https://gm1.ggpht.com/nhbCCYxBMBXpdNvQ3bQAf-sOQP0NfTpwO4wW8j_jby1n44QH8IpUoxnazQIxpzmRRSLggMkDM2hi3HCU_klyovrzYo6ntM0lyngN-UD25pWgNssjV6v7hPAsREaS-cJbKHBKbfjYYeTpoI7WJbMfJCd5HDfLpdWA-aiLve-bh19P_wReDTInvqZB5VjVKB1qv-WrBj2-E1EirrpI18WkE4ZqLkOkqs3QliVBe6tu7Y0XFAzLuUx1RFUyg9V2hykTtcltkyk0xSFzCHqpDPP1dx_E5nv1HivKrfiK0Px_wYGYgL9WByh4y8HeM8oMEQHGtJQ7gi4u9eDqo-37mE8m8KX0bVvIW3KfDzR7D0xRIlwu5VkBwWODC6PF1bXBu_5QU31Vonb6egm5jJz14SxeTx5gLoxc_0pX9GiEGXLh1b399ODtY0vsZpFyr14yky8Aoddp2qYh14m9CB_UYHzRjtQTN_qlhQVojTagammL513botCsWzskpoUnIazEWjQ8uwMkn5NhPBC2ZawrbzLC_dBdfql49c7gNCj1Pxz9nVI14WLwFUBgHo6YnwidKlhmpv8TMQ7CZT_-_DTd_YLEfHO6ImryYsY8iZoZo-n0aRotVOiEPtJqJdGDClKs0Df6wY4-gKA_WAWqVkNRJ5iYOhETpaY5ySM4gZo6G4UIXn8k54Kr8uKnTfbqO0zqH3B0cS0f3CnYotK5z2ZUKWBK=w908-h130-l75-ft`

which gives 403 when I try to do the same thing via js and also with python.

**Comment by josteink** [comment]
Yes. I understand.

Like I said: You'll need to, *in the browser-context where you have Gmail.js running*, transform that image from one referencing an external URL, to one using Data URI-encoded image-data instead.

If you do that, any external application trying to process the HTML should be fine.

**Comment by bb-swapnil** [comment]
@josteink  Thanks mate !!.. I Fixed it "like you said" :+1:  I am closing the issue now.

**Comment by josteink** [comment]
Glad to see you managed to sort things out! Have a nice weekend :)

**Comment by bb-swapnil** [comment]
Will grab a cold one this weekend. Cheers..!
