### ISSUE TITLE
False positive on delegated inbox detection

### ISSUE THREAD

**Issue by remidenele** [KartikTalwar/gmail.js#381]
Hi, I have detected a problem with the [`gmail.get.delegated_to_email()`](https://github.com/KartikTalwar/gmail.js#gmailgetdelegated_to_email) function which is defined as follow:

> Returns the email address of the user the account is currently delegated to (if the inbox is used by the owner, this function returns null)

It is working as described in the doc on one of my G Suite domain where delegation is enabled, but not on an other one where email delegation is disabled at a domain level:

![mail-delegation-management](https://cloud.githubusercontent.com/assets/8693949/23706739/b4b8d494-040f-11e7-925a-a1887bb98d76.png)

On the 2nd domain (mail delegation off), [`gmail.get.delegated_to_email()`](https://github.com/KartikTalwar/gmail.js/blob/master/src/gmail.js#L113) always returns the mailbox owner email address instead of `null`.
It appears that [`api.helper.get.is_delegated_inbox`](https://github.com/KartikTalwar/gmail.js/blob/master/src/gmail.js#L1683) is always returning true in that case.

**Comment by josteink** [comment]
Just to be sure... Have you tried completely logging out and reloading your browser, Gmail (with your extension) and all those things after changing the domain settings? Sometimes, some of these things can be sticky.

If reloading fixes it, I'm not going to consider this a big deal.

If it's a persistent issue however, it's definitely something where we should take a look into possible means of action.

**Comment by remidenele** [comment]
In fact, I have not changed domain settings: I am using 2 different domains with different settings:
- _domain**1**.com_ where Mail Delegation setting is **enabled** at the domain level
- _domain**2**.com_ where Mail Delegation setting is **disabled** at the domain level

I am using 2 distinct Chrome profiles. On each profile, only one G Suite account is logged in in Gmail (no multi login used in Gmail), and none of the mailboxes are shared (no delegate):

- for _user-test@domain**1**.com_, `gmail.get.delegated_to_email()` returns `null` (behaves as described)
- for _user-test@domain**2**.com_, `gmail.get.delegated_to_email()` returns  `user-test@domain2.com`

For now, my workaround is to add a check on the value returned by `gmail.get.delegated_to_email()` to ensure it is not equals to the current logged user.

If you want, I can change Mail Delegation settings on one of the 2 domains to ensure that it indeed controls the value of `GLOBALS[17][5][0]` used by [api.helper.get.is_delegated_inbox](https://github.com/KartikTalwar/gmail.js/blob/master/src/gmail.js#L1683) 
(I have not done it yet as the change can take up to 1h to propagate as described in the G Suite admin panel).

**Comment by josteink** [comment]
Thanks for detailed response and for clearing that up!

> For now, my workaround is to add a check on the value returned by gmail.get.delegated_to_email() to ensure it is not equals to the current logged user.

That all sound reasonable. That could be a workaround which we embed into our API.

> If you want, I can change Mail Delegation settings on one of the 2 domains to ensure that it indeed controls the value of GLOBALS[17][5][0] used by api.helper.get.is_delegated_inbox

If you could indeed verify this, that would be great (so that we know we are still looking in the right place).

Whatever we learn from that can probably help us decide if your current workaround is a good solution, or if there are other more fundamental issues which needs to be addressed.

**Comment by remidenele** [comment]
Thanks for the follow up @josteink !

Tests done:
- disable Email Delegation on _domain**1**.com_ (from domain admin console)
➞ the same problem as on _domain**2**.com_ appears (`GLOBALS[17][5][0] === 'fwd'`)
- re-enable Email Delegation on _domain**1**.com_
➞ the situation is back to normal (`GLOBALS[17][5][0] === 'dlg'`)

This confirms that the Mail Delegation settings from the domain admin console affects the [`gmail.get.delegated_to_email()`](https://github.com/KartikTalwar/gmail.js/blob/master/src/gmail.js#L113)

**Comment by josteink** [comment]
Sorry about the slow response. To me, your workaround sounds like it does what it should and like something we should implement in the core library.

Would you please be so kind and submit a PR for this? I promise I won't keep you waiting another month this time around :)

**Comment by josteink** [comment]
@remidenele: Still around? I'd be happy to merge this if you submit a PR.

**Comment by remidenele** [comment]
@josteink My bad, I totally forgot it!

**Comment by remidenele** [comment]
As discussed, we will deal with this problem in #447
