### ISSUE TITLE
How to print info from Gmail.js to popup.html ?

### ISSUE THREAD

**Issue by SickyBuffalo** [KartikTalwar/gmail.js#382]
Hi, using gmail-chrome-extension-boilerplate i want to display some info from gmail to popop.html! So I succeeded to pass data from content script to popup.js refer from [http://stackoverflow.com/questions/20019958/chrome-extension-how-to-send-data-from-content-script-to-popup-html](url) ! How can i pass data from gmail.js (main.js ) to popup.js and then diplay it on popup.html? Thank you!

**Comment by josteink** [comment]
This sounds like a generic WebExtension issue and not really specific to Gmail.js.

The good news: I'll be nice and try to provide some leads. Mind you, you'll have to follow those leads yourself and piece it all together. I'm not going to provide example code.

The bad news... This is going to be lots more work than you had hoped for.

With that said:

The only way to cross past web and extension security-boundaries are through *messaging*. You can pass along messages, and process them if you've registered event-handlers/message-listeners on "the other side" of the boundary.

Examples of such boundaries are messaging between the "actual" web-page and the associated content-script page. You'll need to use [window.postMessage](https://developer.mozilla.org/en-US/docs/Web/API/Window/postMessage) for this.

Another boundary is between extension pages themselves. Use [chrome.runtime.sendMessage](https://developer.chrome.com/extensions/messaging) and associated APIs for that.

So with that said, you might have setup a event and message path which goes like this:

* Someone opens you popup page.
* Your popup page sends a message to a background page (using chrome.runtime APIs).
* The background page (which has listeners registered for these!) tries to locate a gmail-tab using the tabs API.
* If such a tab is found, it will message the content-script in that tab using the same APIs.
* The content-script in your gmail-tab must then re-post this message into the page-context using window.postMessage.
* In your injected gmail script you must listen for this message.
* The message event triggers your code, use gmailjs to extract the data you want.
* After extracting this data, you post the data back to the gmail.com content-script using window-postMessage.
* In the gmail.com content-script (where you've too registered a listener for these messages!) you verify that this message is indeed the one you expect, and if so, re-post this to the next page using chrome.runtime.sendMessage.
* In the next page (where you've registered event-listeners using the chrome.runtime API!) you intercept this message, and pass it along to the next one in the chain, or process it once you're finally where you want to be.
* Etc.

I'm not sure if you can post messages directly from the content-script to the popup-page, or if this too needs to go by the background page.

No really. That's how you'll have to do it. Thank the security gurus.

Debugging these messaging-scenarios can be seriously frustrating, so try to be patient with yourself :P 

Good luck!

**Comment by SickyBuffalo** [comment]
Thanks, appreciate that !
