### ISSUE TITLE
Am I able to send an email?

### ISSUE THREAD

**Issue by ConnorVO** [KartikTalwar/gmail.js#385]
Hello,

Is it possible for the user to send the email by clicking a button I include, not the send button?

Thank you,
Connor V.

**Comment by josteink** [comment]
The `compose` object contrains a function called `send()`.

If you in your event-handler for the email where you've registered your own button have kept a reference to this `compose` object, you can call `send()` on that.

**Comment by ConnorVO** [comment]
Where do you find the documentation for this?

**Comment by josteink** [comment]
I'm the one who implemented that functionality, so I didn't need any :)

Seriously though... Normally I'd refer to the documentation (the big README), but I can see it's not mentioned there. We may want to fix that.

As for more constructive suggestions (in general); If you use TypeScript, you'll get all this automatically via code-completion (as gmail.js provides complete TypeScript-annotations).

For people who don't use TypeScript, sometimes looking through the relevant part of the source-code can be enlightening when the documentation is inadequate.

**Comment by josteink** [comment]
Anyway: I consider question answered, and I'm closing this issue.
