### ISSUE TITLE
Xpath for gmail body content div

### ISSUE THREAD

**Issue by ajays1991** [KartikTalwar/gmail.js#386]
Hi,

This is not an issue. I was wondering if there is way or get Xpath for the gmail content div.

You have prepared a very comprehensive documentation for the API's. Since you provide html content of the email content body. I was thinking about also getting the XPATH for that div. I was looking at the source code to add this functionality but i thought discussing with you first will really help me move in the right direction.

Thanks
Ajay

**Comment by josteink** [comment]
> This is not an issue. I was wondering if there is way or get Xpath for the gmail content div.

I'm sure there is, but from `gmail.js` alone.

> Since you provide html content of the email content body. I was thinking about also getting the XPATH for that div. 

I think this is a pretty generic kind of problem, and I don't see any very pressing use-cases for reverse-resolving the Xpath query for a given DOM node within `gmail.js`.

That said, we do have access to the exact HTML element which contains the email, and from this element you should be able to get an Xpath-query using any kind of generic JS-approach you see fit.

One example of such a generic solution to your problem can be found here, in the form of a jQuery-plugin: https://gist.github.com/MartijnR/5118908

Or here for a smaller solition which doesn't involve jQuery at all: https://gist.github.com/iimos/e9e96f036a3c174d0bf4

All you need is the body element, which you can get this way:

````javascript
var email_id = gmail.get.email_id();
var email_dom = new gmail.dom.email(email_id);
var body_node = email_dom.dom("body");
// get your xpath here.
````
 
Hope that helps.

**Comment by ajays1991** [comment]
thanks
