### ISSUE TITLE
gmail.get.displayed_email_data() 404 error

### ISSUE THREAD

**Issue by metractive** [KartikTalwar/gmail.js#390]
Good afternoon.

I am having issues with the displayed_email_data method. It gives me 404 error when I try to access it. There is anything I need to do? I am trying to get the people involved from that opened e-mail.

Here's a screenshot of my issue:
https://snag.gy/iIFWPT.jpg

And I try to get this info on e-mail page:
https://mail.google.com/mail/u/0/#inbox/15b498df41719695

My code is:

```php
var gmail = new Gmail();
var currentPage = gmail.get.current_page();

if (currentPage == 'email') {
    var t = gmail.get.displayed_email_data();
    console.log(t);
}
```

**Comment by josteink** [comment]
The 404 makes me suspicous that you've not setup gmail.js correctly.

So just to make sure:

* Are you loading gmail.js in your content-script?
* Or have you done (as instructed in the documentation) injected it into the regular Gmail-page?

If you don't know what I mean by the second term there, feel free to take a look at the boilerplate projects mentioned in the README.

**Comment by metractive** [comment]
You are right @josteink. Thank you very much.
I was injecting it through the content_scripts in manifest.json. It is now working.

**Comment by josteink** [comment]
Glad you worked it out

**Comment by ArpitSohar** [comment]
Hi I am unable to use gmail reference in my message listeners of chrome. I've to use gmail info in my popup using listeners. Please help ASAP.

**Comment by josteink** [comment]
I don't understand what you mean.

Can you post some example code highlighting what your problem is?

**Comment by ArpitSohar** [comment]
I've to make listener for a message through which I have to send data from gmail APIs. Sharing the code 
My Content-script:
`
var j = document.createElement('script');
j.src = chrome.extension.getURL("lib/jquery/jquery-3.3.1.min.js");
(document.head || document.documentElement).appendChild(j);

var g = document.createElement('script');
g.src = chrome.extension.getURL("lib/gmail-lib/gmail.js");
(document.head || document.documentElement).appendChild(g);

var s = document.createElement('script');
s.src = chrome.extension.getURL('js/contentScript/main.js');
(document.head || document.documentElement).appendChild(s);

chrome.runtime.onMessage.addListener(function (msg, sender, response) {
   
    console.log(gmail)
    if ((msg.from === 'popup') && (msg.subject === 'DOMInfo')) {
   
        var is_inside_email = gmail.check.is_inside_email()
        var domInfo = {
            isInsideEmail: is_inside_email
        };


       
        response(domInfo);
    }

    

})`

Manifest.json:

`{
  "manifest_version": 2,
  "name": "Reap",
  "version": "1.0",
  "description": "Application to recognise newer(s) in To The New",
  "icons": {
    "48": "/icons/reap-logo.png",
    "96": "/icons/reap-logo.png"
  },
  "permissions": [
    "storage",
    "notifications",
    "tabs"
  ],
  "content_scripts": [
    {
      "matches": [
        "*://mail.google.com/*"
      ],
      "js": [
        "js/contentScript/reap.js"
      ]
    }
  ],
  "browser_action": {
    "default_icon": "/icons/reap-logo.png",
    "default_title": "Recognize a Newer",
    "default_popup": "/html/popup.html"
  },
  "web_accessible_resources": [
    "lib/jquery/jquery-3.3.1.min.js",
    "lib/gmail-lib/gmail.js",
    "js/contentScript/main.js"

  ]
}
`


Main.js

`
var gmail;


function refresh(f) {
    if( (/in/.test(document.readyState)) || (typeof Gmail === undefined) ) {
        setTimeout('refresh(' + f + ')', 10);
    } else {
        f();
    }
}


var main = function(){
    // NOTE: Always use the latest version of gmail.js from
    // https://github.com/KartikTalwar/gmail.js
    gmail = new Gmail();
    console.log('Hello,', gmail.get.user_email())
    // addListeners()

}


refresh(main);



`


I am newbie in JS and chrome extension and done this by referring your boilerplate code :
(https://github.com/KartikTalwar/gmail-chrome-extension-boilerplate)

**Comment by ArpitSohar** [comment]
Sharing my code:
manifest.json:
```
{
  "manifest_version": 2,
  "name": "Reap",
  "version": "1.0",
  "description": "Application to recognise newer(s) in To The New",
  "icons": {
    "48": "/icons/reap-logo.png",
    "96": "/icons/reap-logo.png"
  },
  "permissions": [
    "storage",
    "notifications",
    "tabs"
  ],
  "content_scripts": [
    {
      "matches": [
        "*://mail.google.com/*"
      ],
      "js": [
        "js/contentScript/reap.js"
      ]
    }
  ],
  "browser_action": {
    "default_icon": "/icons/reap-logo.png",
    "default_title": "Recognize a Newer",
    "default_popup": "/html/popup.html"
  },
  "web_accessible_resources": [
    "lib/jquery/jquery-3.3.1.min.js",
    "lib/gmail-lib/gmail.js",
    "js/contentScript/main.js"

  ]
}
```

Reap.js -- Content Script

```
var j = document.createElement('script');
j.src = chrome.extension.getURL("lib/jquery/jquery-3.3.1.min.js");
(document.head || document.documentElement).appendChild(j);

var g = document.createElement('script');
g.src = chrome.extension.getURL("lib/gmail-lib/gmail.js");
(document.head || document.documentElement).appendChild(g);

var s = document.createElement('script');
s.src = chrome.extension.getURL('js/contentScript/main.js');
(document.head || document.documentElement).appendChild(s);

chrome.runtime.onMessage.addListener(function (msg, sender, response) {

    console.log(gmail)
    if ((msg.from === 'popup') && (msg.subject === 'DOMInfo')) {

        var is_inside_email = gmail.check.is_inside_email()
        var domInfo = {
            isInsideEmail: is_inside_email
        };



        response(domInfo);
    }



})

```

Main.js

```

var gmail;


function refresh(f) {
    if( (/in/.test(document.readyState)) || (typeof Gmail === undefined) ) {
        setTimeout('refresh(' + f + ')', 10);
    } else {
        f();
    }
}


var main = function(){
    // NOTE: Always use the latest version of gmail.js from
    // https://github.com/KartikTalwar/gmail.js
    gmail = new Gmail();
    console.log('Hello,', gmail.get.user_email())
    // addListeners()

}


refresh(main);


```


I am newbie in JS and chrome extension and done this by referring your boilerplate code :

**Comment by josteink** [comment]
You're (trying to) running gmail.js code (`gmail.check.is_inside_email()`) in the content script, not the injected script. That's not how gmail.js is designed to work, and may be the source of your error.

You can only use gmail.js in your main.js file.

Your whole approach also looks weird... Try to message out from the injected script ... to the content-script ... and messaging results back based on processing through gmailjs.

Why not just use gmail.js in the injected script and keep all your logic there?

**Comment by ArpitSohar** [comment]
Basically I need recipients data in popup that's why I was trying something. I've achieved it and sharing the flow. I request you to review it and suggest any better way if I'm doing it in a wrong way.
I am sending data from 
main.js -->content.js through a custom event and then
content.js ---> background.js through messages
and then storing it in chrome.storage
for popup I am asking from background.js for what data I needed.

**Comment by josteink** [comment]
Please re-read my response. I've already reviewed it and provided the advice you need to fix your solution.

Basically you need to do everything which involves gmailjs in Main.js. If you need any information from gmailjs in your popup you will need to extract that in Main.js and pass it along using messaging, like you've already implemented.

Using gmailjs in either content-scripts or background-scripts is guaranteed to fail.

**Comment by ArpitSohar** [comment]
Yes, I was just cross verifying. Thanks for your response. It was helpful. Also, I want to raise a concern that I am getting some warning in executing this code:
Code: 

```
gmail.observe.on("open_email",function () {
    var isInEmail = true;
    var recipients = [];
    var selectedEmail = gmail.get.selected_emails_data();
    var loggedInUser = gmail.get.user_email();
    var people_involved = selectedEmail[0].people_involved
    for (i=0; i < people_involved.length; i++) {
        recipients.push(people_involved[i][1])
    }
    console.log(recipients);
    var data = pushDataOfGmail({
        loggedInUser: loggedInUser,
        isInEmail: isInEmail,
        recipients: recipients
    });
    var event = new CustomEvent("PassToBackground", {detail: data});
    console.log("Observing event");
    window.dispatchEvent(event);
});
```


```
Warning:
Synchronous XMLHttpRequest on the main thread is deprecated because of its detrimental effects to the end user's experience. For more help, check https://xhr.spec.whatwg.org/.

Context
https://mail.google.com/mail/u/0/#inbox/FMfcgxvzMBqJbHdLbwMgsXDDMNqQFbrS
Stack Trace
lib/gmail-lib/gmail.js:1579 (win.XMLHttpRequest.open)

    api.tools.patch(win.XMLHttpRequest.prototype.open, (orig) => {
            win.XMLHttpRequest.prototype.open = function (method, url, async, user, password) {
                var out = orig.apply(this, arguments); //Warning is on this line.
                this.xhrParams = {
                    method: method.toString(),
                    url: url.toString()
                };

```

**Comment by josteink** [comment]
You're getting this error because you are using synchrenous GmailJS APIs which are using synchrenous XHR under the hood.

To address this, I have several questions and suggestions:

* Why are you using `api.get.selected_email_data()`? If all you want is the *current* email, `api.get.email_data()` will suffice.
* To avoid your warnings, replace use of synchronous methods which will cause synchronous XHR (like `api.get.email_data()`) with asynchronous methods (like `api.get.email_data_async()`).
* Better yet: If you know none of your existing users are using "old" gmail, use the new `api.new.get.email_data()` which doesn't rely on XHR at all. This returns results instantly if available, but only works on new Gmail. (Please note data-format returned is *significantly* different.

Hope this helps.
