### ISSUE TITLE
How do you define "document" properly 

### ISSUE THREAD

**Issue by geosh03** [KartikTalwar/gmail.js#391]
I am testing using the example provided:

            var jq = document.createElement('script');
            jq.src = "https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js";
            document.getElementsByTagName('body')[0].appendChild(jq);
            var gmail = Gmail();
            console.log(gmail.get.displayed_email_data());

However, I keep getting an error that "document" is not defined. 
"Unhandled rejection ReferenceError: document is not defined"
How do I properly define "document"?

**Comment by KartikTalwar** [comment]
@geosh03 how are you using this? document here is `window.document` with the window being gmail.com in your chrome extension

**Comment by geosh03** [comment]
I am driving the UI to login to my gmail account and click on a specific email. From that point, I would like to get the contents of that email body. Here is how my code looks:

var JSQA = require("../utility/jsqa.js");
var URL = require("../utility/url.js");
var main_page = require("../pageobj/main.json");
var gmail = require("../pageobj/gmail.json").login;
var Utility = require("../utility/utility.js");
var Promise = require("bluebird");
var $ = require("jquery");

module.exports = function(driver) {
    var self = {
        login: Promise.coroutine(function*(userInfo) {
            var qa = new JSQA(driver);
            var url = URL.buildURL("accounts.google.com/ServiceLogin?continue=https%3A%2F%2Fmail.google.com%2Fmail%2F&service=mail&sacu=1&rip=1#identifier");

            var jq = document.createElement('script');
            jq.src = "https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js";
            document.getElementsByTagName('body')[0].appendChild(jq);

            yield driver.get(url);
            yield qa.input(gmail.email, userInfo.username);
            yield qa.click(gmail.next);
            yield qa.input(gmail.password, userInfo.password);
            yield qa.click(gmail.sign_in);
            yield qa.click(gmail.welcome_email);

            var gmail = Gmail();
            console.log(gmail.get.displayed_email_data());

        })

      };
      return self;
  };

**Comment by geosh03** [comment]
Sorry that pasted weird. I'm probably not using this correctly, any feedback would certainly help.

**Comment by KartikTalwar** [comment]
Unfortunately the way you are using this library is not how it is intended to be used. Though it supports being importable in node, it is not a node library. This library lets you make chrome extensions on top of gmail and relies on what the browser shows on the screen at the time of interaction. 

To get started with a hello world, please see the sample chrome extension that comes with the library https://github.com/KartikTalwar/gmail-chrome-extension-boilerplate

**Comment by geosh03** [comment]
Thank you, I will look into that example and see if I can figure something out.

**Comment by KartikTalwar** [comment]
👍
