### ISSUE TITLE
Get id of draft from the event gmail.observe.on("save_draft") 

### ISSUE THREAD

**Issue by OriAmir** [KartikTalwar/gmail.js#394]
Hey ,I need to change the draft every time he is changed ,I mean to encrypt the draft until user send it... So I am looking for event that will fire every time gmail save the mail to the draft and then to change it every time...

I using:
 gmail.observe.on("save_draft", function(url, body, data, xhr) {
  console.log("url:", url, 'body', body, 'email_data', data, 'xhr', xhr);
})

So I get in the console many details include **composeid** and **draft**  but then when I try to update the draft by the id ( I try both of them ) via [Gmail API](https://developers.google.com/gmail/api/v1/reference/users/drafts/update) but it's always 404 not found . I success to find the real id of the draft finally in other way and it's totally different from the result I get in the event...

Is this is the right way to do or can I use something else?

Thank you very much !!

**Comment by josteink** [comment]
> So I am looking for event that will fire every time gmail save the mail to the draft

I'm sorry, but gmail.js has no such APIs. If you need this functionality, this library currently can't help you, and I don't think anyone is working on such support either.

The only thing we have which even comes closes, is via workarounds being able to indirectly and asynchronously trigger such an event.

If you manage to figure it out on your own though, and want to submit such functionality as patches for gmail.js, you're more than welcome to do so. We're a friendly bunch :)

**Comment by OriAmir** [comment]
Hi @josteink , thank you very much for your help!
So I understand from your answer that the event of : gmail.observe.on("save_draft", function(url, body, data, xhr)  is not happend really when the message is save as a draft? so how exactly it's work ? 
So by your idea how can I 'hide' the real draft and to change the real content? 

Thanks again.

**Comment by josteink** [comment]
You know what... Sometimes I may be wrong and I'm happy to admit it.

We *do* have a `save_draft`-event as you so correctly point out. Just to verify its behaviour I've stepped through the following simple test-case in a debugger:

````javascript
function mytest() { console.log("MY TEST!"); console.log(arguments); }
gmail.observe.on("save_draft", mytest);
````

My function does indeed trigger, and I can observe *when* it happens, and that it happens syncronously at the time of saving the draft. So far all is good.

In practice the `on`-observer is called directly *after* the XHR request has been sent: https://github.com/KartikTalwar/gmail.js/blob/886f3e7cf34cb88de010d8bd3153ef21315872d2/src/gmail.js#L1044-L1048

That means you won't be able to modify it or intercept it, but maybe you can extract the info you need from the parameters here.

Sorry about any confusion I may have caused with my initial reply.

**Comment by OriAmir** [comment]
@josteink Thanks , I try this event. My question is if this event happens already after google '
get' the information? it's means it's fire just after it's saved? and I try this event with 'before' but nothing happens..
So this is my only option , because the id I get from this event is surprisingly return me wrong id of the draft message..

Thank you very much again!!

**Comment by josteink** [comment]
This happens immediately after the information has been sent to Google (asynchronously).

That means that Google is in the process of receiving the information as your event-handler is executed.

**Comment by OriAmir** [comment]
**Thank you** @josteink  ! It's not possible to catch the event before he sent to google ? I just don't want that content send to google when someone write a message..

**Comment by josteink** [comment]
Seemingly not so. At least not without changing gmail.js.

If you need that, feel free to send in a patch for this functionality.

**Comment by OriAmir** [comment]
I don't idea how to do this and to take control on gmail events .. your job is great. I am stuck with this ): thanks.

**Comment by OriAmir** [comment]
@josteink I try to get into code , I need to create event of before send draft or just cancel the auto-save draft... So I try just abort the xhr when I see event of save_draft... it's really abort the event but then it's try again and again to save draft and always return 404.. Maybe you could give me some advice how could I change the code to my purpose?

Thank you very much again!

**Comment by josteink** [comment]
I honestly can't help much here. I've only worked with bits which are non-intrusive with regard to how Gmail normally works.

I haven't (and don't plan to) write code to sabotage core functionality, even if it is for a good purpose.

Even if you get it working now, you will always run the risk that Google makes some changes later which causes your hacks or workarounds to fail.

On this one, I'm afraid you are on your own.

**Comment by OriAmir** [comment]
@josteink Thanks!  I don't want to sabotage the core... I just want to make event 'before' like the other events ( like send message ) have...

**Comment by josteink** [comment]
If you can make it trigger a before-event... Sure have a go at it! And if you make that work, feel free to send a PR :)
