### ISSUE TITLE
Cancel auto save of draft programmatically

### ISSUE THREAD

**Issue by OriAmir** [KartikTalwar/gmail.js#395]
Is exist some option to cancel the auto save of the draft ? I don't see anything about this in the API and also not in the issues ... is it possible?

My case is that I need to hide from user the real compose message content , and if it's save the message every 2-3 seconds to drafts so I actually lost what I want to do..

Is anyone have any idea?
Thanks!

**Comment by josteink** [comment]
We can't stop this from happening, nor intercept the event. At best we can trigger it, although indirectly. 

You'll need to reverse engineer Gmails code yourself if you need to do this.

**Comment by arantes555** [comment]
Hello,

Looks like I managed to throw together a very simple script to prevent saving drafts, here it is
```javascript
decodeQueryString = (qs) => {
    const result = {}
    qs.split('&').forEach(part => {
        const parts = part.split('=')
        const key = decodeURIComponent(parts[0] || '')
        const val = decodeURIComponent(parts[1] || '')
        if (key) result[key] = val
    })
    return result
}

encodeQueryString = (obj) => Object.keys(obj).map(key => `${encodeURIComponent(key)}=${encodeURIComponent(obj[key])}`).join('&')

gmail.observe.before('save_draft', (url, body, data, xhr) => {
    body.body = ''
    
    const temp = decodeQueryString(xhr.xhrParams.body)
    temp.body = ''
    xhr.xhrParams.body = encodeQueryString(temp)
    
    xhr.xhrParams.body_params.body = ''
    console.log('Prevented draft content')
})
```
