### ISSUE TITLE
Can we have forward function

### ISSUE THREAD

**Issue by levis012** [KartikTalwar/gmail.js#401]
I have working with gmail.js and I need a function to forward email like this
`gmail.forward(emailId, 'to@email.com');`

Please help me.

Thanks

**Comment by josteink** [comment]
I myself have no need for such a function and won't be actively working on it.

That said, I'll be happy to accept a path for this if someone makes it and submits it as a PR.

**Comment by josteink** [comment]
No further work will be done on this issue by the core team. Closing.
