### ISSUE TITLE
Two or more extensions using Gmail JS

### ISSUE THREAD

**Issue by ebeltran1981** [KartikTalwar/gmail.js#402]
Hi guys,

I just found out that SugarCRM 6 extension uses this plugin, and is blocking my extension on the http events, example: `gmail.observe.on("load", function(){})`. Apparently on the version 7 they've fixed it...

Is there a way to workaround this? like a `noConflict()` method or something like that?

**Comment by ebeltran1981** [comment]
Just FYI, since gmail.js only has a definition file `gmail.d.ts`, you cannot use `import * as gmailjs from "gmail-js"`, so if you do `import "gmail-js"` it works but creates the conflict I was seeing. My final solution was to use `require` syntax instead. I did `const gmailjs = require("gmail-js")` that did the trick and forced my code to use my instance of gmail.js, and not the other plugin's instance.

hope this helps anyone.

**Comment by josteink** [comment]
> Is there a way to workaround this? like a noConflict() method or something like that?

Unfortunately not. You'll have to convince them to upgrade to a later version.

We still don't have a good (enough) story about how to handle conflicting versions between different extensions. And the only way to create a future-proof way seems to be to break gmail-js in existing extensions running "older" versions.

In lack of any good option, we've really decided to do nothing so far.

>  since gmail.js only has a definition file gmail.d.ts, you cannot use import * as gmailjs from "gmail-js", so if you do import "gmail-js" it works but creates the conflict I was seeing. My final solution was to use require syntax instead.

Yes. I've noticed this as well. Maybe this should be outlined in the readme somewhere...
