### ISSUE TITLE
How can we get uid of a draft during compose email 

### ISSUE THREAD

**Issue by uc-ach** [KartikTalwar/gmail.js#403]
I am working on a gmail extension, in whichI want functionality like I gave a button which closes compose window and gets uid of the message, on other end I want to extract body of email by providing that uid which i got during composing,
the problem is I am just getting draft Id not draft uid, how can i get uid during composition of draft

![3](https://user-images.githubusercontent.com/23550609/26912361-6a39d426-4c31-11e7-9b6e-b1c97d1edccd.png)

**Comment by josteink** [comment]
To the best of my knowledge there is no way using this API to get a unique ID for a draft from a compose window.

Any patches to provide this functionality would be very much welcome.

**Comment by josteink** [comment]
Closing issue due to question being answered and lack of activity.
