### ISSUE TITLE
gmail.get.email_data(id) taking over 300ms

### ISSUE THREAD

**Issue by danielms215** [KartikTalwar/gmail.js#406]
Calls to gmail.get.email_data() with an id passed in are taking over 300ms per call.
Is this normal behaviour? Is there something wrong on my end?

Thank you in advance!

**Comment by KartikTalwar** [comment]
this is the expected behavior as this function makes a network call to get
email data directly from gmail for a given id
ᐧ
ᐧ

**Comment by danielms215** [comment]
Thank you!
