### ISSUE TITLE
Observe compose is returning undefined data

### ISSUE THREAD

**Issue by danieltigse** [KartikTalwar/gmail.js#407]
I am using the observer for the compose action:

```js
gmail.observe.on('compose', function(compose,type) {
console.log(compose.$el.context.id);
});
````

And the attribute compose.$el.context.id is returning undefined.

**Comment by josteink** [comment]
A compose has no ID until it is saved as a draft. 

I don't think there's any simple way for us to fix this.

**Comment by danieltigse** [comment]
I used to get this value before, I think something changed in Gmail.

**Comment by josteink** [comment]
In my extension I've bound event handlers to closures containing the compose ref. 

That way the id is set when things are triggered later. Could that work for you?

**Comment by danieltigse** [comment]
Yes I could works, Can you share me some code?

**Comment by josteink** [comment]
Not here and now, no. Sorry.

**Comment by danieltigse** [comment]
I think is a problem with gmail look the table created by gmail:
```html
<table cellpadding="0" class="cf An" id="undefined">
```
