### ISSUE TITLE
How to get thread_ids for each visible thread

### ISSUE THREAD

**Issue by sabyasachi** [KartikTalwar/gmail.js#413]
I am trying to fetch the thread_ids for each visible emails in Gmail interface. 

`https://mail.google.com/mail/u/0/#inbox/15d97a4f1ac7ea94` <- `15d97a4f1ac7ea94` is the thread_id.

Basically, I should be able to map a thread_id to its corresponding DOM element. I need the thread_ids in the same sequence as I can see them in the interface. I was hoping get.visible_emails() returns the emails in the same order. Is that assumption correct? I am not getting in the same sequence.

I have tried the following code. When I run it, I see mismatch between sequence of the DOM elements and the array returned by `get.visibble_emails()`.

```javascript
var fetch_ids = function () {
    var gmail = new Gmail;
    var emails = gmail.get.visible_emails();

    //select the email "rows"
    var doms = $("[gh='tl'] .zA");

    doms.each(function(index, domElement) {
        var id = emails[index].id;

        //print subject returned by visible_emails API
        console.log(index + '=>' + emails[index].title);

        //print subject from the DOM elements
        console.log(index + '=>' + $($("[gh='tl'] .zA")[index]).find('.bog').text());
    });
};
```
My questions are:

- Ami I missing anything? Is my assumption correct that visible_emails will return the results in the same sequence as in the Gmail interface?

-  Also, I have 100 visible threads in the interface, but I the get.visible_emails API returns 120. Is that expected?

**Comment by josteink** [comment]
I think the with the current code we have, the best way to express is it that the order returned is not strictly defined.

Basically we make a server-request about the current view-state and return it in whatever order the server-response gives us. We don't attempt to sort it or analyze it further.

Maybe you can use the `time` attribute to do a customer sort after retrieving the data?

**Comment by josteink** [comment]
Assuming issue resolved due to inactivity. Closing.

**Comment by sabyasachi** [comment]
>  I should be able to map a thread_id to its corresponding DOM element. I need the thread_ids in the same sequence as I can see them in the interface. I was hoping get.visible_emails() returns the emails in the same order. Is that assumption correct? I am not getting in the same sequence.

Sorry for replying late. The problem was that I had "Gmail Tabs" enabled. So:

The get.visible_emails() API returns all emails including Promotions, while Gmail tabs filters out promotion emails from the Primary tab, there will be a mismatch in the sequence.
