### ISSUE TITLE
Unable to create gmail.dom.email object

### ISSUE THREAD

**Issue by stefanlenoach** [KartikTalwar/gmail.js#414]
I've tried the following:
1.
```
gmail.observe.on('open_email', function(id){var email = new gmail.dom.email(id);})
// open email
> Error: api.dom.email called with invalid element/id
```

2.
```
gmail.observe.on('view_thread', function(){})
gmail.observe.on('view_email', function(e){console.log(e);}) 
// open email
> TypeError: Cannot read property 'pop' of null
@ gmail.js line 2250:  this.id = this.id_element.attr('class').match(/(^|\s)m([\S]*)/).pop();
```

Also, `gmail.get.email_id()` seems to always return `null`, probably a bug.
Any help is much appreciated. Thanks!

**Comment by stefanlenoach** [comment]
First solution just started working for me...not sure what changed but I can move forward now at least.

**Comment by josteink** [comment]
Glad you worked it out. I was thinking about looking into this tomorrow, but now I guess I don't have to. 

Feel free to re-open if you really encounter an issue like this.
