### ISSUE TITLE
send email with gmail js

### ISSUE THREAD

**Issue by hamzaahmad** [KartikTalwar/gmail.js#416]
Dear Jostein

thanks for all your effort ,can you show us example how we can send email via gmail js?

best

**Comment by josteink** [comment]
Sorry. but I don't have time to outline every possible use-case this library has with an example.

If you have a intermediate javascript background, the thing you want to do should be fairly doable by reading the docs, checking the source for where the library provides related functionality, but not the exact thing you need, and generally just glue things together as needed.
