### ISSUE TITLE
Cannot read property 'each' of undefined

### ISSUE THREAD

**Issue by sieppl** [KartikTalwar/gmail.js#418]
Happens during loading gmail.js

![grafik](https://user-images.githubusercontent.com/837595/29515618-65e175b6-866d-11e7-9a07-94b306b6544c.png)

**Comment by josteink** [comment]
Is this from a plain boilerplate repo (if so, which?) and have you made any modifications?

**Comment by sieppl** [comment]
yes, I am using the boilerplate. It seems sometimes loading jquery fails, which would explain the above error.  To fix this I have tried following in the main.js

```javascript
function refresh(f) {
  if( (/in/.test(document.readyState)) || (typeof Gmail == 'undefined') || (!window.jQuery)) {
    setTimeout('refresh(' + f + ')', 10);
  } else {
    f();
  }
}
```

This prevents the above mentioned error, but the timeout loop never ends, it seems in this case jQuery is never loaded.

**Comment by josteink** [comment]
Try using the node boilerplate instead. 

That completely eliminates loading related issues like this.

**Comment by sieppl** [comment]
Thank you, the node boilerplate work much better and stable for me.
