### ISSUE TITLE
Best way to observe that we are back in the inbox

### ISSUE THREAD

**Issue by sieppl** [KartikTalwar/gmail.js#420]
How can I oberve that the inbox was opened, e.g. when the user leaves a thread and goes back. 
I guess oberserving `http_request` is not the right way as gmail might load the inbox from cache.

**Comment by josteink** [comment]
This is covered in the readme. Check the observe.on function and related events.

**Comment by sieppl** [comment]
Yes, I am aware of observe.on, which event does fire when the inbox is opened?

**Comment by josteink** [comment]
Please check the readme. It's in there.

**Comment by sieppl** [comment]
I am sorry, but there is no such event described in the readme. `refresh` comes close but is not fired all the time when the inbox is opened.

**Comment by josteink** [comment]
Actually, it seems you are right.

We have a method to determine the kind of page you are on though. You can check that every time the user navigates, by subscribing to the `onhashchange`-event:

````javascript
window.onhashchange = () => {
    console.log("current page: " + gmail.get.current_page());
};
````

**Comment by josteink** [comment]
Assuming proposed solution works due to lack of further activity on this issue. Closing.
