### ISSUE TITLE
Observe view_email in view_thread

### ISSUE THREAD

**Issue by CyNn0** [KartikTalwar/gmail.js#422]
When we try this
>`  gmail.observe.on('view_thread', function(obj) {
        console.log('view_thread', obj);
       gmail.observe.on('view_email', function(obj) {
          console.log('individual email opened', obj);  // gmail.dom.email object
      });
    });`

We get this error : Uncaught TypeError: Cannot read property 'pop' of null

So i changed from gmail.js:2049 
` this.id_element = element.find('div.ii.gt');` 

to

`this.id_element = element.find('div.a3s');`

And it seems to work but could you please check this
thx alot for that pretty complete and understandable api

**Comment by josteink** [comment]
Some comments about your original code: You are creating `view_email` observeables on every `view_thread` event. That's not needed, and may be a source of problems.

Please rewrite that section and try again.

Could you also please provide the full strack-trace you get when you are experiencing this? Does it happen every time you open a thread? Or only when you CTRL-R or load directly into a thread?

Also: Are you using traditional script loading with the "old-style" boilerplate, or are you using modern script-bundling using the node-boilerplate?

**Comment by CyNn0** [comment]
`gmail.js:2250 Uncaught TypeError: Cannot read property 'pop' of null
    at new Gmail.api.dom.email (gmail.js:2250)
    at handler (gmail.js:1123)
    at Function.<anonymous> (gmail.js:1075)
    at Function.each (jquery-1.10.2.min.js:4)
    at Object.Gmail.api.observe.trigger_dom (gmail.js:1074)
    at handler (gmail.js:1113)
    at Function.<anonymous> (gmail.js:1075)
    at Function.each (jquery-1.10.2.min.js:4)
    at Object.Gmail.api.observe.trigger_dom (gmail.js:1074)
    at String.<anonymous> (gmail.js:1363)`

I'm currently dont nothing 

  gmail.observe.on('load', function () {
       gmail.observe.on('view_thread', function() {
          console.log('test');
      });
and this error trigger everytime i tryied to open a thread

**Comment by josteink** [comment]
There's no such code in the line-numbers you reported.

Which again leads me to the following question:

* Does it happen every time you open a thread? Or only when you CTRL-R or load directly into a thread?
* Are you using traditional script loading with the "old-style" boilerplate?
* Or are you using modern script-bundling using the node-boilerplate?

Also:

* What version of Gmail.js are you using? How did you obtain it?

Please answer them this time :)

**Comment by CyNn0** [comment]
pretty much traditional script loading with the "old-style" boilerplate
And I guess i'm using the one contained in your "hello world"  sample
so it seems to be   `api.version           = "0.4";`

**Comment by josteink** [comment]
Thats ages old. Get the latest version first.

**Comment by CyNn0** [comment]
Yah that's my bad, did not check if that sample provided was updated
Thanks to be so reactive

**Comment by CyNn0** [comment]
Well with the last version there is no problem, that was my bad not checking it
thanks for your help
