### ISSUE TITLE
Adding a button to gmail compose which inserts html into body of email

### ISSUE THREAD

**Issue by LymeSimon** [KartikTalwar/gmail.js#423]
I have managed to work out how to add a button when a new compose window is opened using:

gmail.observe.on("compose", function(compose, type) {
&nbsp;&nbsp;var compose_ref = gmail.dom.composes()[0];
&nbsp;&nbsp;gmail.tools.add_compose_button(compose_ref, '<button title="My Button">Click Me</button>', 
&nbsp;&nbsp;function() {
&nbsp;&nbsp;&nbsp;&nbsp;// Code here
&nbsp;&nbsp;}, 'Custom Style Classes');
});

Now I need that button, when clicked, to insert custom html at the current insertion point in the email.
The html inserted will be an image with an external src URL and a link, for example:

`<a href="http://myserver.com/user?userid=1234"><img src="http://myserver.com/image?imageid=5678" /></a>`

I can't see how to manipulate the current compose window's DOM as it seems that should be done with an xhr object, and observe on compose doesn't appear to return one.

Any ideas?

LymeSimon

**Comment by josteink** [comment]
I know it doesn't answer your question, but your current code won't be able to handle multiple compose-windows.

Why not just use the `compose`-variable passed into the function instead of all that gmail.dom.composes()[0] nonsense?

**Comment by LymeSimon** [comment]
Darn it you've worked out that I don't really know what I'm doing ;-) I'm an old school procedural programmer and really struggle with OO code.

The documentation for gmail.gs gives the gmail.dom.composes() bit [as an example](https://github.com/KartikTalwar/gmail.js/blob/master/README.md#gmailtoolsadd_compose_buttoncompose_ref-content_html-onclick_action-custom_style_class) to add a button.

Any chance you could give me some idea how I could use the compose object to add the button and to make that button insert some html? I will need to use an ajax call to get the html code, if that makes any difference.

Cheers
LymeSimon

**Comment by josteink** [comment]
> I'm an old school procedural programmer and really struggle with OO code.

Gotcha. Then I hope the next answer will be too scary :)

> Any chance you could give me some idea how I could use the compose object to add the button and to make that button insert some html?

In the `compose`-event, you should register your button using a function *closure* which keeps the `compose`-ref.

You can use this `compose`-ref's `dom()`-method to obtain the various DOM elements of the compose-dialog.

You can see the various DOM elements available here: https://github.com/KartikTalwar/gmail.js/blob/54ab61932d5522421b7535c10b6a303b97ac3a43/src/gmail.js#L2654-L2670

I'm guessing the "body" element is the one you're after.

> insert custom html at the current insertion point in the email.

And this is gmail.js stops helping you out. From here on, you're on your own. (And I'm closing the issue)

I guess you can fake some DOM events to insert your contents at the currently active , but you'll have figure this out on your own.

One thing I would research before doing anything else is.... Does the current insertion point remain active *after* you have clicked something outside the text-area (like your button)?

Good luck!
