### ISSUE TITLE
api.helper.get.visible_emails_pre function

### ISSUE THREAD

**Issue by rushglen** [KartikTalwar/gmail.js#425]
start is returning NAN because gmail have changed their html layout.

start is currently defined like this:
`var start = $(".aqK:visible .Dj").find("span:first").text().replace(",", "").replace(".", "");`

replace with this and it works!
`var start = $('div[class^="J-J5-Ji amH"][role="button"][aria-expanded="false"]:visible')[0].childNodes[0].childNodes[0].childNodes[0].innerHTML.trim();

There's probably a better way of doing this - suggestions welcome!
`
edit: also I notice that previously when start = NAN it returned 120 visible emails, now it returns 350....
when viewing inbox, 
however if viewing sent it returns 120....

**Comment by josteink** [comment]
Could you prepare this as a PR so it’s easier for us to test?

**Comment by josteink** [comment]
Old issue is old. Closing.
