### ISSUE TITLE
Unable to get email body in a thread reply

### ISSUE THREAD

**Issue by luciocorrea** [KartikTalwar/gmail.js#428]
Hi guys.

I'm trying to get the email's content in a thread reply but I don't know how to do it. I already searched in the closed issues and found #231 but didn't understand that answer.

Can you guys give me a hint?

Thank you in advance.

**Comment by josteink** [comment]
You'll have to use the DOM API, not the data API. You're given a DOM compose-instance if you subscribe to the `"compose"` DOM-observer.

Check the readme for details, and prototype a "compose"-observer. If you check the params your event-handler receives, it should be pretty self-explanatory.

**Comment by luciocorrea** [comment]
@josteink I tried this:

```
var main = function(){
  gmail = new Gmail();
    
  gmail.observe.on("compose", function(compose, type) {
      if (type == "reply"){
        console.log("Reply");
        var body = compose.body();
        compose.body('<h1>My New Heading!</h1>' + body);
      }
    });
  }
```
But that didn't work.  I'm trying to create a default message when I click "Reply". 

Can you help me?

**Comment by josteink** [comment]
On initial inspection, that does look proper to me.

* Do you see the message you wrote in the console log?
* Are you using "traditional" script loading, or modern NodeJS-style script-bundling?

Can you demonstrate this issue in a self-contained sample repo?

**Comment by luciocorrea** [comment]
> Do you see the message you wrote in the console log?
Yes, the "Reply" is logged  in the console

> Are you using "traditional" script loading, or modern NodeJS-style script-bundling?
I just forked "gmail-chrome-extension-boilerplate" repository, updated gmail.js file from main repository and replaced the code in the main function.

**Comment by josteink** [comment]
That repo is causing a lot of issues, and I'm planning to remove all links to it...

Try using this one instead:

https://github.com/josteink/gmailjs-node-boilerplate

**Comment by luciocorrea** [comment]
@josteink I forked it, but it still doesn't work: https://github.com/luciocorrea/gmailjs-node-boilerplate

**Comment by josteink** [comment]
Thanks for the sample-repo. I could reproduce it.

If you wrap the call to mutate the compose-instance in a setTimeout({}, 0), it gives the UI time to draw before altering it.

````javascript
   setTimeout(function () {
      compose.body('<h1>New Email!</h1>');    
   }, 0);
````

That at leasy works for me.

**Comment by luciocorrea** [comment]
@josteink It worked now, thank you very much!

**Comment by luciocorrea** [comment]
@josteink I reopened because I got another issue related to that:

If I try to get the body of the compose,  in the compose-instance, I only get a "<br>" as a result. 

It looks like the body of the previous reply is only showed if the "show trimmed content" button is clicked.

I updated the code in the repository to show it.

Any idea?

Thank you in advance.

**Comment by josteink** [comment]
Not really no. 

Sounds like this is something outside what the API currently supports.

**Comment by josteink** [comment]
Old issue is old. Closing.
