### ISSUE TITLE
insertion_observer 'cn.trim is not a function'

### ISSUE THREAD

**Issue by revmischa** [KartikTalwar/gmail.js#429]
When hiding gmail native compose:
<img width="734" alt="screen shot 2017-10-15 at 14 32 12" src="https://user-images.githubusercontent.com/245131/31584793-ae9175f4-b1b5-11e7-9eac-5262b0e53efe.png">

**Comment by josteink** [comment]
Could you elaborate a little on this error. Can you provide some sample code to reproduce it?

**Comment by revmischa** [comment]
I added some debugging and found that it is erroring on this:
<img width="682" alt="screen shot 2018-02-15 at 11 23 07" src="https://user-images.githubusercontent.com/245131/36252787-7178a38c-124e-11e8-80e5-62e670cc7e65.png">

**Comment by josteink** [comment]
Old issue is old. Closing.
