### ISSUE TITLE
Shared value between sent emails

### ISSUE THREAD

**Issue by panchicore** [KartikTalwar/gmail.js#433]
I realized that when I sent an email, `gmail.get.email_id()` from the sender is different than the receiver, also you can see it easily from the url. Is there any bullet-proof value that could work as a unique-id for database crossing info between both parties?

I tried, md5 hashing `senderemail-receiveremail-subject`, but the subject could change on the conversation lifecycle, which makes me think of creating another table to store all the ids related to each party, hence this question. Thanks.

**Comment by josteink** [comment]
There's only one globally unique identifier for an email as for as I know...

That's set by the MTA actually sending the email, and it can be found at the SMTP/MIME-layer. It looks like this:

````
Message-ID: <593b0768dfab369d.1508780229123.110264644.20047653.no.e6772ee17e0ca97f@google.com>
````

There's no direct gmailjs API-call to get it, but you if you use `api.get.email_source_promise()` or `api.get.email_source_async()`, you can use that to get the actual MIME-message and extract the header itself.

**Comment by panchicore** [comment]
Seems like it is what I need. No need to create ugly hashes, the message id is more reliable and even better is data that says something. Can I ask which is your strategy to cross-check info among diffs threads?

**Comment by josteink** [comment]
I don't, at least not within Gmail.

I merely use this as a document-key when extracting info from Gmail into external systems.
