### ISSUE TITLE
Get email id/details on click of dropdown menu next to reply button

### ISSUE THREAD

**Issue by NishanthiDev** [KartikTalwar/gmail.js#438]
I would like to get 'email id/details' on click of the dropdown menu, not the entire thread details but the particular email only on which the button is clicked.

Can anyone help me sharing your thoughts please.

Btw, a great library to work with. Thanks to Kartik Talwar and his team for this awesome piece.

**Comment by josteink** [comment]
You will have to do something custom to get that.

What I've done in our extension for SuperOffice is that I've added an event-handler for the `view_email` Gmail.js-event, which is run *once* when the email is rendered to HTML for the first time.

In this event, you have a specific Email DOM instance available to you, in which you can extract the exact email-id, as opposed to the thread-id.

You must then keep this email-id in a closure (or whatever) for use later, when needed.

Hope this helps.

**Comment by NishanthiDev** [comment]
@josteink thanks for your reply, the above logic works well to me! 

And unlike 'view_email' observer triggered on the click of every message in a thread for the first time, i see 'load_email_menu' gets triggered on a single message in the thread.
Is this an expected behaviour of 'load_email_menu' event ?

**Comment by josteink** [comment]
I'm not sure and I don't remember. `gmail.js` is not fully documented, but if nothing else it's open-source.

In that regard, checking out (or backtracking) the implementation is probably the best way to get accurate answers about questions like this.

**Comment by NishanthiDev** [comment]
Thanks again for your reply @josteink 

I cross-verified 'load_email_menu' event, it is triggered just on any one message in the thread for the first time, and not for every individual messages in the thread.

Anyway, i did some custom workarounds and could achieve the use-case where 'load_email_menu' getting handled for every individual message was in need.

Thanks

**Comment by josteink** [comment]
Glad you worked it out!
