### ISSUE TITLE
Button to support functionality with "all attachments"

### ISSUE THREAD

**Issue by Nishanthi** [KartikTalwar/gmail.js#441]
Hi, 

I have a use-case to deal with all the attachments with the email, i would need a button to be placed next to 'Download all attachments' and 'Save all to Drive' in the attachment section of the email message.
I see an API to add button to individual attachments but not one to support all the attachments.

Can anyone share your thoughts on this please, does GmailJS support this or should this be a custom approach and has to be taken care from the web extension end ?

**Comment by josteink** [comment]
You’ll have to piece that together yourself, but the API should make it possible as far as I can tell.

**Comment by Nishanthi** [comment]
I could achieve the requirement, closing this ticket.
Thanks
