### ISSUE TITLE
TypeError: Cannot read property 'GLOBALS' of undefined

### ISSUE THREAD

**Issue by Brantron** [KartikTalwar/gmail.js#449]
`TypeError: Cannot read property 'GLOBALS' of undefined`
I'm not sure why this is error is popping up? Here's a basic example of what I'm doing

```
import GmailFactory from 'gmail-js'
import $ from "jquery"

class GmailObserver {
  constructor() {
    this.gmail = new GmailFactory.Gmail($)
  }
}
```

**Comment by josteink** [comment]
I assume you searched for duplicates and figured this one out yourself :)
