### ISSUE TITLE
Support to add 'link' and 'attachment' to compose window

### ISSUE THREAD

**Issue by Nishanthi** [KartikTalwar/gmail.js#452]
Hi,

In my project, i have a requirement to add a button to compose window and on click of the button i will have to perform the below actions from my document management system to the compose window. 
    1>upload the files as 'link' 
    2> upload the files as a 'attachment' 
(Just like the link and attachments getting uploaded from GDrive)

From GmailJS we have an API to add button to compose window, and i am looking for the approaches for points 1 and 2.

Can anyone suggest me please.

**Comment by josteink** [comment]
All the current features of gmailjs have been:

* added by people who reviewed the codebase
* adapted it to fulfill whatever needs they had
* and sent these patches back upstream. 

If you want features not currently present your best (and only?) option is to do the same.

**Comment by Nishanthi** [comment]
I could achieve the 1 and 2 points mentioned above, closing this ticket.
Thanks
