### ISSUE TITLE
callback is not a function

### ISSUE THREAD

**Issue by o-x-y-g-e-n** [KartikTalwar/gmail.js#453]
I get this error while executing -> gmail.get.email_data_async()
extension.js:2138 Uncaught TypeError: callback is not a function at extension.js:2138 at Object.<anonymous> (extension.js:1661) at fire (extension.js:6297) at Object.fireWith [as resolveWith] (extension.js:6427) at done (extension.js:12334) at XMLHttpRequest.<anonymous> (extension.js:12577) (anonymous) @ extension.js:2138 (anonymous) @ extension.js:1661 fire @ extension.js:6297 fireWith @ extension.js:6427 done @ extension.js:12334 (anonymous) @ extension.js:12577 XMLHttpRequest.send (async) send @ extension.js:12629 ajax @ extension.js:12235 Gmail_.api.tools.make_request_async @ extension.js:1659 Gmail_.api.get.email_data_async @ extension.js:2136 (anonymous) @ VM94723:1

Also the text of the email body is decreased to 3 dots. How can i extract the whole email body.
Thanks.

**Comment by josteink** [comment]
Read the documentation. [gmail.get.email_data_async](https://github.com/KartikTalwar/gmail.js#gmailgetemail_data_asyncemail_idundefined-callback), as the name implies is [async](https://en.wikipedia.org/wiki/Asynchrony_(computer_programming)). That means it doesn't return a value immediately. It needs a callback which will be provided the result upon completion.
