### ISSUE TITLE
js_frame doesn't present in dom

### ISSUE THREAD

**Issue by phyxolog** [KartikTalwar/gmail.js#455]
Hi. When i'm tested my extension, i see, that not everyone have `js_frame`. Proofs:

Without js_frame:

![87ba367e-c2eb-4262-9d41-6e2a305fc46d](https://user-images.githubusercontent.com/5149171/37662130-09b0e900-2c5f-11e8-959f-09f2401fa714.jpeg)

With js_frame:

![screenshot from 2018-03-20 16-47-12](https://user-images.githubusercontent.com/5149171/37661966-aa5db79e-2c5e-11e8-9530-734cdbc042b5.png)

So, i get many errors in the first case. Ideas?

Error text: `
Uncaught Cannot register the xhr watcher as mail.google.com is not fully loaded yet. Please wrap your code in gmail.observe.on("load")
`
(but code wrapped in `load`, script injected after tab loaded)

**Comment by josteink** [comment]
Thanks for reporting in, and for have some useful debugging info along it.

The code in question here was most recently rewritten by @michi88.  Maybe he can offer some comments? Are there any fallback strategies we can apply in this case?

**Comment by josteink** [comment]
I've submitted some code which may or may not address this in the following branch: https://github.com/KartikTalwar/gmail.js/tree/js_frame_fix

I can't guarantee this will solve all your issues, but if you could test it and report back how this works, that might help us move the issue along :)

**Comment by phyxolog** [comment]
@josteink it works, thanks)

**Comment by josteink** [comment]
I’m not fully aware of all the implications of all the aspects of the code I’ve modified here so I would appreciate it if you tested all aspects of your extension and regular operation of Gmail and made sure that there’s no regressions or new errors introduced. 

Could you do that?

I would also advise to compare with regular Gmail operation with no extension installed while having the web developer Console open to monitor for errors. are new errors showing up?

**Comment by phyxolog** [comment]
@josteink Well, I'll do it when I full testing my extension, after this I will report you about problems/or their lacks :)

**Comment by josteink** [comment]
I've done some very basic testing with this modified code (and other modifications), and from what I can tell this now works.

Changes have been merged to `master` and will be available in the next upcoming stable release.
