### ISSUE TITLE
Get Email address

### ISSUE THREAD

**Issue by GodStar88** [KartikTalwar/gmail.js#457]
Hello.
I want to get the email address when i open the message.
I just used gmail.js, but i can't get the any email address.
Please help me, Thank you.
![capture](https://user-images.githubusercontent.com/23701978/37838224-4d5ec0e2-2ef2-11e8-893c-f3360f16c3ad.PNG)

**Comment by josteink** [comment]
What have you tried? Have you read the readme? Did you use any of the existing boilerplate repos linked in the repo?

**Comment by GodStar88** [comment]
Yes, 
var gmail = Gmail();
gmail.get.user_email();

but i can't get email address.

**Comment by josteink** [comment]
Is that an actual quote? If so you are missing a “new” before the Gmail.

**Comment by GodStar88** [comment]
I am not clear

**Comment by GodStar88** [comment]
Hello.
I want to get the email address when i open the message.
I just used gmail.js, but i can't get the any email address.

var gmail = Gmail();
gmail.get.user_email();

Please help me, Thank you.

**Comment by josteink** [comment]
Gmail.js is for web-extesions. WebExtensions pressume you know alot about javascript.

Your error is that you are not using `new`. Your code should be like:

````javascript
var gmail = new Gmail();
````

These concrete examples are mentioned directly in the readme and boiler-plate samples.

Please check the documentation and samples before opening an issues next time.

**Comment by GodStar88** [comment]
Thank you

**Comment by GodStar88** [comment]
Thank you.
But i got error.
![capture](https://user-images.githubusercontent.com/23701978/37881808-929e4388-30cf-11e8-871d-dd51f2bd61c6.PNG)

**Comment by josteink** [comment]
I've asked lots of questions, but not gotten much answers,.

* Have you read the readme?
* Did you use any of [the existing boilerplate repos](https://github.com/josteink/gmailjs-node-boilerplate) linked in the readme?
* If none of that works, can you post a FULL repo demonstrating your issue?

If you can't answer those questions, we can't help you.
