### ISSUE TITLE
How to get profile pics?

### ISSUE THREAD

**Issue by getzvnm** [KartikTalwar/gmail.js#458]
How to get logged in gmail user image and recipients image on recipient_change event?
@josteink

**Comment by 30bySixty** [comment]
I don't think this is part of the Gmail.js library. We attempted to grab the image urls ourselves, but it ultimately wasn't worth the effort because the gmail divs that contain user and recipient images are often created dynamically on mouseover events.

**Comment by josteink** [comment]
From what I can tell, this is looked up dynamically via som XHR social-graph stuff:

![image](https://user-images.githubusercontent.com/411338/42201123-badfa462-7e96-11e8-831a-b1d6d6a9106b.png)

![image](https://user-images.githubusercontent.com/411338/42201100-a67787ec-7e96-11e8-8e13-8a0059b4b120.png)

We can clearly see a URL to some "usercontent" there, and that's the photo:

![image](https://user-images.githubusercontent.com/411338/42201167-dde8c98e-7e96-11e8-9e54-55a6665e6d7e.png)

If we could find out how to forge/generate the first request, we could look this up, but looking at the URL, I don't see any obvious things to plug into or replace in that URL:

https://apis.google.com/u/0/_/socialgraph/lookup/hovercards/?n=0&sp=0&cmp=2&src=gmail&soc-app=1&cid=0&soc-platform=1&hl=en_GB&ozv=\<stuff\>&f.sid=\<stuff\>&_reqid=\<sequence?\>&rt=j

The SID does *not* represent the message or thread Id, so I have no idea what that is.

Maybe a simple approach is checking the DOM? Looking into the HTML for the same email, I get this (under the DOM-node for the email-message itself):

````html
<img id=":0_146-e"
     name=":0"
     src="https://plus.google.com/u/0/_/focus/photos/public/AIbEiAIAAABECKiT1qv9rZG_-AEiC3ZjYXJkX3Bob3RvKigwOTAzOWMzZTEyNmU4ZTFhNjhiYTJkOWVkMmExYTRjM2QwYjg5NTM2MAEPRoZnxth4oyKWLhi0z-IKc2ztoQ?sz=32"
     class="ajn"
     jid="joaotavora@gmail.com"
     data-hovercard-id="joaotavora@gmail.com"
     data-name="João Távora" aria-hidden="true">
````

Based on that it seems fairly trivial to get a photo for a given email-address, *if* that address represents a shown email:

````javascript
var emailAddress = "joaotavora@gmail.com";
var photoNode = document.querySelector("img[data-hovercard-id='" + emailAddress + "']");
var photoUrl = photoNode.src;
photoUrl
// https://plus.google.com/u/0/_/focus/photos/public/AIbEiAIAAABECKiT1qv9rZG_-AEiC3ZjYXJkX3Bob3RvKigwOTAzOWMzZTEyNmU4ZTFhNjhiYTJkOWVkMmExYTRjM2QwYjg5NTM2MAEPRoZnxth4oyKWLhi0z-IKc2ztoQ?sz=32
````

This gives us the tiny thumbnail, but from what I can tell, the sz-param represents size and can be tweaked:

Like this: https://plus.google.com/u/0/_/focus/photos/public/AIbEiAIAAABECKiT1qv9rZG_-AEiC3ZjYXJkX3Bob3RvKigwOTAzOWMzZTEyNmU4ZTFhNjhiYTJkOWVkMmExYTRjM2QwYjg5NTM2MAEPRoZnxth4oyKWLhi0z-IKc2ztoQ?sz=256

Maybe that works for you. Maybe it doesn't. But I was able to cook that up in less than 15 minutes, so I figure whoever spends a little more time at this, may be able to get even further.

**Comment by josteink** [comment]
Old issue is old. Closing.
