### ISSUE TITLE
Custom toolbar button hide when click on next page button 

### ISSUE THREAD

**Issue by geekdiv** [KartikTalwar/gmail.js#459]
Here is my issue is when first-time Gmail load button is rendered properly but when I click on next button my custom toolbar button is hidden. 

![joxi_screenshot_1522671899923 1](https://user-images.githubusercontent.com/12626079/38196377-7212c4be-36a0-11e8-9662-e740381ef63c.png)

After click on next or previous button   

![joxi_screenshot_1522672613516](https://user-images.githubusercontent.com/12626079/38196623-b5f88528-36a1-11e8-91fe-e5b75e06e28f.png)

I want to display that button consistent (means all pages).  

How to do that ? for next and previous button any observe event ?

**Comment by josteink** [comment]
I'm pretty sure you can use the window-object's hash_change event for that:

https://developer.mozilla.org/en-US/docs/Web/API/WindowEventHandlers/onhashchange

**Comment by geekdiv** [comment]
@josteink  Thanks for reply. When I did't use Tab view then custom button hide. Please check it your side once. It's working well in Tabview.
