### ISSUE TITLE
'get.email_data_async' returns 'attachments_details' as null though attachments are present

### ISSUE THREAD

**Issue by Nishanthi** [KartikTalwar/gmail.js#461]
Hi,
I am trying to fetch 'attachment details' for each of the conversations in a message thread using 'email_data_async' API.
This API returns the details of all the messages, but for some messages the 'attachment_details' is null though 'attachments' property shows some values.

Part of the sample response below:
{
attachments: ["browser-ui.png", "Screenshot.png", "Screen Shot123.png", "Screenshot.png"]
attachments_details: null
}

To reproduce kindly check with any thread with >(5 to 6) conversations.

Anyone, please share your thoughts/inputs.

**Comment by Nishanthi** [comment]
@josteink  thanks for your reply.

Below are some observation points:
1> I can reproduce the above issue with plain 'api.get.email_data()' as well
2> similar behavior with 'get.displayed_email_data()'
3> Other DOM API I check is 'gmail.dom.email(emailId).attachments()',
    Here, at times 'url' and 'type' properties goes missing in the response
    Sample response: 
     [{name: "hosts.txt", size: "1 KB"}, 
      {name: "gmail js observations.docx", size: "25 KB"},
      {name: "GI-779.txt", size: "1 KB"},
      {name: "export (6).txt", size: "1 KB"}]

Can you suggest any alternate API where I can fetch the attachment details for an email message?
I browsed the entire list and these are APIs and their responses I see.

**Comment by Capo93** [comment]
I have the same problem.

@Nishanthi have you find any solution for this issue?
