### ISSUE TITLE
Support for new Gmail UI

### ISSUE THREAD

**Issue by anaimi** [KartikTalwar/gmail.js#462]
Hi,

1. Anyone has any insights whether the new Gmail redesign will be compatible with gmail.js?
2. Do you know if Gmail will be on the same subdomain (mail.google.com) or new subdomain?

Thanks

**Comment by josteink** [comment]
1. Testing shows that work will be needed. XHR/data changes seems to have caused highest impact. There will be some effort to fix this once the maintainers have time and capacity. Any help appreciated. 
2. The domain seems to be the same.

**Comment by anaimi** [comment]
Thanks @josteink. Do you know where I might be able to get my hands on the new version?

**Comment by josteink** [comment]
I’m not 100% sure what’s the best way here is.

My company is bound by an NDA on these matters so there’s limited amount of details I’m able to discuss or disclose. 

I suggest searching for all news and announcement for more developer-oriented details.

**Comment by josteink** [comment]
Preliminary work has been made in the 0.7.0 version to use documented compatible “legacy” APIs for select parts of the codebase

Using these should ensure compatibility until they are deprecated in early 2019. 

Amount of functions tested remains low though. 

In the meantime upgrading to 0.7.0 is recommended to avoid outright crashes upon upgrade.

**Comment by josteink** [comment]
Old issue is old. Closing! :)
