### ISSUE TITLE
Can't get unread emails correct number

### ISSUE THREAD

**Issue by luco** [KartikTalwar/gmail.js#464]
Trying to get unread emails correct number, but it always gives me 0 while I have 1 unread email. Calling get.user_email gives me the correct email, so I think it's properly connected, right?

![image](https://user-images.githubusercontent.com/246373/39079775-ad7fa89a-44f7-11e8-9b1a-252323d9407b.png)

**Comment by josteink** [comment]
From a cursory glance that looks correct. Does any other methods works as they should? For instance `gmail.get.email_id()` ?

And are you enrolled in any Gmail beta or preview-program?

**Comment by tosolini** [comment]
Same for me, not gmail beta or gmail 2018 version. Spam is correct, but inbox report zero

**Comment by tosolini** [comment]
Ok i got the problem, is related to translation. Gmail.js check inbox, but if you have another language fail.

**Comment by josteink** [comment]
Oh. That's interesting and probably makes sense. Thanks for diagnosing!

In that case, `gmail.js` do have [methods to do locale-detection](https://github.com/KartikTalwar/gmail.js/#gmailgetlocalization)... So making this portion more language-aware should not really be that hard.

I'm a little squeezed on time right now though. If you would be interested in making a PR for this, I'll be happy to review and merge.

**Comment by tosolini** [comment]
thx @josteink for reply. I've check the locale-detection and report the correct language id (it in my case), but in translate i've add to api.tools.i18n the related case dictionary array and still not working. I try switching to the NL lang and is not working, bu FR goes ok... don't know why. Anyway i've made a PR

Thx

**Comment by josteink** [comment]
@luco: Can you elaborate on what locale you are using when this fails?

If this still doesn't work for you, feel free to issue a PR like @tosolini did in https://github.com/KartikTalwar/gmail.js/pull/508.

It should be fairly simple both for you to make and for me to review :)
