### ISSUE TITLE
Gmail create a new Interface

### ISSUE THREAD

**Issue by cboivin80** [KartikTalwar/gmail.js#468]
Gmail create a new interface, and the event no more connected.

Did you will modify this project or you will start a new one ?

**Comment by josteink** [comment]
Support for new Gmail is an ongoing issue. 

GmailJS 0.6.x would *crash* on new Gmail and all data-methods would fail. 

Clearly some improvements have been made. Have patience or provide patches yourself :)

**Comment by cboivin80** [comment]
Yes sorry i did not see other thread!

I will see if i am able to fix some issues :~
