### ISSUE TITLE
how can we add default recipient,subject and email content to an emial compose window?

### ISSUE THREAD

**Issue by getzvnm** [KartikTalwar/gmail.js#470]

**Comment by josteink** [comment]
Read the documentation.

Specifically we have an event for new compose-windows, and we do have methods for these fields in the compose DOM instances.

**Comment by getzvnm** [comment]
i know the compose window event   
```
 gmail.observe.on('compose', function(obj) { 
     console.log('compose_obj', obj);
});
```
 but i dont get the method to change the email contents when a window opens

**Comment by josteink** [comment]
https://github.com/KartikTalwar/gmail.js/#gmaildomemailemail_el-or-email_id

**Comment by josteink** [comment]
The compose object has several functions and methods for this exact purpose.
Just check the instance received in the event!

https://github.com/KartikTalwar/gmail.js/blob/master/src/gmail.js#L2768-L2919
