### ISSUE TITLE
add_toolbar_button not works when compose window opens

### ISSUE THREAD

**Issue by getzvnm** [KartikTalwar/gmail.js#472]
```
gmail.tools.add_toolbar_button(logo_html, function() {  
  // Code here
}, 'logo');
```
does not add button when compose window opens ,else it works well

 api.dom.toolbar  returns as `selector:"[gh='mtb']"` , when compose window opens

**Comment by josteink** [comment]
First patan should be compose-instance from event. 

That at least works for me.

**Comment by getzvnm** [comment]
why should i need compose instance to add button in gmail toolbar?

**Comment by josteink** [comment]
Just to double-check: Does this apply to the function always, or is this an error introduced with new Gmail?

**Comment by getzvnm** [comment]
'content_html' button shows onload

![with_button](https://user-images.githubusercontent.com/37620550/39953335-8954e2a6-55c7-11e8-8217-e21aaa098c17.jpg)

button doesn't shows when page reload by opening compose window
![without_button](https://user-images.githubusercontent.com/37620550/39953342-b125d60a-55c7-11e8-99e8-d0feff3b34e4.jpg)

**Comment by getzvnm** [comment]
'content_html' button shows onload
![with](https://user-images.githubusercontent.com/37620550/39953365-0c3914a8-55c8-11e8-956b-dac9e5477f89.jpg)

button doesn't shows on page reload by opening compose window
![without](https://user-images.githubusercontent.com/37620550/39953367-20fe6adc-55c8-11e8-8554-623ca9d72425.jpg)

**Comment by josteink** [comment]
That’s a known issue. You will have to re-add your buttons on reloads or layout changes. 

That’s also the expected behavior which people have written code to anticipate in numerous extensions, so we won’t change that now.

**Comment by getzvnm** [comment]
issue fixed by re-add button
