### ISSUE TITLE
gmail.observe.before("send_message") is not working on new Gmail

### ISSUE THREAD

**Issue by mailbeep** [KartikTalwar/gmail.js#479]
Hey,

There are 2 issues with before send message event on new Gmail:

1. The actual message is sent before the event is fired
2. xhr.xhrParams.body_params does not contain to, cc and bcc properties. 

I am using the latest 0.7.2 version

Any help would be appreciated.
Eugene

**Comment by josteink** [comment]
Support for new Gmail is work-in-progress.

As you can see in https://github.com/KartikTalwar/gmail.js/issues/478, there's clearly additional info in the XHR message. We just need to shred it and parse it.

I've been "lazy" and only ensured gmail.js covers the needs I have for the extension I maintain for my company, as I'm pretty short on time.

If you want to help out and issue a PR to cover the missing bits, all contributions are welcome!

Incidentally, that's also open-source is supposed to work: Several people contributing useful code which covers their need into a common project and a bigger goal. Open-source is not a free ride which means that someone else writes your code for you. Sorry :smile:

**Comment by bastiendonjon** [comment]
Hello,
You have news ?
thanks

**Comment by josteink** [comment]
Latest Gmail.js has a new data api via gmail.new.get.

It lets you get email content based on new message id and the sent event contains the message id. 

Together this should hopefully be sufficient to get something working.

**Comment by bastiendonjon** [comment]
Ok i look that.

You think that rewrite email body with this new version ?

**Comment by josteink** [comment]
To rewrite the message-body I suspect you must do so before it is queued for sending (i.e. in the compose window). Maybe it's possible to intercept the send-button even there and modify in place before that fully triggers?

**Comment by kevinpiac** [comment]
@josteink, it's possible to listen for click on "send button" and rewrite the body content before to effectively trigger the click.

However, it might be also possible (not tested) to intercept the "send" method of XMLHTTPRequest and rewrite the body on the fly.

**Comment by josteink** [comment]
I personally will not work on implementing this before-handler. Closing as wontfix. 

PRs are welcome though.
