### ISSUE TITLE
Is there any option to add default 'to address ' in compose window

### ISSUE THREAD

**Issue by getzvnm** [KartikTalwar/gmail.js#483]
Is there any option to add default 'to address ' in compose window in events like

 `gmail.compose.start_compose()` 

`gmail.observe.on('compose'`

by passing email address?

edited:
tried  
```
gmail.observe.on('compose', function(obj) {   
         compose_email = '123@gmail.com';
         $('.wO').append('<div class="vR"><span class="vN bfK a3q" email="'+compose_email+'" data-hovercard-id="'+compose_email+'"><div class="vT">'+compose_email+'</div><div class="vM"></div></span><input name="to" type="hidden" value="'+compose_email+'"></div>');
        });
```

**Comment by josteink** [comment]
Compose is object with lots of methods.

Why not use those provided?

**Comment by josteink** [comment]
Compose is object with lots of methods. Why not use those provided?

This really should be covered by the stuff already there, but I see that in the readme that compose-functionality is under-documented.

If you'd like to fix that, any such PR will be accepted :)

**Comment by getzvnm** [comment]
worked the following code:

```
gmail.observe.on('compose', function(obj) {   
         compose_email = 'test@gmail.com';
         setTimeout(function(){ 
                obj.find('textarea.vO').val(compose_email); 
                compose_email = '';
         },500); 
 });
```

**Comment by josteink** [comment]
Why not use the *compose object* directly?

````javascript
gmail.observe.on('compose', function(compose) {   
         setTimeout(function(){ 
                compose.to(compose_email);
         },500); 
 });````
