### ISSUE TITLE
open_mail is never triggered on opening an email from inbox mode on new Gmail UI in v0.7.3.

### ISSUE THREAD

**Issue by thinksysprem** [KartikTalwar/gmail.js#484]
**gmail.js version: 0.7.3**

inside the `gmail.observe.on('load')` handler, I have this code:

`gmail.observe.on('load', function name() {
            var userProfile = _getUserProfile();

            _postMessage({
                type: "GMAIL_INIT",
                payload: {
                    user_profile: userProfile
                }
            });

            gmail.observe.before('send_message', beforeSendMessageHandler);
            gmail.observe.after('send_message', aftersendMessageHandler);
            gmail.observe.on("open_email", openMailHandler);
            closeMailHandler(); // gmail lib does not have a even for this and register is not working
            gmail.observe.on("compose", composeMailHandler);
            gmail.observe.on("save_draft", saveDraftHandler);
            gmail.observe.on("recipient_change", recipientChangeHandler);
            checkForOpenAtLoad();
        });`

All handlers are registered without a problem, Proof:
![open_email_xhr_registration_on_load](https://user-images.githubusercontent.com/18140689/40784447-4e514906-6503-11e8-8387-0a94dc93a30d.png)

**But on opening the email from inbox mode, the handler is never triggered.**

**Chrome version: Version 66.0.3359.181 (Official Build) (64-bit)**

**Other Active extensions:**
1. Google Docs
2. Google Sheets

Am I doing something wrong?

**Comment by josteink** [comment]
That sounds very likely.

Gmail.js has a pretty big feature-set, and far from all of it is supported on new Gmail.

Work has been done to ensure some basic stuff works (like not crashing, getting email meta-data, handling multiple concurrent Gmail.js-versions, etc), but lots of stuff remains.

One of the things where probably least have been done is events.

If you need to get an event working, I suspect the quickest/easiest way to get there is by providing a PR yourself.

In the mean time... Any reason you use the `open_email` instead of the `view_thread` and `view_email` events (which should be working)?

**Comment by thinksysprem** [comment]
`open_email` gave us the 'id' of the opened thread directly while `view_thread` gave us the jQuery element which would require scrapping to find out the message id from the element. We require the id to get the data about the email asynchronously via `gmail.get.email_data_async`. 

![image](https://user-images.githubusercontent.com/18140689/40955764-a83b32c0-68a9-11e8-885d-257ce661af0e.png)

Once I changed the implementation to use `view_thread` as suggested above, another gmail.js feature `gmail.check.is_conversation_view()` threw an exception. I will open a separate issue for this but for now I have a quick question

Does there exists a list of features/api methods/endpoints that are not supported by gmail.js for the new Gmail UI, so we know exactly **what** and **how much** we have to deal with? 

This will be a huge help for us to identify the areas or flows impacted and need fixing in our application.

**Comment by josteink** [comment]
If you use the `view_email` sub-observer (as opposed to the main `view_thread` observer) you get a [api.dom.email](https://github.com/KartikTalwar/gmail.js/blob/master/src/gmail.js#L3031-L3052)-instance which comes with code to handle IDs and stuff already, so you at least shouldn't have to handle that.

`gmail.check.is_conversation_view()` being broken... Might be right. I don't use it myself.

If you have any PRs, I promise friendly reviews for all of themt :)

**Comment by thinksysprem** [comment]
`view_email` does not get triggered just like the `open_email`

**Comment by josteink** [comment]
> `view_email` does not get triggered just like the `open_email`.

`view_email` is a sub-observer of `view_thread` (which means you need to subscribe to that event too, even if you're not doing anything).

Iirc it is a DOM-based observer and not XHR, but yes, it will only trigger upon first viewing of the email. It's thus suitable for DOM-based manipulation of that email, but not for code which needs to run every time that email is shown.

> Any thoughts?

Yes and no.

1. There are parts of the current gmail.js implementation I really don't like, and would like to fix.
2. I'd really like to rewrite some of the stuff into more modern constructs (ES-classes, maybe even TypeScript)
3. There's *no way* we're going to get all 141 API-functions tested and working on new Gmail in a reasonable time.
4. For a gmail.js-user these is no way to know what bits are supported or not, meaning new Gmail will be a recurring theme in all bug-reports for the foreseeable future.

Especially the last point there, means I'm considering a rather radical option:

*Create/fork a new Gmail.js which is not backwards compatible*.

When creating this new version, we could then upgrade the codebase to use modern constructs and tooling, and only port in the functions we know work with both the old and the new Gmail.

This would have several advantages:

* Clear visibility for Gmail.js users about what functions are available and working across versions.
* Reducing API-surface to only the bits in use, or which has active maintainers
* Possibility to upgrade Gmail.js to a more modern toolchain.

Ofcourse all this would take some time and effort, but I don't have too much of that these days.

And I'd also like to not alienate the Gmail.js-userbase. So as a Gmail.js-user, how would you see such a change?

**Comment by josteink** [comment]
Seems like you got your issue fixed "accidentally" through another PR.

Care to get latest source from git and test?
