### ISSUE TITLE
gmail.check.is_conversation_view() throws an exception when executing in new Gmail UI

### ISSUE THREAD

**Issue by thinksysprem** [KartikTalwar/gmail.js#485]
This is the exception encountered:

![image](https://user-images.githubusercontent.com/18140689/40956291-08beccee-68ad-11e8-87d0-00b3cdb35e08.png)

gmail.js version: 0.7.3

Chrome version: Version 66.0.3359.181 (Official Build) (64-bit)

Other Active extensions:

Google Docs
Google Sheets

**Comment by josteink** [comment]
Can confirm. `gmail.check.is_conversation_view()` doesn't work with new gmail.

Seems this is one of the few functions which [depends almost exclusively on `globals`](https://github.com/KartikTalwar/gmail.js/blob/master/src/gmail.js#L2547), and the `globals`-object has seen major changes in the new Gmail.

My guess is that we'll have to find some other way to determine this view-mode for new Gmail.

**Comment by thinksysprem** [comment]
I did some digging and found out:

The very depended on property `api.tracker.globals[17]` is null for the new Gmail UI that means it is going to impact the following methods apart from the method in question here.

- `api.get.last_active`
- `api.get.loggedin_accounts`
- `api.get.localization`
- `api.check.should_compose_fullscreen`
- `api.check.is_plain_text`
- `api.check.are_shortcuts_enabled`

**Comment by josteink** [comment]
Yeah. We're aware of it, but no-one has put in any effort to fix those parts.

This is a open-source project with very limited resources, so the parts of Gmail.js which are supported are the ones we (the main maintainers) are using ourselves or which we receive patches for.

There's just no way I can sit down, test and reverse engineer, figure out and fix the 141 API functions we have received in form of community patches over the years. The community itself will have to help out fix the parts which they are actively using and need fixed,

**Comment by shashikiran-im** [comment]
After spending quite amount of time I found that window.GLOBALS[69] will reflect "Conversation View" setting.

Now i am planning to update is_conversation_view() method to make it work on both in classic and new gmail interface.

Need help:
It will be great if anybody has found solution to know whether user is in classic mode or new gmail interface mode (So that we can make is_conversation_view() work in both the modes).

Thanks in Advance,
Shashikiran

**Comment by josteink** [comment]
@shashikiran-im: Great findings. Please make a PR for it!

> It will be great if anybody has found solution to know whether user is in classic mode or new gmail interface mode (So that we can make is_conversation_view() work in both the modes).

We already have new Gmail-specific code, and we already have implemented checks for this, using documented methods provided by Google.

You can use the following two methods:

* api.check.is_new_data_layer()
* api.check.is_new_gui()

See source here: https://github.com/KartikTalwar/gmail.js/blob/b5ea3b8/src/gmail.js#L247-L254

Please note one of those are about the *GUI* being new, and the other one about the *data layer* being new.

For anything which relates to `globals`, I think it's safe to assume this is the new *data layer*. New GUI checks should be reserved for CSS and purely visual stuff.

**Comment by shashikiran-im** [comment]
Hi Josteink,

I had fixed the lint error and generated new pull request.
Please do merge it.

Thanks[,
Shashikiran

**Comment by josteink** [comment]
Fixed via #491 and released in package version 0.7.4.

**Comment by josteink** [comment]
Actually contained a minor error which may affect a tiny percentage of users who are slowly migrated to new Gmail without explicitly upgrading.

I recommend upgrading to 0.7.5 if you've already upgraded to 0.7.4.
