### ISSUE TITLE
gmail.observe.before('send_message') email body editing(through body_params(or/and body)) errors on new GMail

### ISSUE THREAD

**Issue by kinkoazc** [KartikTalwar/gmail.js#488]
The tampered-with message request triggers a "Oops.. the system encountered a problem (#102)" alert, and the optimistic, successful response, gets reverted. This is probably due to the new security rules. Will changing the email's body be possible for the new GMail? Thank you.

**Comment by josteink** [comment]
Speaking as a maintainer, I've never used this functionality and won't be investing time in this area myself.

I suggest you look in previous issues for other people who have used this functionality in the past, and discuss with them. Together you may come up with a solution?

And if you find one, PRs are definitely welcome.

**Comment by kinkoazc** [comment]
Thank you for the quick reply and work! I've seen on a different [issue ](https://github.com/KartikTalwar/gmail.js/issues/478) that you had to sign an NDA for access to the docs on GMail's internals(the old version). What were the conditions? Is this something that I can have access to(as a collaborator to this library)?

**Comment by josteink** [comment]
I can't promise anything, but you may try to reach out to Aisha Thiessen (aishawithaneye@google.com) and see if she can help you out.

**Comment by kinkoazc** [comment]
This issue is fixed for v0.7.6. Thank you.
