### ISSUE TITLE
"move_label" event not working in new gmail UI

### ISSUE THREAD

**Issue by shashikiran-im** [KartikTalwar/gmail.js#494]
Hi,

"move_label" event not working in new gmail UI.

API method:
gmail.observe.on("move_label", function(id, url, body, label, xhr) {});

Has anyone found the root cause of the issue / fixed the issue.
Please share your thoughts if you have made any progress.

Thanks in Advance,
Shashikiran

**Comment by josteink** [comment]
> Has anyone found the root cause of the issue / fixed the issue.

The root cause is changed XHR the new GMail data-layer (not new GUI).

This format has not yet been fully reverse engineered and event-support is therefore lacking.

Please inspect the existing code for supporting events in new Gmail data-layer and issue PRs if you find fixes.

**Comment by shashikiran-im** [comment]
Hi All,

I tested latest version of GmailJS library (of version 0.9.9) and observed that "move_label" event is not working when email is moved to label by dragging and dropping it.

Could anyone had made any progress on this issue then please do let me know.

Thanks in Advance,
Shashi

**Comment by shashikiran-im** [comment]
Hi All,

I had analyzed the HTTP request when email is dragged and dropped to an existing label and label is applied to the email (from toolbar) as shown in the below request.

Email is dragged and dropped to an existing email:
{"2":{"1":[{"1":"19","2":{"1":"thread-f:1643175894745010884|msg-f:1643175894745010884","2":{"7":{"1":["^x_3936349673376384568"],"2":["^ri_hl","^i","^iim","^t_p","^t_rd","^us","^k","^s"],"3":["msg-f:1643175894745010884"],"4":"1570629612477"}}}}]},"3":{"1":1,"2":"744240","5":{"2":0},"7":1},"4":{"2":1,"3":"1570629612483","4":0,"5":427},"5":2}

Label is applied to an email (from label toolbar):
{"2":{"1":[{"1":"20","2":{"1":"thread-f:1643108118967574812|msg-f:1643108118967574812","2":{"7":{"1":["^x_8368183271314027004"],"3":["msg-f:1643108118967574812"]}}}}]},"3":{"1":1,"2":"744259","5":{"2":0},"7":1},"4":{"2":1,"3":"1570629778945","4":0,"5":428},"5":2}

Here is my observation,
	1. In both above cases, "^x_" is getting passed in the POST request.
	2. "^x_" can be used in GmailJS project where it will invoke both the events "label" & "move_label" (as shown in the below source code),
		api.tools.check_event_type = function(threadObj) {
		    	const label = "^x_";
		        const action_map = {
		            // ""            : "add_to_tasks",
		            "^a": "archive",
		            "^k": "delete",
		            // ""            : "delete_message_in_thread",
		            // ""            : "delete_forever",
		            // ""            : "delete_label",
		            // ""            : "discard_draft",
		            // ""            : "expand_categories",
		            // ""            : "filter_messages_like_these",
		            // ""            : "label",
		            "^x_"            : "label",
		            // "^io_im^imi": "mark_as_important",
		            // "^imn": "mark_as_not_important",
		            // ""            : "mark_as_not_spam",
		            // ""            : "mark_as_spam",
		            // ""            : "move_label",
		            // ""            : "move_to_inbox",
		            // ""            : "mute",
		            "^u^us": "read",
		            // ""            : "save_draft",
		            // ""            : "send_message",
		            // ""            : "show_newly_arrived_message",
		            // "^t^ss_sy": "star",
		            // ""            : "undo_send",
		            // ""            : "unmute",
		            "^u"            : "unread",
		            // "^t^ss_sy^ss_so^ss_sr^ss_sp^ss_sb^ss_sg^ss_cr^ss_co^ss_cy^ss_cg^ss_cb^ss_cp": "unstar",
		            "^us"            : "new_email",
		            // ""            : "poll",
		            // ""            : "refresh",
		            // ""            : "restore_message_in_thread",
		            "^o": "open_email",
		            // ""            : "toggle_threads"
		        };
		        const threadData = api.tools.get_thread_data(threadObj);
		        if (threadData && api.check.data.is_action(threadData)) {
		            const action = api.tools.get_action(threadData);
		            //return action_map[action];
					//Check if label is applied to email / existing email is moved to an label
		            if(action.startsWith(label) && api.check.data.is_first_type_action(threadData)) {
		                return action_map[label];
		            } else {
		                return action_map[action];
		            }            
		        } else {
		            return null;
		        }
		    };
	3. "label" & "move_label" callback events is getting called with email details.
		
Can anybody let me know if "label" & "move_label" logic can be relied on observing to the prefix "^x_".
Please share your thoughts.

Thanks in Advance,
Shashi

**Comment by josteink** [comment]
Old issue is old. Closing.
