### ISSUE TITLE
"delete_label" event not working in new gmail UI

### ISSUE THREAD

**Issue by shashikiran-im** [KartikTalwar/gmail.js#495]
Hi,

"delete_label" event not working in new gmail UI.

API method:
gmail.observe.on("delete_label", function(id, url, body, label, xhr) {});

Has anyone found the root cause of the issue / fixed the issue.
Please share your thoughts if you have made any progress.

Thanks in Advance,
Shashikiran

**Comment by josteink** [comment]
> Has anyone found the root cause of the issue / fixed the issue.

The root cause is changed XHR the new GMail data-layer (not new GUI).

This format has not yet been fully reverse engineered and event-support is therefore lacking.

Please inspect the existing code for supporting events in new Gmail data-layer and issue PRs if you find fixes.

**Comment by shashikiran-im** [comment]
Hi @josteink  / @hankypanky666,

I had analyzed HTTP request format of deleting existing label operation and found that 4th represent that the label is to be deleted as shown below.

Request Format:
{"2":{"1":[{"1":"8","4":{"1":"^x_8571846599374771753","2":{"2":{}}}}]},"3":{"1":1,"2":"4500741","5":{"2":0},"7":1},"4":{"2":1,"3":"1531112160709","4":0},"5":2}

Label ID to be Deleted: ^x_8571846599374771753"

Need Clarification:
1. Existing logic is not handling delete label operation in parse_request_payload() method (As it is not neither an email and not thread).
2. I think i should add one more method (similar to api.tools.get_thread_data()) to read the 4th key data and take appropriate action.

Please let me know if you have any thoughts on the implementation plan (Meanwhile i start implementing the logic)

Thanks,
Shashikiran

**Comment by shashikiran-im** [comment]
Hi,

I had implemented the logic to handle and fire "delete_label" event and it is working fine.
But want you people to have look and give your review comments.

NOTE: @josteink i am unable to generate PR as my previous PR is not yet merged.

Thanks,
Shashikiran

**Comment by josteink** [comment]
@shashikiran-im: You can start multiple PRs. Just make sure your changes are in different branches.

Right now, it's hard for me to merge the previous PR, since it contains extra changes (and not just what the PR was meant to fix).

**Comment by josteink** [comment]
@shashikiran-im Can you generate a new PR now?

**Comment by josteink** [comment]
Old issue is old. Closing.
