### ISSUE TITLE
How to get email signature in gmail.observe.on('compose', function( ) ?

### ISSUE THREAD

**Issue by getzvnm** [KartikTalwar/gmail.js#498]
Hi, 
i need to add atext in combox body ,i did it by following. but it replaces my email signature. How to add text without replace email signature?

```
gmail.observe.on('compose', function(obj,type) {
        window.setTimeout( function() { 
            obj.body('<div style ="display:block">Hi</div>');
        },0);
)};
```

**Comment by josteink** [comment]
obj.body() alone will give you the existing body. 

Use that and append your data to the returned value, before setting the new value.

**Comment by getzvnm** [comment]
`obj.body(obj.body()+'<div style ="display:block">Hi</div>');` worked. Thanks.

**Comment by kstubs** [comment]
This is the pattern I am using, and works well.


```
		_gmail.observe.on('compose', function(obj,type) {
			function temp() {
				obj.body('<div style ="display:block">Hi</div>' + obj.body());
			}
			setTimeout(temp, 100);
    	});
```
