### ISSUE TITLE
Email tracking option exists?

### ISSUE THREAD

**Issue by getzvnm** [KartikTalwar/gmail.js#499]
is there any method exists to track the gmail? ie to know reciever  opened the email or not 

 " i am added a tracking link which tracks when reciever opens the mail";
 ```
gmail.observe.before('send_message', function (url, body, data, xhr) {
    var unique        =   '_' + Math.random().toString(36).substr(2, 9);
    var tracking_link = "mydomain.com/track-email/"+unique;  
    var tracking_link =  '<img src="https://'+tracking_link+'" width="1" height="1">';
    body_overwritten     = data.body+tracking_link;
            ...
            ...
 });
```
 " the issue with this , it also tracks the mail open when sender opens the mail from sent items 
    Is there any method exists to change the tracking link url when sender opens the mail or any other methods?";

**Comment by josteink** [comment]
This is a question fundamentally about email-tracking, not about `gmail.js`, so I'm closing this one.
