### ISSUE TITLE
Handle composition/reply/forward

### ISSUE THREAD

**Issue by ghost** [KartikTalwar/gmail.js#50]
Hi,

Currently there are two observers to handle email data at its creation.
- **send_message**, even though it doesn't seem to include the new email content ;
- **show_newly_arrived_message** which doesn't seem to work for me, in the way that I expect it to trigger a callback when the new email enters the current thread.

By _creation_ I mean one of these :
- **composition** of a new email, performed in a dedicated popin (which in turn has several display configurations) ;
- **reply to**/**forwarding** of a previous email, performed right under it (or in popin mode too).

It would be nice to access relevant elements whenever the user starts editing an email. I know this looks UI-oriented, but as it actually triggers draft saving and whatnot as background routine, I'd have thought maybe there's something to track there.
## 

Maybe my use case is a bit too specific, but I try to include a custom control in the body of the edited content (like a custom button), then perform extension-related things using the new content. Finally I try to take into account the new email in the thread right away.

So here we have three relevant things to wish an access for:
- a DOM element for the edition "frame", that would be found in `api.dom` ;
- an observer for the submission event, in `api.observe`, passing the new content ;
- an observer for the integration of the new email in the current thread.
## 

What do you think of this?
Am I missing something already here, or asking too much?
Anyway I don't expect it to be obvious.

Thanks.

**Comment by josteink** [comment]
This seems both old and solved. Closing.
