### ISSUE TITLE
How to get conversation is in sent items or inbox?

### ISSUE THREAD

**Issue by getzvnm** [KartikTalwar/gmail.js#502]
```
gmail.observe.on('view_thread', function (obj) {
});
```

how to know the currently opened conversation is selected from sent items or from inbox inside above method ?

i done it with 
 ```
if(obj['$el'][0]['baseURI'].indexOf("https://mail.google.com/mail/u/0/#sent/") > -1) {
console.log('inside sent items');
}
```

check

But is there any dom method?

**Comment by josteink** [comment]
There is.

This is probably what you're looking for:

https://github.com/KartikTalwar/gmail.js/blob/master/README.md#gmailgetcurrent_page

Next time, please check the readme.
