### ISSUE TITLE
Is there any method to trigger gmail compose send button?

### ISSUE THREAD

**Issue by getzvnm** [KartikTalwar/gmail.js#504]
```
 gmail.observe.on("compose", function(compose, type) {  
    gmail.tools.add_compose_button(compose, 'click', function() {  
      });
 });

```
Is there any method to trigger gmail compose send button onclik of 'click' button ?

**Comment by josteink** [comment]
Please read the docs, source and inspect the objects you have available to you at runtime. 

All these questions you ask can easily be answered that way. 

I’ll answer this question with a yes, the compose instance offers that functionality. 

You go find out how. Github issues is not a support service. It’s primarily intended for bug-reports.
