### ISSUE TITLE
There are errors if switch to new GmailUI

### ISSUE THREAD

**Issue by vikram1234** [KartikTalwar/gmail.js#517]
extension.js:1072 Uncaught Cannot register the xhr watcher as mail.google.com is not fully loaded yet. Please wrap your code in `gmail.observe.on("load")`

Gmail_.api.tools.xhr_watcher | @ | extension.js:1072
-- | -- | --
  | Gmail_.api.observe.bind | @ | extension.js:1165
  | Gmail_.api.observe.on | @ | extension.js:1190
  | 3.gmail-js | @ | extension.js:13405
  | o | @ | extension.js:1
  | r | @ | extension.js:1
  | (anonymous) | @ | extension.js:1

**Comment by josteink** [comment]
Can you reproduce this behaviour if you use the node boilerplate project?

https://github.com/josteink/gmailjs-node-boilerplate

**Comment by vikram1234** [comment]
![screen shot 2018-08-17 at 6 53 08 am](https://user-images.githubusercontent.com/11531441/44262796-482b0c00-a1ea-11e8-8240-275a23474d03.png)

**Comment by vikram1234** [comment]
yes its with boilerplate code, i downloaded this few days back.

**Comment by josteink** [comment]
Can you create a minimal git repo which reproduces this behaviour?

**Comment by vikram1234** [comment]
I did not do anything, i just switched from old view to new

Gmail->settings icon->Try the new gmail
[Archive.zip](https://github.com/KartikTalwar/gmail.js/files/2297088/Archive.zip)

**Comment by josteink** [comment]
Got it. I see that you're not using the latest version of Gmail.js.

Can you try updating?

**Comment by vikram1234** [comment]
Extension.js or Gmail.js? 

I just followed your steps 2 days back unless there are new updates in last 2 days.

**Comment by josteink** [comment]
Gmail.js. I'm not sure that boilerplate repo always pulls in the latest version from npm.

Can you try upgrading?

**Comment by vikram1234** [comment]
i just took latest code and same issue - 

[gmailjs-node-boilerplate.zip](https://github.com/KartikTalwar/gmail.js/files/2297205/gmailjs-node-boilerplate.zip)

**Comment by vikram1234** [comment]
My internet speed is 50MS. 
Did you try to switch to new view? 
![screen shot 2018-08-20 at 4 53 46 am](https://user-images.githubusercontent.com/11531441/44330466-148ff200-a435-11e8-9d73-77fa562a9da4.png)

**Comment by vikram1234** [comment]
how to inject custom scripts in the plugin? 

I tried to adding in and declaring in manifest.json but it says gmail not found.

**Comment by josteink** [comment]
Why not place your code in extension.js or require it from there?

**Comment by josteink** [comment]
Anyway: initial issue resolved. Closing.

**Comment by vikram1234** [comment]
there are two extension.js dist, src. The src/ never called and dist/ is big file already.

**Comment by josteink** [comment]
This is not a fault in gmailjs and the example repo. These repos are not “learn JavaScript” support forums. 

Knowledge about JavaScript is a prerequisite to use this library. 

You need to completely disregard gmailjs, take a break, read up on how modern day JS development with script-bundling (browserify, webpack, etc) works.

When you understand that, using gmailjs will be easy.

**Comment by vikram1234** [comment]
@josteink So issue starts if i add another event in extension.js file, is that wrong way do do that?

gmail.observe.on("load", () => {
    const userEmail = gmail.get.user_email();
    console.log("Hello, " + userEmail + ". This is your extension talking!");
});
gmail.observe.after("load", () => {
    console.log("Hello, This is your extension talking!");
});
![screen shot 2018-08-20 at 12 30 38 pm](https://user-
images.githubusercontent.com/11531441/44353439-f5b15000-a474-11e8-8ea1-228fc5319546.png)

**Comment by vikram1234** [comment]
![screen shot 2018-08-20 at 12 30 38 pm](https://user-images.githubusercontent.com/11531441/44353463-0e216a80-a475-11e8-942d-6bfb47d7f541.png)

**Comment by vikram1234** [comment]
@josteink and same works with old Gmail UI without any changes.

**Comment by josteink** [comment]
As for injecting, I'm not sure what you are asking about:

`src/extensionLoader.js` is the content-page loaded by the extension.

`src/extension.js` is built into `dist/extension.js`. This file is the *injected* script. Anything you reference/require() in this script will be injected too.

You're already injected. What more do you need?

**Comment by vikram1234** [comment]
@josteink Thanks for your time, we decided to use some other API due to no support of new GMAIL UI. 

We have been facing lots of issues while switching to New UI (it works well with old UI though).
I apologize that I could not explain all issues but later when I did more testing with NEW, most of events not working, exceptions. Even tried from console but most of events does not work with new UI. 

The Iframe api look for to setup observer is not in source with new UI - 

<iframe id="js_frame" class="invfr" name="jn4nsqfv37gdi" src="/_/scs/mail-static/_/js/k=gmail.main.en.PZY5abr1U30.O/am=Fno7YBwg3j5A-AKYnTHAcBBAmoGw-T-CLAV4GwBhjP___wAGBwA9AMA34P8PaDkAAAAAAAAAAAAAAAAAAAC4o8Av/rt=h/d=1/im=1/rs=AHGWq9Cpt-KHtDEQdZQqeGi4BMVEgVPcQQ/m=pds,pdl,pdit,m_i,pdt,t,it" tabindex="-1" title="empty" aria-hidden="true"></iframe>

I thank you for your time, please let us know once New UI is supported.

And yes I accept that i am not expert with new JS frameworks, i have been mostly working with Jquery for long years and been backend developer, and it was bit hard for me to inject JS with this, all though i got it working but actually that was not the issue.

Thank you!

**Comment by josteink** [comment]
> we decided to use some other API due to no support of new GMAIL UI

This is an on-going effort. And gmailjs is a open-source project. Nothing gets added, unless an *active contributor* decides to add it.

>  I did more testing with NEW, most of events not working

This is [a known issue](https://github.com/KartikTalwar/gmail.js/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aopen+event+new). It's being worked upon. By active contributors who needs those events working. They're submitting patches, and so can you.

> we decided to use some other API due to no support of new GMAIL UI

That's entirely your call.
