### ISSUE TITLE
Question: toolbar button is appearing, when loading the mail for the first time

### ISSUE THREAD

**Issue by Debolinap** [KartikTalwar/gmail.js#518]
I am adding toolbar button to the gmail view, using gmail.js.
-----------------------------------
 var main = function() {
  gmail = new Gmail();
   // add toolbar
  gmail.tools.add_toolbar_button('', function()) }

 calling this main function on page loading,
------------------------------------------
refresh(main);
function refresh(f) {
  if( (/in/.test(document.readyState)) || (typeof Gmail === undefined) ) {
    setTimeout('refresh(' + f + ')', 10);
  } else {
    f();
  }
}

As, I am calling this main() on page loading, this toolbar button is appearing right after we are opening gmail ui.
but my requirement is to show the toolbar button only when at least 1 mail is selected, like other toolbar buttons. How to catch the event of mail selection, so that I can call the add_toolbar_button() only when at least one mail is selected from visible label

**Comment by Debolinap** [comment]
used display:none style class to hide the button for 1 st time load of gmail. now button is visible only if 1 mail is s elected by checkbox. but button remains hidden if user clicks on the mail and open it

**Comment by cancan101** [comment]
Related to this issue, it looks like gmail on the inbox list is setting the `display` style to `none` for the the button if you select and then unselect an thread.

**Comment by josteink** [comment]
So basically even more pitfalls then? 😅

**Comment by josteink** [comment]
Old issue is old. Closing.
