### ISSUE TITLE
New Gmail design - observe

### ISSUE THREAD

**Issue by Kreestof** [KartikTalwar/gmail.js#519]
Hi,

we have an application which inserts some text to every sent messages. It uses the following code:

```
gmail.observe.before('send_message', somefunc);
function somefunc(url, body, data, xhr) {
  data.body.concat(...);
}
```

It worked pretty well with the previous design of the gmail, but since 22 August there is a new design with which this code causes a crash with a snackbar saying 
> Message could not be sent. Check your network and try again.

There is no error log in the console. 

Regards,
Kreestof

**Comment by josteink** [comment]
Lacking support for new Gmail is a known issue. It's work in progress.

Among many, many issues, this one is already registered: https://github.com/KartikTalwar/gmail.js/issues/479

Closing as duplicate.
