### ISSUE TITLE
Uncaught SyntaxError: Unexpected token < in JSON

### ISSUE THREAD

**Issue by pttdev** [KartikTalwar/gmail.js#522]
updated: sorry, my fault. I use sync function instead of async because of the docs. Please update the docs from "gmail.get.visible_emails(async)" to "gmail.get.visible_emails_async".

I tried a simple test and got these error.

jquery.js:9488 [Deprecation] Synchronous XMLHttpRequest on the main thread is deprecated because of its detrimental effects to the end user's experience. For more help, check https://xhr.spec.whatwg.org/.
jquery.js:9600 GET https://mail.google.com/mail/u/0/?ui=2&ik=982c4ad31a&rid=undefined&view=tl&num=120&rt=1&start=0&sstart=0&search=data%20=%3E%20%7B%0A%20%20%20%20%20%20%20%20console.log(data)%0A%20%20%20%20%7D 404 ()
send @ jquery.js:9600
ajax @ jquery.js:9206
Gmail.api.tools.make_request @ gmail.js:1916
Gmail.api.get.visible_emails @ gmail.js:2144
gmail.observe.on @ test.js:15
(anonymous) @ gmail.js:1848
setInterval (async)
Gmail.api.observe.on_dom @ gmail.js:1844
Gmail.api.observe.on @ gmail.js:1481
(anonymous) @ test.js:9

VM7748:2 Uncaught SyntaxError: Unexpected token < in JSON at position 1
    at JSON.parse (<anonymous>)
    at Object.Gmail.api.helper.get.visible_emails_post (gmail.js:2108)
    at Object.Gmail.api.get.visible_emails (gmail.js:2145)
    at gmail.observe.on (test.js:15)
    at eval (gmail.js:1848)

my code:
````javascript
gmail.observe.on("load", () => {
    const userEmail = gmail.get.user_email();
    console.log(userEmail);
    console.log('new data layer', gmail.check.is_new_data_layer());
    console.log('new ui', gmail.check.is_new_gui());

    gmail.get.visible_emails(data => {
        console.log(data)
    });
});
````

**Comment by josteink** [comment]
`gmail.get.visible_emails` is not an sync function.

What you provide as a callback is actually a custom query URL filter which is only meant to be used by expert users. The result is a failed request (HTTP 404), and that does not adhere to the JSON format we expect.

Change your code to the following:

````javascript
const data = gmail.get.visible_emails();
console.log(data);
````
