### ISSUE TITLE
Is it possible to get reference to each thread row in the list?

### ISSUE THREAD

**Issue by pttdev** [KartikTalwar/gmail.js#523]
I consider to switch from inboxsdk to gmail.js. My app's main feature is to add a button in each thread row in the list. Inboxsdk has a threadrowview listener so I can add a button to each row but it does not work with new Gmail UI.
It would be great if we have something like `gmail.dom.getReferenceByThreadID()`
I tried to implement this feature by using gmail.get.visible_emails() but I don't know how to get reference to a row.
Does anyone have a solution?

**Comment by josteink** [comment]
Have you tried using the `gmail.dom.email`-class?

**Comment by pttdev** [comment]
`gmail.dom.email` work for current viewed message only. What I want to achieve is select a row in the list of emails. Since I want to target new UI only, I found a way by using this selector: [data-legacy-thread-id~=<thread_id>]

**Comment by josteink** [comment]
Yeah. Once we get going with the Gmailjs2 rewrite effort, we'll probably have more dedicated methods based on either thread OR email IDs.


Either way: Glad you worked it out. Closing.
