### ISSUE TITLE
How to get Message ID after send_message on new UI?

### ISSUE THREAD

**Issue by pttdev** [KartikTalwar/gmail.js#525]
```
using gmail.observe.after("send_message", function (url, body, data, response, xhr) {
        console.log(data);
});
```
the "data" virable showing something like this:
![test-gmail](https://user-images.githubusercontent.com/22335222/44903402-a6053b00-ad36-11e8-8345-ccfebd904147.png)

The message id is data['1']. I wonder if this kind of "weird" format is stable? and does anyone know why google response this kind of messy format?

**Comment by josteink** [comment]
Please search existing issues. 

This particular problem has been discussed extensively elsewhere. 

Closing as duplicate.
