### ISSUE TITLE
"send_message" event is firing twice sometimes ("after").

### ISSUE THREAD

**Issue by shashikiran-im** [KartikTalwar/gmail.js#526]
Issue:
"send_message" fires twice some times in my application.
But "send_message" is firing only once in the same app "GmailJS Node Boilerplate".

Solution tried:
1. I tried to switch off the events using the API method 
gmail.observe.off('send_message');                    //Not working
gmail.observe.off('send_message', "after");        //Not working

None of the solution is working.

Could you please let me know if anybody facing same / found any work around.

Thanks in Advance.

**Comment by josteink** [comment]
> Issue: "send_message" fires twice some times in my application. But "send_message" is firing only once in the same app "GmailJS Node Boilerplate".

Sounds like a loading issue then. Or registering the same event-handlers more than once.

Put a break-point in the code which registers the event-handlers and see if you can reproduce. If so, you need to modify your code to guard against double registration.
