### ISSUE TITLE
How to read "Button labels" settings of Gmail using GmailJS library

### ISSUE THREAD

**Issue by shashikiran-im** [KartikTalwar/gmail.js#530]
Hi,

Gmail allows user to set "Button labels" as "Icons" OR "Text" under settings. When set to "Icons" the toolbar shows only Icons and if it is set to "Text" then it will show title as Text instead of icons.

GmailJS API method gmail.tools.add_toolbar_button() won't honor the "Button labels" setting to show only "Text" / "Icon" depending on the settings.

Does any method available in GmailJS library to get "Button labels" setting.
OR
Anybody had implemented the solution to know the "Button labels" setting (Otherwise will work on it).

Thanks in Advance,
Shashi

**Comment by josteink** [comment]
Nothing built in as far as I know.

**Comment by shashikiran-im** [comment]
Hi,

I was able to find "Button labels" setting in classic UI.

But in new gmail UI, "Button labels" setting is available in the web page (mail.google.com) javascript code in the JSON format, but i think it is difficult to read it.

Does anybody had done any RnD to read the similar setting from web page in new gmail UI?

Thanks in Advance,
Shashi

**Comment by shashikiran-im** [comment]
Hi Jostein,

I implemented #530 to know "Button labels" settings and updated README doc.

Could you please merge the pull request.

Thanks,
Shashi

**Comment by josteink** [comment]
I've done a brief review by looking at the code alone, but I haven't yet have time to test it.

After the code is finalized, I can test and if it works, we merge.

**Comment by josteink** [comment]
Old issue is old. Closing.
