### ISSUE TITLE
gmail.get.email_ids throws error in new Gmail Interface.

### ISSUE THREAD

**Issue by shashikiran-im** [KartikTalwar/gmail.js#531]
Hi,

Issue in new Gmail UI:
I have registered for "view_email" and calling "gmail.get.email_ids()" method to get the threadID list but it throws error.

Steps to reproduce in new Gmail UI:
	1. Compose an email (self-compose)
	2. Open the self-composed / received email immediately  (less than 5 seconds).
	3. Observe that gmail.get.email_ids() throws an error.

Root issue of the issue:
gmail.get.email_ids() method internally calls the method "api.get.thread_id()" which tries to read the threadID from the DOM as stated below & fails as h2 DOM element don't have the attribute "data-thread-perm-id" at all.

const elem = document.querySelector("h2[data-thread-perm-id]"); 

But if I open self-composed / email received after quite amount time (like 15-20 seconds) then the attribute "data-thread-perm-id" is available.

Off course look like Gmail issue. Does anybody found any solution ?

Thanks in Advance,
Shashi

**Comment by josteink** [comment]
This is a known issue.

A sent email in new Gmail can be *cancelled*. In practice that means that Gmail actually postpones sending the email until the cancellation period is expires.

And until the email is sent, it has no legacy ID, so trying to fetch one will fail.

The "solution" (or workaround) is trying to refresh the view until a ID is provided in the DOM.

**Comment by josteink** [comment]
Old issue is old. Closing.
