### ISSUE TITLE
[Question] How to hook into page changes?

### ISSUE THREAD

**Issue by ckarcz** [KartikTalwar/gmail.js#538]
```gmail.get.current_page()``` will provide us with the current page. but is there a way to subscribe to an event that will fire when the page changes?

i need to add toolbar buttons for each inbox-like page. currently when i navigate away from inbox my custom toolbar button disappears.

**Comment by josteink** [comment]
This has been answered in quite a few other issues, like this one. https://github.com/KartikTalwar/gmail.js/issues/459.

Closing as duplicate.
