### ISSUE TITLE
Q: Reading/parsing xhr response

### ISSUE THREAD

**Issue by ginotria** [KartikTalwar/gmail.js#54]
Hello,

I have an observer for the send_message event where I can get data like the composeid and draftid. But for my use case, I would also want to get the email Id of the sent email. 

Upon checking the xhr response for the send_message request the email id is indeed included. Is there a way to read and parse these responses like how xhr_watcher is doing?

Thanks,
Gino

**Comment by JerryBels** [comment]
@KartikTalwar the solution you gave here 

    gmail.observe.on("send_message", function(url, body, data) {
        var id = gmail.get.email_id();
        var info = gmail.get.email_data(id);

        console.log(data.composeid);
        console.log(info.threads); // you can sort the result by highest timestamp to get the newest mail
    })

doesn't work for me. It gives me the compose id, yes, but that's not the id of the email and can't be used in URL to get to that email, as long as I can tell (this gives a numeric id only where the email id starts with 14dab...), and "info" is empty. 

Anything else that I can do to get the email ID on / after send ?

**Comment by JerryBels** [comment]
bump !

**Comment by SfayhiKarim** [comment]
it work for me when i execute this code : 

  
 gmail.observe.on('view_thread', function(obj) {
        console.log('view_thread', obj);

});

gmail.observe.after("send_message", function(url, body, data, response, xhr) {
  console.log( 'xhr', xhr.xhrResponse[1][1][3][0]);
});

**Comment by JerryBels** [comment]
@SfayhiKarim thanks, we discussed the subject here : https://github.com/KartikTalwar/gmail.js/issues/179
