### ISSUE TITLE
In the pane mode is_inside_email returns false positive results

### ISSUE THREAD

**Issue by AlexBazer** [KartikTalwar/gmail.js#540]
From the documentation `is_inside_email`:
> Returns `True` if you are currently inside an email conversation `False` otherwise

As I understand this: if user sees opened email thread, function should return `true`.

But in the pane mode, it doesn't work as expected.

if you select email thread to preview in the inbox folder - `is_inside_email` return `true`
and then if you select any other folder without selecting thread(right pane shows `No conversations selected`) - `is_inside_email` returns `true` too

**Comment by AlexBazer** [comment]
@josteink I'm using 0.7.0 version

**Comment by josteink** [comment]
Latest version is 0.7.7. Try that first.

If you sill have issues on latest, it would also help to know if you're using the old or new version of Gmail itself (not gmailjs).

**Comment by AlexBazer** [comment]
@josteink do you remember why this logic is used for `is_inside_email` in pane mode?

> File: src/gmail.js
> 401:         var items = $(".ii.gt .a3s.aXjCH");
> 402:         var ids = [];
> 403: 
> 404:         for(var i=0; i<items.length; i++) {
> 405:             var mail_id = items[i].getAttribute("class").split(" ")[2];
> 406:             if(mail_id !== "undefined" && mail_id !== undefined) {
> 407:                 ids.push(items[i]);
> 408:             }
> 409:         }
> 410: 
> 411:         return ids.length > 0;

I see a much simpler solution, but not sure if it covers all the cases

`Boolean(document.querySelector('[role="main"] h2[data-legacy-thread-id]'))`

**Comment by josteink** [comment]
I'm honestly not sure about this code. Lots of the gmailjs code looks quite convoluted and messy when given a critical look.

Basically this code seems to rely on some specific DIVs having the message-id encoded into them (as a CSS class). I guess the reasoning is that if we can find *any* div which contains an email-identifier, it we must be inside an email-view of sorts.

Given how Google has made the Gmail DOM much more easily inspectible (using well-defined attributes like in your example), it may be very possible that some of these functions are overdue for a rewrite and simplification.

Feel free to issue a PR.

**Comment by josteink** [comment]
The documentation I've received from Google regarding new GMail says this:

> When a conversation is opened, a `<div class="ha">` would be present in the DOM.

Feel free to test a PR based on that approach and let me know how it works out for your use-cases.

**Comment by AlexBazer** [comment]
@josteink thanks, I'll test.

**Comment by josteink** [comment]
Old issue is old. Closing.
