### ISSUE TITLE
api.tracker.watchdog not initialized?

### ISSUE THREAD

**Issue by Kaydub00** [KartikTalwar/gmail.js#542]
I'm assuming this is related to the new gmail interface. 

I'm not much of a JS developer but I was just tasked with creating a chrome extension for gmail. I've been debugging the issue where I'm trying to observe.before("send_message") but it looks like XHR events aren't working correctly after the change.

I'm seeing an issue at line 1757 where api.tracker.watchdog is undefined. 

I see this is setup under the api.observe.bind function, but it seems this is never called so api.tracker.watchdog is never set.

How does this get initialized? I'd love to help getting this working right again so any maintainers feel free to reach out and point me in the right direction.

**Comment by josteink** [comment]
I don’t think *before* message changed works on New Gmail at all. 

*After* should be good though.

**Comment by Kaydub00** [comment]
Ha, but I need before. Does observe.on work for send_message?

Is there any documentation on what's been found with the google xhr requests? I believe I saw somewhere else that you (maybe someone else) have an NDA but is there anything as part of this project?

What I think I'm seeing is that the bind function is called after the xhr request?

Sorry, still wrapping my head around how this works. I'm basically just trying to find a way to check a few things right before an email is sent and then either cancel sending the email or continue based on that check. Starting to think I should drop using this library for now and just attempt to override the XMLHttpRequests open and send methods myself since this is a pretty narrow use case I need it for.

**Comment by josteink** [comment]
If you want to change the content of an email before sending, I believe right now your only choice is intercepting clicks to the DOM Send-button, alter the compose content and manually trigger a real (unintercepted) send afterwards. 

I know: not really smooth, but that’s the only thing I can think of.

**Comment by Kaydub00** [comment]
Yeah, I took that approach before but it's not exactly what I'm looking for. Thanks for the help.

**Comment by josteink** [comment]
Old issue is old. Closing.
