### ISSUE TITLE
Load on click only?

### ISSUE THREAD

**Issue by vtexperts** [KartikTalwar/gmail.js#544]
Question - can I load gmail.js on a click in my extension? instead of loading it on every email i open? 

Thanks

**Comment by josteink** [comment]
You can load gmail.js at any time you want, but I'm not sure I understand the question.

You typically only load gmail.js once, and keep a reference to that object which you keep using again and again. You certainly should not load it for every email opened.

To help eliminate some confusion, it might help if you provided a code-example for your use-case, and I can provide feedback on that.

**Comment by vtexperts** [comment]
Instead, I would like to privately share the solution that we have and possibly get some input.  Someone experienced, like you, I hope should be able to point out the problem.  I feel that my developer has no idea what the problem is and from what I know, gmail.js should not add 3-5 lag to my gmail. 

I'm looking someone "for hire" to do a quick analysis to help us understand the issue.

Let me know if @josteink  you could assist. You will be compensated for you time.

**Comment by josteink** [comment]
Sorry. I'm a paid full time developer, and I don't take freelance jobs.

**Comment by vtexperts** [comment]
Here's what I have:

Step 1: Check the gmail request and bind the "open_email" event: 
![step1](https://user-images.githubusercontent.com/17834854/50484426-0be89300-09b6-11e9-9c35-789d345e060c.png)

Step 2: Handle "open_email" event and notify corrensa that the event is triggered : 
![step2](https://user-images.githubusercontent.com/17834854/50484431-10ad4700-09b6-11e9-95c4-9e7ef1eb3d90.png)

Step 3: Get the email data from the email content : 
![step3](https://user-images.githubusercontent.com/17834854/50484435-12770a80-09b6-11e9-88c2-e833f8436089.png)

---

Any ideas what could be causing the lag?

**Comment by josteink** [comment]
From what I can tell, you do things mostly by the book.

1. You register the event (hopefully only once!)
2. You intercept the event.
3. You defer the *expensive* parts of the your event-handling logic until after Gmail.js has completed its event-cycle (via `setTimeout()`)
4. You try to fetch email-data about the currently open email (`adapter.gmail.get.displayed_email_data()`) via GmailJS XHR.

Unless you are registering the event multiple times, or gmail is somehow throttling your XHR-requests, there's nothing about this code which looks fundamentally wrong.

That said I have the following remarks:

* `adapter.gmail.get.email_data()` should be sufficient, and possibly cheaper.
* GmailJS XHR is going to be a source of complete breakage in 2019 when Google obsoletes old gmail, so if you rely on that, your extension will break and we can't fix it.
* I recommend migrating to `gmail.new.get.email_data()` which doesn't rely on XHR, returns data instantly and should be future proof once Google obsoletes old gmail.

Please note the following things about `gmail.new.get.email_data()`:

* It requires new-style GMail IDs.
* The data-format returned is different from `gmail.get.email_data()`. You will need to adapt your code.
* It is not backwards compatible with old Gmail.

This may not have been the answer you wanted, but hopefully it's still helpful.

**Comment by josteink** [comment]
Old issue is old. Closing.
