### ISSUE TITLE
is_conversation_view() is giving wrong result

### ISSUE THREAD

**Issue by shashikiran-im** [KartikTalwar/gmail.js#546]
Hi,

**Issue:**
api.check.is_conversation_view() is always returning "true" irrespective of conversation view is set to On / Off (It should return true if it is set to On, false otherwise).

Actually I had fixed the issue for new Gmail UI but I guess Gmail team had changed the response format so it is not reflecting in **api.tracker.globals[69];**

I am analyzing to fix this issue but if anybody had found solution then please do let me know.

Thanks in Advance,
Shashi

**Comment by josteink** [comment]
I cannot and will not merge that PR as it currently stands.

Please see my comment on your PR: https://github.com/KartikTalwar/gmail.js/pull/547#issuecomment-450861915

I advice you to close that PR, and reopen 2 new PRs, from 2 different branches in your repo.

**Comment by shashikiran-im** [comment]
Hi Josteink,

I had created pull request for is_conversation_view() not working issue.

NOTE: I will verify and generate new pull request for other issue (adding new feature) to know button labels settings. As i need to test and re-verify this new feature as gmail page evolved since then.

 Kindly request you to merge the pull request.

Thanks

**Comment by josteink** [comment]
Fixed by https://github.com/KartikTalwar/gmail.js/pull/548.
