### ISSUE TITLE
Searching through entire mailbox

### ISSUE THREAD

**Issue by botherder** [KartikTalwar/gmail.js#551]
I need to (on demand, so on a click of a button) search through an entire email inbox to find emails matching certain parameters. While `gmail.get.visible_emails()` is certainly a good start, I would need to crawl further back in the inbox.

Is there any suggested way I can do this using gmail.js? Or should I instead start looking at other ways?

**Comment by josteink** [comment]
> I need to (on demand, so on a click of a button) search through an entire email inbox to find emails matching certain parameters
> 
> ....
>
> Is there any suggested way I can do this using gmail.js?

It may be possible, but it won't be reliable, and in general it will cause you more troubles than it will solve.

I think using [the official Gmail Oauth API](https://developers.google.com/gmail/api/) is a better fit for this use-case.
