### ISSUE TITLE
Wrong typescript typings for GmailDomCompose

### ISSUE THREAD

**Issue by bagbee** [KartikTalwar/gmail.js#555]
version 0.9.1

currently in **GmailDomCompose** _recipients_, _to_, _cc_ and _bcc_ methods described like:
```
recipients(options?: { type: string, flat: boolean }): GmailEmailAddress[];
to(): string;
cc(): string;
bcc(): string;
```
but actually we have the next picture

![selection_011](https://user-images.githubusercontent.com/1095274/53290022-464c9180-37a7-11e9-945c-02c4075df2e4.png)

as you see _recipients_ returns object, not array of GmailEmailAddress
and _to_, _cc_ and _bcc_ returns jQuery object

**Comment by josteink** [comment]
You're absolutely correct. That *does* look wrong.

Would you care to send in a PR which fixes this? I'll be sure to get it reviewed and merged ASAP.

**Comment by bagbee** [comment]
sure, will send a PR
