### ISSUE TITLE
emailIdCache is partial after new compose

### ISSUE THREAD

**Issue by bastiendonjon** [KartikTalwar/gmail.js#561]
Hello,

api.cache.emailIdCache used by gmail.new.get.email_data is partial after new compose or reply.

If i compose new mail, i d'ont retry email_data of this compose, before "send_message" event.
I do not see the new email_id in cache.

Generally, I have to wait many secondes to see this email_id in cache. How i can get email_data in "before send_message" ? with new API ;-)

**Comment by josteink** [comment]
Hey there. Sorry about the slow reply.

If I understand your question properly:

* you've noticed that the email-cache used by api.new.get.email_data() does not always contain the info you need for a new compose or an email reply.
* you've noticed you can't get this data for in before send_message even.
* you have to wait many seconds (until "undo send email"-period is expired) before emails are real and show up in cache.

All this is true.

If you want to do anything to an email before "send_message", you cant do that directly with the new API. Sorry. And Gmail has made back-end changes which makes fixing that impossible.

You can read more about how the new APIs work in [this issue](https://github.com/KartikTalwar/gmail.js/issues/558), and also in the updated API documentation.

If you want to inspect emails before they are sent I suggest you hijack the "compose" button in the compose-window and intercept there before Gmail is actually sending the email.

Or if you only need to see what has happened afterwards, after send_message may have more parameters/arguments:

````javascript
gmail.observe.after("send_message", (...args) => {
    console.log("Email sent!", args);
});
````

**Comment by josteink** [comment]
Old issue is old. Closing.
