### ISSUE TITLE
load event not working

### ISSUE THREAD

**Issue by amk3011** [KartikTalwar/gmail.js#562]
I am using a newly released Gmail js of api_version (0.8.0) in my project but it is not firing a observe.on load event when Gmail loads. it is working fine with the old Gmail js file api_version (0.6.4). 

var gmail;

function refresh(f) {
  if( (/in/.test(document.readyState)) || (typeof Gmail === undefined) ) {
    setTimeout('refresh(' + f + ')', 100);
  } else {
    f();
  }
}

var main = function() {
  gmail = new Gmail();
  runChromeApp();

  setTimeout(function () {
      registerEvents();
  },5000);
};
refresh(main);

function registerEvents() {
  window.gmail.observe.on('load', ()=>{
      console.log('Gmail Js Loaded Successfully');

      //TODO : Register Further events here
      setTimeout( function() {
         
         

         console.log(gmail.get.user_email());  
        // console.log(gmail.get.search_query());
        // console.log(gmail.get.visible_emails());
        console.log(gmail.get.unread_inbox_emails());
      },1000);
  });
      
    
}

**Comment by josteink** [comment]
You are using legacy loading which is unreliable, and not really supported any more. 

Please try again using the NodeJS and bundled approach. Example here:
