### ISSUE TITLE
What is gmail.dom.inbox_content()?

### ISSUE THREAD

**Issue by ryanmclaughlin** [KartikTalwar/gmail.js#563]
There doesn't seem to be any documentation for it. I'm wanting to parse each email thread in the inbox.

**Comment by josteink** [comment]
From what I can tell (by sheer inspection) is that it returns the list-view of the email inbox.

It's listed in the README as an available function, but sadly not all functions are 100% documented.

> I'm wanting to parse each email thread in the inbox.

If so, it might be more apt to create an event for when GmailJS itself has parsed each email's content (as they are preloaded by Gmail itself).

We could do this by triggering an event from `api.tools.cache_email_data()`. Would that work for you?

Please note: There's no guarantee about the rate of emails being preloaded, nor that only the ones in the current view are being preloaded.

**Comment by josteink** [comment]
Oh. We already have an event for that! `"load_email_data"`.

Please try that one:

````javascript
gmail.observe.after("load_email_data", emails => console.log("EMAILS:", emails));
````

**Comment by ryanmclaughlin** [comment]
@josteink Awesome, thanks! I'll give `load_email_data` a go.
