### ISSUE TITLE
Is there any way to get the unread emails for the given time stamp?

### ISSUE THREAD

**Issue by amk3011** [KartikTalwar/gmail.js#568]
Hi there, 
I am creating an extension for gmail and I want to get the count of the unread emails for the particular day. For example, if I have got 10 emails in a day and I have read 5 emails from them then I should get the 5 emails as unread from that day only.

Is there any way to get this using gmail js?

**Comment by josteink** [comment]
Right now I don't think there is. Shouldn't be too hard though.

* You'll probably have to create a PR to get unread email (IDs) from the Inbox (feel free to make this a new function like `gmail.new.get.unread_email_ids()`
* Then use `gmail.new.get.email_data()` on those emails
* Finally aggregate and partition based on the email_data `timestamp` or `date`.

Good luck!

**Comment by josteink** [comment]
Old issue is old. Closing.
