### ISSUE TITLE
listen to sender_change while composing message

### ISSUE THREAD

**Issue by ericdude4** [KartikTalwar/gmail.js#583]
When multiple gmail accounts are added to gmail, it is possible to change the email address which is being used to send the email while an email is being composed.

Can we add a "sender_change" observable event? I have been trying, but I am having trouble finding the right class name to register the event handler to.

**Comment by josteink** [comment]
> Can we add a "sender_change" observable event?

In general, I'm never opposed to useful APIs, events or functions in GmailJS.

> I have been trying, but I am having trouble finding the right class name to register the event handler to.

That said, I won't implement APIs I'm not going to use myself, just for the sake of others. That's not how open-source works.

Open-source works when people are willing to scratch their own itch. So if you want this, you will have to build it yourself.

But if you do that, we will be happy to review, test and merge. Sounds good?

**Comment by ericdude4** [comment]
> Open-source works when people are willing to scratch their own itch. So if you want this, you will have to build it yourself.

Of course! Would you be able to point me somewhere to find incite as to how the CSS classes hang together in Gmail? It all seems so cryptic.

I will make a PR.

**Comment by josteink** [comment]
> Would you be able to point me somewhere to find incite as to how the CSS classes hang together in Gmail?

I don't think there's a reference guide. All code in Gmail.JS is reverse-engineered.

**Comment by josteink** [comment]
Old issue is old. Closing.
