### ISSUE TITLE
Compose attachments

### ISSUE THREAD

**Issue by PineappleShade** [KartikTalwar/gmail.js#605]
Hi,

I was wondering if there was a way for me to get the attachments of a compose object when I forward an email?

![image](https://user-images.githubusercontent.com/17995780/74862656-868f1300-531a-11ea-905a-2aef42fa0883.png)

Something like this?
```
gmail.observe.on("compose", function(compose, type) {
       compose.attachments;
});
```

Thank you.

**Comment by josteink** [comment]
The best way to "discover" what APIs are available is using a language like TypeScript.

gmail.js has almost full type-definitions for all APIs, so at any point in your code you will get correct auto-completions and can use them to navigate the API-space your are currently working with. It's really nice :smile: 

With that said, as you will discover if you do as I suggest, is that currently there is no support for any attachment-related functionality in the DOM compose API.

PRs welcome.

**Comment by PineappleShade** [comment]
Thank you.
