### ISSUE TITLE
Gmail removes the text I add

### ISSUE THREAD

**Issue by kotfarepra** [KartikTalwar/gmail.js#610]
Hello to all

I have this code that finds a link and then adds my text to that link 

````javascript
gmail.observe.on("load", () => {
    const userEmail = gmail.get.user_email();
    console.log("Hello, " + userEmail + ". This is your extension talking!");

    gmail.observe.on("view_email", (domEmail) => {
        console.log("Looking at email:", domEmail);
        const emailData = gmail.new.get.email_data(domEmail);
        console.log("Email data:", emailData);
		
		//setTimeout(function(){ 
	
			var addTextBelow = jQuery("a:contains('Hello dear')");
			addTextBelow.css('color','red')
			addTextBelow.parent().parent().append('My custom text');

		//}, 1000);
		
    });
});
````

It works the first half-second , then the text "My custom text" gets removed. But if I go back to the main list of emails and then back to that email it shows OK and doesn't go away. 
Seems like my code is being executed OK then some function  re-renders the email at the first time that I open that email. If i open that email for 2nd/3rd/4th time my text shows ok. Im presuming maybe Gmail is doing a re-render for the emails that I open the first time.

I even tried with setTimeout but its the same. 
Any idea how to make or  for what should I observe ( instead of load ) so that I dont have to do :
- open the email first time 
- go back to all email list
- go to back to the specific email 

Thank you

**Comment by josteink** [comment]
> It works the first half-second , then the text "My custom text" gets removed. But if I go back to the main list of emails and then back to that email it shows OK and doesn't go away.

As documented in the readme-file:

> *view_email - When an individual email is loaded within a conversation thread. It's worth noting this event is only triggered when the email is actually rendered in the DOM. Gmail tends to cache the rendered emails, **so it should not be expected to fire reliably for every viewing of the same email. It will most likely fire once, for the initial and possibly only rendering.**

If you need the changes to remain more permanent, you need to engineer a different solution to your problem.

**Comment by Crazyalien666** [comment]
> Hello to all
> 
> I have this code that finds a link and then adds my text to that link
> 
> ```js
> gmail.observe.on("load", () => {
>     const userEmail = gmail.get.user_email();
>     console.log("Hello, " + userEmail + ". This is your extension talking!");
> 
>     gmail.observe.on("view_email", (domEmail) => {
>         console.log("Looking at email:", domEmail);
>         const emailData = gmail.new.get.email_data(domEmail);
>         console.log("Email data:", emailData);
> 		
> 		//setTimeout(function(){ 
> 	
> 			var addTextBelow = jQuery("a:contains('Hello dear')");
> 			addTextBelow.css('color','red')
> 			addTextBelow.parent().parent().append('My custom text');
> 
> 		//}, 1000);
> 		
>     });
> });
> ```
> 
> It works the first half-second , then the text "My custom text" gets removed. But if I go back to the main list of emails and then back to that email it shows OK and doesn't go away.
> Seems like my code is being executed OK then some function re-renders the email at the first time that I open that email. If i open that email for 2nd/3rd/4th time my text shows ok. Im presuming maybe Gmail is doing a re-render for the emails that I open the first time.
> 
> I even tried with setTimeout but its the same.
> Any idea how to make or for what should I observe ( instead of load ) so that I dont have to do :
> 
> * open the email first time
> * go back to all email list
> * go to back to the specific email
> 
> Thank you

fuck u

**Comment by kotfarepra** [comment]
Hi there, would then be a way to delete the cache ?
sorry if I sound so "out of water" but its a big script and never dealt with gmail 

Thank you in advance

**Comment by josteink** [comment]
We don't know how the cache works and do t have any APIs for that. Sorry.
