### ISSUE TITLE
gmail.observe.on("send_message", function(url, body, data, xhr)

### ISSUE THREAD

**Issue by egala8** [KartikTalwar/gmail.js#611]
Hello All,
I hope you all are keeping safe during these times.
I am using the gmail.observe.on to get the body of the sent message to fetch the attachments in a chrome extension.
I am doing it by manipulating the body object returned from the event. I am new to gmail extension development. Can someone experienced please let me know whether this method is future proof.
I look forward to hearing from you.
 
`gmail.observe.on("send_message", function(url, body, data, xhr) {`
	  
 		`console.log(body);`
 ` });`

**Comment by josteink** [comment]
For accessing attachment-information, I recommend obtaining a reference to the sent email, and then using the regular `get.new.email_data(id).attachments` API:

![Screenshot-2020 04 27-08 58 42](https://user-images.githubusercontent.com/411338/80342932-535e8800-8865-11ea-90ec-d53aef8cf59f.png)

**Comment by egala8** [comment]
Hello Jostein,

Thanks for that. I actually realized that the attachments can also be accessed from the data object. 

`data.attachments[i]['url'].`

I am trying to get the attachments of a sent email.

Can you please briefly let me know how to get started with a chrome extension without modifying the original extension file. Thank you!

**Comment by josteink** [comment]
I’m not sure I understand. Obviously you’ll have to make changes to the extension-file to create your own extension. 

The boilerplate-project linked in the README should be a simple and safe project to start with. 

Otherwise the internet is full of documentation on how to create non-gmail-specific WebExtensions. Everything mentioned there still applies here.

**Comment by egala8** [comment]
Is there a way I can keep the original file untouched. What I have done so far is;
followed the procedure in [here](https://github.com/josteink/gmailjs-node-boilerplate). I am editing the extension file in the dist folder after running npm run build.
My question was is there a way to keep the file in the dist folder unchanged when creating the extension.

**Comment by josteink** [comment]
What you are doing is not practical, nor supported. You are *supposed* to edit the `src/extension.js` file and rebuild (and thus create a new dist/extension.js) to create your extension.

Why do you insist on not editing the file directly, when that is absolutely the simplest approach?

**Comment by josteink** [comment]
Either way, I'm closing this issue, as it's not an issue with gmail-js, and the original question (regarding attachments) have been resolved.
