### ISSUE TITLE
Problem in gmail.js or in gmail-chrome-extension-boilerplate

### ISSUE THREAD

**Issue by albertly** [KartikTalwar/gmail.js#612]
I took project from gmail-chrome-extension-boilerplate. Replaced gmail.js from this repository (as suggested) and replaced jquery from this repository version (first I tried with original one, the same result).

After adding extension in my Chrome I've got errors:

`The service worker navigation preload request was cancelled before 'preloadResponse' settled. If you intend to use 'preloadResponse', use waitUntil() or respondWith() to wait for the promise to settle.
The service worker navigation preload request was cancelled before 'preloadResponse' settled. If you intend to use 'preloadResponse', use waitUntil() or respondWith() to wait for the promise to settle.
The service worker navigation preload request was cancelled before 'preloadResponse' settled. If you intend to use 'preloadResponse', use waitUntil() or respondWith() to wait for the promise to settle.
The service worker navigation preload request was cancelled before 'preloadResponse' settled. If you intend to use 'preloadResponse', use waitUntil() or respondWith() to wait for the promise to settle.
The service worker navigation preload request was cancelled before 'preloadResponse' settled. If you intend to use 'preloadResponse', use waitUntil() or respondWith() to wait for the promise to settle.
The service worker navigation preload request was cancelled before 'preloadResponse' settled. If you intend to use 'preloadResponse', use waitUntil() or respondWith() to wait for the promise to settle.
/mail/u/0/#inbox:1 [DOM] Found 2 elements with non-unique id #null: (More info: https://goo.gl/9p2vKq) <form id=​"null" action=​"?ui=html&zy=s" method=​"post">​…​</form>​ <form id=​"null" action=​"?ui=html&zy=d" method=​"post">​…​</form>​
m=a:1332 Deprecated API for given entry type.
Wvd.activate @ m=a:1332
VM50:5 Hello, albert.lyubarsky@gmail.com
(index):94 Uncaught (in promise) Error: E
    at Hd.i ((index):94)
    at m=a:1208
    at (index):136
    at d (m=b:1094)
DevTools failed to load SourceMap: Could not load content for chrome-extension://gighmmpiobklfepjocnamgkkbiglidom/include.postload.js.map: HTTP error: status code 404, net::ERR_UNKNOWN_URL_SCHEME
m=b:1094 Uncaught a8a {message: "Error in protected function: x`a6jdv`2", cause: Error: x`a6jdv`2
    at https://mail.google.com/mail/u/0/:86:44
    at d (https://mail.google.com/m…, stack: "Error: x`a6jdv`2↵    at https://mail.google.com/ma…)↵    at https://mail.google.com/mail/u/0/:86:432"}
d @ m=b:1094
setTimeout (async)
d.<computed> @ m=b:1095
WIa @ m=b:268
Mp.IZa @ m=b:1104
(anonymous) @ m=b:280
Gp.wa @ m=b:271
Promise.then (async)
Gp.ha @ m=b:271
Gp @ m=b:271
lJa @ m=b:279
Mp.lH @ m=b:278
Mp.Znd @ m=b:278
l @ m=b:279
m=b:1094 Uncaught a8a {message: "Error in protected function: x`VWNrn`2", cause: Error: x`VWNrn`2
    at https://mail.google.com/mail/u/0/:86:44
    at d (https://mail.google.com/m…, stack: "Error: x`VWNrn`2↵    at https://mail.google.com/ma…)↵    at https://mail.google.com/mail/u/0/:86:432"}
d @ m=b:1094
setTimeout (async)
d.<computed> @ m=b:1095
WIa @ m=b:268
Mp.IZa @ m=b:1104
(anonymous) @ m=b:280
Gp.wa @ m=b:271
Promise.then (async)
Gp.ha @ m=b:271
Gp @ m=b:271
lJa @ m=b:279
Mp.lH @ m=b:278
Mp.Znd @ m=b:278
l @ m=b:279
m=b:1094 Uncaught a8a {message: "Error in protected function: x`Cl6csf`2", cause: Error: x`Cl6csf`2
    at https://mail.google.com/mail/u/0/:86:44
    at d (https://mail.google.com/…, stack: "Error: x`Cl6csf`2↵    at https://mail.google.com/m…)↵    at https://mail.google.com/mail/u/0/:86:432"}
d @ m=b:1094
setTimeout (async)
d.<computed> @ m=b:1095
WIa @ m=b:268
Mp.IZa @ m=b:1104
(anonymous) @ m=b:280
Gp.wa @ m=b:271
Promise.then (async)
Gp.ha @ m=b:271
Gp @ m=b:271
lJa @ m=b:279
Mp.lH @ m=b:278
Mp.Znd @ m=b:278
l @ m=b:279
m=b:1094 Uncaught a8a {message: "Error in protected function: Cannot read property 'style' of null", cause: TypeError: Cannot read property 'style' of null
    at onLoadTimeout (https://mail.google.com/mail/…, stack: "TypeError: Cannot read property 'style' of null↵  …=AHGWq9CKXlQ4uQ1DUkFM-I0jqul9KV0ZDg/m=b:1094:137)"}
d @ m=b:1094
setTimeout (async)
d.<computed> @ m=b:1095
onLoadTimeout @ (index):123

`
What's going on ? Plz, help.
[mail.google.com-1589779942244.log](https://github.com/KartikTalwar/gmail.js/files/4642183/mail.google.com-1589779942244.log)

**Comment by albertly** [comment]
![image](https://user-images.githubusercontent.com/3274890/82177769-33aa0500-98e3-11ea-8d0b-13b6e1773de8.png)

**Comment by albertly** [comment]
Not closed

**Comment by josteink** [comment]
Without having the actual project and actual failing code there's not much I can do.

Can you create a minimal fork of the boilerplate project which demonstrates this error?

**Comment by albertly** [comment]
[gmail-chrome.zip](https://github.com/KartikTalwar/gmail.js/files/4644042/gmail-chrome.zip)
Here is it.

**Comment by Fabi1Sc** [comment]
Hey, i look at your project.
I think you could look at https://github.com/josteink/gmailjs-node-boilerplate to have a better implementation.

**Comment by josteink** [comment]
Oh. You used the OLD boilerplate?

That’s unfortunately obsolete and deprecated now and no longer supported. 

Using the repo suggested above should work though.
