### ISSUE TITLE
Gmail.check.is_inside_email() seem to not work anymore

### ISSUE THREAD

**Issue by yevhene** [KartikTalwar/gmail.js#620]
There are no items matching `.ii.gt .a3s.aXjCH` selector anymore on the page

**Comment by josteink** [comment]
Hey there and thanks for reporting in.

I just did some quick testing in the browser and it seems you are correct. Just relaxing the selector slightly, down to to `".ii.gt .a3s"` instead seems to work better now.

Would you be willing to do some testing and see if that works better on your end too? Or if there are unexpected side-effects of such a change?

**Comment by yevhene** [comment]
@josteink Work for me
