### ISSUE TITLE
api.dom.email doesn't work with new-style id

### ISSUE THREAD

**Issue by rickardnorlander** [KartikTalwar/gmail.js#625]
This was needed to use api.dom.email in email threads. I managed to work around it by getting the element myself and feeding it to api.dom.email, but ideally it would be supported in the library. For reference my workaround code was
```
const email_element = document.querySelector("div.adn[data-message-id=" + email_id.replace("msg-f:", "\\#msg-f\\:") + "]")
const dom_email = gmail.dom.email(email_element);
```

**Comment by josteink** [comment]
You're absolutely right. Looking at the code, it clearly assumes old-style ID.

![image](https://user-images.githubusercontent.com/411338/97533951-76efc000-19b9-11eb-9e46-2dd5ff0bad9c.png)

As you show, it should be pretty easy to fix.

If you make a PR for this, I'll try to get this merged pretty quickly. If not... You make have to wait until next week :)

**Comment by josteink** [comment]
I've pushed some changes to git master to make the ergonomics of using this function better.

Please note that while it now supports new-style IDs as an input, the `api.dom.email().id`-property still provides the legacy-ID for compatibility reasons.

Please let me know if this works for you.

**Comment by rickardnorlander** [comment]
Thanks, yup that did the trick!

**Comment by josteink** [comment]
Pushed to NPM as version `1.0.5`.
