### ISSUE TITLE
getting the email sender

### ISSUE THREAD

**Issue by Suphikoira** [KartikTalwar/gmail.js#630]
I am trying to parse the sender information of the displayed email. any idea?

as string: 

"Received: from smtp.github.com (out-17.smtp.github.com. [192.30.252.221])"

**Comment by Suphikoira** [comment]
just figured it out that I was using an old version of gmail.js

gmail.get.email_source("email_id");  works well.

**Comment by josteink** [comment]
gmail.new.email_data() is probably better for this purpose.

**Comment by josteink** [comment]
Disregard my previous comment. I misread the problem, and your solution is indeed the correct one. 

I would advice using one of the async versions though.
