### ISSUE TITLE
gmail.compose.start_compose() does not pop the compose window

### ISSUE THREAD

**Issue by anuragphadke** [KartikTalwar/gmail.js#633]
Hi,
I successfully installed the `gmailjs-node-boilerplate` chrome extension, the console msg "This is your extension talking" shows up w/o any issues.
However,
```
gmail.compose.start_compose()
returns:
true
```

I don't see any compose window neither do I see anything in drafts folder. 

Any idea why the compose window isn't showing up? Filed https://github.com/josteink/gmailjs-node-boilerplate/issues/20 but @josteink suggested that it might be an issue on gmail.js side of things.

**Comment by anuragphadke** [comment]
bump ^ is it just me that's having this issue?

**Comment by josteink** [comment]
I can confirm this appears broken in latest version of Gmail & GmailJS.

**Comment by josteink** [comment]
This should be fixed in latest git master now. Can you verify that it works for you too?

If so, I can publish a new npm-release for that fix.

**Comment by josteink** [comment]
Released in version 1.0.6.
