### ISSUE TITLE
Refresh email thread manually

### ISSUE THREAD

**Issue by rami14c** [KartikTalwar/gmail.js#634]
I've opened one email and sent a reply using my customized send button(I'm not using gmail send button). Replied email is coming but it is not showing up in same thread until I refresh the screen. any thoughts here.

I wanted to refresh the email thread to show the newly added reply message.

**Comment by josteink** [comment]
> using my customized send button(I'm not using gmail send button)

How are you triggering the send? What happens (as an experiment) if you use the gmail send button? Does *that* behave as it should?

**Comment by rami14c** [comment]
> > using my customized send button(I'm not using gmail send button)
> 
> How are you triggering the send? What happens (as an experiment) if you use the gmail send button? Does _that_ behave as it should?

I have customized the reply window, this customization will enable another features which are similar to my another application. So when click on customized send button, it will make a API call to my application, from there we are sending an email.
gmail send will not work for me in this case.

**Comment by josteink** [comment]
So basically you are doing data-interactions with Gmail outside the Gmail web-app?

That's clearly outside the scope of GmailJS, but you may be able to work around this if you `await` your custom send, and re-set the location (which contains the email thread id) once you know the email has been sent?

**Comment by rami14c** [comment]
Thanks for the idea. It is working with resetting document.location.
