### ISSUE TITLE
" gmail.tracker**.xhr_open** " what does this line do?

### ISSUE THREAD

**Issue by Aryan-desale** [KartikTalwar/gmail.js#647]
I don't have any idea what does this line of code does.
Can somebody please help me with this?

**Comment by josteink** [comment]
This is an gmail.js internal implementation detail.

Why are you asking about it? What are you trying to do?

**Comment by Aryan-desale** [comment]
Is it a tracker that tracks the mail? Or is it something else.

**Comment by josteink** [comment]
It's part of an internal mechanism which allows gmail.js to work. It doesn't "track" anything externally to gmail.js.

**Comment by josteink** [comment]
Considering this a question and question answered. Closing :)
