### ISSUE TITLE
Click event not getting fired for button added using gmail.tools.add_toolbar_button()

### ISSUE THREAD

**Issue by shashikiran-im** [KartikTalwar/gmail.js#648]
Hi GmailJS Team,

I observed that gmail.tools.add_toolbar_button() Click callback event is not getting fired from couples of days now.

Could anyone confim  if you  can reproduce the issue.

Could please let me know if anyone found solution for the same.

Please do replay.

Thanks in Advance

**Comment by josteink** [comment]
I don't use that particular API in my extension, but I used `gmail.tools.add_compose_button()` and I can confirm I'm experiencing the same there.

No clicking is happening, and no errors are showing up in the console either. Will have to debug this.

**Comment by josteink** [comment]
It seems Gmail has made some extensive changes w.r.t. how it handles click-events inside the DOM.

Trying to add a simple toolbar_button, I can see that it does indeed have a `onclick`-event registered, but the event does never get triggered when clicking the button.

Instead clicking the button triggers some huuuge Gmail page-global event-handler which somehow ends up preventing the rest of the events from unfolding.

It's super-hacky, but for now I seem to be able to bypass this click-jacking (of the compose-button)... by click-jacking the click-jacking itself.

Example code below:

````javascript
// prevent gmail jacking our click-events!
window.addEventListener("click", (e) => {
    console.log(e);

    const realTarget = e.path[0];
    const gmailJsButton = realTarget.querySelector(".gmailjscomposebutton");
    if (gmailJsButton) {
        gmailJsButton.click();
    }
});
````

I'll see if I can "productionify" this work around later, but for now I have other things which needs my immediate attention.

**Comment by josteink** [comment]
I've made a tentative fix in gmail-js version 1.0.7 now available on npmjs.com.

Let me know if that works for you.

**Comment by josteink** [comment]
After putting this in production, I've gotten feedback that buttons added using the compose API (`gmail.tools.add_compose_button`) gets invoked for some of the *other* gmail-buttons in the toolbar, among others:

* hyperlink
* add attachment from google drive
* add image

This seems like a clear regression caused by the previous fix, so depending on your use-case 1.0.7/1.0.8 may or may not be a viable fix or upgrade for 1.0.6.

**Comment by ATheSecretCocktail** [comment]
Not sure if this is related to this, but I have noticed over the last few days the click event is firing more than expected. I have found that when you click into the empty space in the toolbar (see image). It also fires if you are holding down the mouse (to highlight text for example) and it gets dragged into that same area. 
![image](https://user-images.githubusercontent.com/84815195/120865622-6493c100-c55c-11eb-9f48-929d4e70aaa0.png)

**Comment by josteink** [comment]
Can you reproduce this in v1.0.10?

**Comment by josteink** [comment]
From the readme in the boilerplate:

![image](https://user-images.githubusercontent.com/411338/121147536-3c001580-c841-11eb-818a-88f1bdf2951f.png)

If you do that, reload the extension in your browser and can still reproduce, we might still have an issue. That said, I just tested using latest and I can not reproduce here.

**Comment by ATheSecretCocktail** [comment]
Thank you for your prompt response and instructions! Sorry for the delay. I was out of the office. That has seemed to work! 

Thanks!

**Comment by josteink** [comment]
Righto. Considering this closed then!
