### ISSUE TITLE
How i can get selected emails?

### ISSUE THREAD

**Issue by artyRay12** [KartikTalwar/gmail.js#650]
Cant find method for selected emails, pls help.
Thx

**Comment by josteink** [comment]
Check readme. It’s there in the DOM section iirc.

**Comment by artyRay12** [comment]
gmail.get.selected_emails_data() old version, readme say that i should use gmail.new.get.* now, but i can't find any. I check DOM method and cant find any too.
sry for my bad englsh.

**Comment by josteink** [comment]
Oh well. I’m sure there is a DOM way to do it, possibly discussed in now closed issues. 

Search around?

Also: PRs welcome 🙂

**Comment by artyRay12** [comment]
still cant find, tell analog of "api.get.selected_emails_data_async" pls.

**Comment by josteink** [comment]
1. Use Dom to find selected emails
2. Use api.new.get.email_data() for those emails.

**Comment by artyRay12** [comment]
I get email dom element with checking 
const [email] = $(table .x7), i get array with length  = 1
then i use const emailData = api.new.get.email_data(email); 
but emailData is undefined.
i find place where i get undefined, screen below, function tried extract data from object by id as key, but it doesnt exist.
![image](https://user-images.githubusercontent.com/39522767/127895089-868d0c0d-69d5-4662-8978-c0df4bc921f1.png);
what im doing wrong.
im sry if i stupid

**Comment by josteink** [comment]
Looking at it in my browser, I notice these are not emails, they are *threads*. This is semantically different, and means you need to use different APIs.

Anyhow: You first need to first ensure you are selecting the right elements. From what I can see, you were on track, but not entirely. We can select even more useful elements to obtain information about the currently selected email-rows:

````javascript
var threadElems = document.querySelectorAll("table .x7 span[data-thread-id]");
````

We the need to extract the actual `thread-id` property from these elements. Note: We may get the same thread-id more than once.

````javascript
var threadIds=[];
for (let elem of threadElems) {
    var threadId = elem.dataset.threadId;
    if (threadId[0] === "#") threadId = threadId.substring(1); // filter #-prefix. Should really be done in gmail.js...
    threadIds.push(threadId);
}
````

Then using `threadIds` we can obtain information about these emails:

````javascript
for (let threadId of threadIds) {
    var threadData = gmail.new.get.thread_data(threadId);
    console.log(threadData);
}
```` 

And that should get you something like this to work with:

![image](https://user-images.githubusercontent.com/411338/127906522-3a4b202b-65de-49e3-ae05-be46e7305f4c.png)

**Comment by artyRay12** [comment]
Thx very much, its work, but sometimes i get undefined from get.thread_data(threadId), can i update thread_cache?)

**Comment by josteink** [comment]
You can't. It is passively updated whenever Gmail fetched information about those threads. If you really *need* that info, you need to initiate a navigation to that thread first, to ensure gmail actually fetches the data.

If you still can't get it, it might be part of the early-load preamble, and you need to make sure Gmail.js is loaded *really* early in the page-load cycle. See how to do that in [the boilerplate](https://github.com/josteink/gmailjs-node-boilerplate) project for information about how that should be done.
