### ISSUE TITLE
Newbie questions

### ISSUE THREAD

**Issue by evagelos21** [KartikTalwar/gmail.js#651]
Hi to all,
i want to create a chrome extension in order to read the email body and if the body contains specific words i want to highlight this email.
Am I in the right corner?
If so, how can i start?
I am in the very beginning in chrome extension, byt so far i have created 3-4 for test purposes

Thanks in advance.

**Comment by josteink** [comment]
Yes. Look at the linked boilerplate repo for example.

**Comment by evagelos21** [comment]
I am trying from the example "https://camo.githubusercontent.com/7a72794f38fdb4718946c5fc52ecc18e7c47bbdae8ff4dafaec288d9ed163195/68747470733a2f2f662e636c6f75642e6769746875622e636f6d2f6173736574732f3436313730322f313632383938342f38336464623235302d353732382d313165332d396462632d3730613133633262656362302e4a5047"

but an error message appears just after document.getElementsByTagName('body')[0].appendChild(jq);  (3rd line)

**Comment by josteink** [comment]
Don’t use that one. 

Use the linked boilerplate project.

**Comment by evagelos21** [comment]
Sorry but i cannot find it.

**Comment by josteink** [comment]
It’s right there linked in the readme. 

![953AE643-A03E-43F1-83D9-4616E7623C03](https://user-images.githubusercontent.com/411338/130248917-36fb6714-761c-47bc-973f-f3bb7ea70404.png)

There’s no support for this library. If you can’t read a readme, this project is not for you 🙂

**Comment by evagelos21** [comment]
chrome looking for
  "dist/gmailJsLoader.js" and  "dist/extension.js"

Where can i find them?


    "web_accessible_resources": [
        "dist/gmailJsLoader.js",
        "dist/extension.js"
    ],

**Comment by evagelos21** [comment]
ok,
now i have error :
gmailJsLoader.js:13 Uncaught ReferenceError: require is not defined
    at gmailJsLoader.js:13

and 

extension.js:3 Uncaught ReferenceError: require is not defined
    at extension.js:3

**Comment by josteink** [comment]
Learn some NodeJS. Until then, this library is not for you. 

Not a GmailJs error. Closing.
