### ISSUE TITLE
Lost the ability to get to, cc and bcc fields from email compose

### ISSUE THREAD

**Issue by dbadea-sugarcrm** [KartikTalwar/gmail.js#654]
It looks like gmail did an update, and changed the compose window.
composeEl.to() will not give an error
<img width="510" alt="Screenshot 2021-10-22 at 12 52 07" src="https://user-images.githubusercontent.com/40794294/138476631-20dccc32-a76d-4970-9fba-0be61b989c5b.png">

This also means that gmail.observe.on('recipient_change' no longer triggers

Any workaround for this, or fix in the works?

**Comment by josteink** [comment]
> @josteink So I added "recipient_change_new" event to dom observers, and it works fine, but needs code change on user's side. What do you think, how we can do that "recipient_change" will work both with old and new Gmail?

I noticed that and I'm not sure I like it.

Maybe we could find some way to make sure both events report under the same name?

**Comment by huksley** [comment]
> I noticed that and I'm not sure I like it.
Yes, that was suboptimal. Now it is one event. Can someone test it?

**Comment by huksley** [comment]
Also fixed copy paste of email address from elsewhere (it was producing error)

**Comment by josteink** [comment]
Fix should be available in new release `gmail-js@1.0.15`. Thanks @huksley !
