### ISSUE TITLE
gmail.observe.before('send_message') Uncaught (in promise) A server error has occurred.

### ISSUE THREAD

**Issue by anuragphadke** [KartikTalwar/gmail.js#665]
gmail.observe.before('send_message', function(url, body, data, xhr){
      console.log("hi..:", body)
})

Adding an observe on `before` returns:
```
Uncaught (in promise) A server error has occurred.
```

How to reproduce:

Load gmailjs as described in README.md
--------------
// {inject jquery.js} by copy pasting this in your console
var jq = document.createElement('script');
jq.src = "https://ajax.googleapis.com/ajax/libs/jquery/1.10.2/jquery.min.js";
document.getElementsByTagName('body')[0].appendChild(jq);

// {inject gmail.js} by copy pasting gmail.js contents or via url like jquery above
// var Gmail = {.....} // paste gmail.js code here

// start using!
// you can also pass in a reference to jQuery upon init - Gmail(localJQuery)
var gmail = Gmail();
gmail.get.user_email();

gmail.observe.before('send_message', function(url, body, data, xhr){
      console.log("hi..:", body)
})

compose a message and press send..
devtools shows the error. (screenshot attached)
![image](https://user-images.githubusercontent.com/349486/152664658-383f6710-c181-44bd-8816-247bd91e6d8c.png)

**Comment by josteink** [comment]
Don’t use that technique. It’s obsolete. 

Use the technique shown in the linked boilerplate.

**Comment by josteink** [comment]
I’ve now removed this section from the readme to avoid confusion 🙂

**Comment by anuragphadke** [comment]
The Readme is massive, is there a specific gist you can point towards? 

I’ll submit a PR if I can find it and get it to work….

**Comment by anuragphadke** [comment]
@josteink : I wrote a small gist to reproduce the issue, details at:
https://gist.github.com/anuragphadke/f0a599af4c4d82d1a327600456e8a92d

Ant pointers on what could be going wrong here?

**Comment by josteink** [comment]
The gmailjs boilerplate linked at the top of the readme. 

https://github.com/josteink/gmailjs-node-boilerplate

**Comment by josteink** [comment]
The gmailjs boilerplate linked at the top of the readme. 

https://github.com/josteink/gmailjs-node-boilerplate

What you’re doing is NOT supported and is not going to work. Your gist is based on the obsolete instructions I explicitly removed. 

Use the boilerplate instead and let me know if that solves your issue.

**Comment by anuragphadke** [comment]
@josteink : thx for the quick reply, is there a snippet / pointer for `observe.before()` events?
The code at https://github.com/josteink/gmailjs-node-boilerplate/blob/master/src/extension.js has `observe.on()` events that  work without issues. 

The observe.before() code snippet is from README.md at https://github.com/KartikTalwar/gmail.js/
<img width="881" alt="before" src="https://user-images.githubusercontent.com/349486/152693068-75e46f94-c466-4d31-9968-6eb780ec24c4.png">

Apologies if I am missing something obvious..

**Comment by josteink** [comment]
Modification of sent messages have not really been well supported since the launch of “new” Gmail a few years back. 

That example is surely dated. 🙂

**Comment by josteink** [comment]
Old issue is old. Closing! :)
