### ISSUE TITLE
Attachments from fd_embedded_json are not correctly parsed

### ISSUE THREAD

**Issue by onestep** [KartikTalwar/gmail.js#673]
**Prerequisites:**
- Account with `_GM_setData` preload.

**Steps to reproduce:**
1. open Inbox folder
2. receive email with attachment from some another account
3. reload page
4. navigate to new received email

**Actual result:**
Attachments data are processed incorrectly: attachment_id is `"a"`, other properties are `undefined`.

**Comment by onestep** [comment]
I've opened a pull request #674 with a fix. I decided to keep `parse_fd_attachments` as is, but it can be renamed to `parse_fd_request_payload_attachments` if needed.

**Comment by josteink** [comment]
Fixed in #673 and published on npmjs as v1.0.18.
