### ISSUE TITLE
Does gmail.new.get.email_data() works only on emails ID what is in DOM?

### ISSUE THREAD

**Issue by DainisVerdins** [KartikTalwar/gmail.js#681]
I have message id example `msg-a:r-7566937225308457080` of existing msg what is stored in mail email.
I want to get all info about email with this id. But after calling `gmail.new.get.email_data()` in returns empty object.

library is "connected "
my code 
```
console.log("Current_email,",gmail.get.user_email())
            var id = 'msg-a:r-7566937225308457080';
            var userId = gmail.get.user_email();
            let tmp = gmail.new.get.email_data(id);
            console.log("ss",ss);//returns null
```
Just in case, proof what this email at that id exist  I get it from gmail api test stand [link](https://developers.google.com/gmail/api/reference/rest/v1/users.messages/get?apix_params=%7B%22userId%22%3A%22dverdins%40cirrusinsight.com%22%2C%22id%22%3A%22msg-a%3Ar-7566937225308457080%22%7D).
![image](https://user-images.githubusercontent.com/55252915/165099238-8330d7d6-817d-40e1-adba-13ab90e88e40.png)

**Comment by josteink** [comment]
We can only return what is already in the cache. 

As a workaround, you can try force-navigate the user to that email to bring its email-data into the cache?

Never tried myself, but sounds like something which could work.

**Comment by DainisVerdins** [comment]
@josteink Any suggestions to get data of specific email? Should then I use then gmail api javascript library?
