### ISSUE TITLE
Ordering of compose vs load events differs based on page

### ISSUE THREAD

**Issue by cancan101** [KartikTalwar/gmail.js#688]
The ordering of the `compose` and `load` events differs based on whether I am on the inbox page or an email thread page. On the email page the compose event fires first. On the inbox the load event fires first:
```ts
gmail.observe.on('compose', () => {console.log('compose')});
gmail.observe.on('load', () => {console.log('load')});
```
I had been putting all of my hooks within load (ie waiting for load to fire, [consistent with the boilerplate](https://github.com/josteink/gmailjs-node-boilerplate/blob/381cb1190921bc49c1983c35c36a7eb7bbd014c7/src/extension.js#L18-L31)); however, that is problematic as I am dropping the compose event if I am on the email page.

**Comment by josteink** [comment]
If that’s so, and there’s no other I’ll effects, one might as well register all event-handlers at once. 

PR to update the boilerplate is welcome 🙂

**Comment by josteink** [comment]
Seconding that. Looking at the code itself, I can't see any harm just adding all subscriptions/events right away.

It might have been a limitation related to the earlier implementation before I implemented nested XHR interception?

**Comment by josteink** [comment]
Recommendation removed from readme.

Issue closed? :smile:
