### ISSUE TITLE
Add gmail.js to bower

### ISSUE THREAD

**Issue by tejasmanohar** [KartikTalwar/gmail.js#69]
Maybe you should create a bower package?

**Comment by r00tat** [comment]
Hi Karik,

I think it's still a good idea to include gmail.js in bower. If you want to bundle all required files in your extension it's hard to update them, if they are not in any repository. With bower you would be able to simply update your requirements with `bower update`

**Comment by r00tat** [comment]
BTW: I found a workaround:

If you add the raw link to the bower dependencies, it will automatically download the latest version and deploy it to gmail/index.js:

```
  "dependencies": {
    "jquery": "~2.1.4",
    "gmail": "https://raw.githubusercontent.com/KartikTalwar/gmail.js/master/src/gmail.js"
  }
```
