### ISSUE TITLE
[Question] Set/replace email's subject when opened from inbox view

### ISSUE THREAD

**Issue by GTP95** [KartikTalwar/gmail.js#709]
Greetings,

I'm trying to modify the data shown when a certain kind of email is opened from inbox view. After getting a reference to the email's DOM using the dedicated observer like so
```JS
gmail.observe.on("view_email", (domEmail) => {
[my code here]
}
);
```
I can change the email's body with
```JS
domEmail.body(bodyAsText);
```
But I'm failing to do the same for the email's subject. I tried both `domEmail.email_subject(subject)` and `domEmail.subject(subject)` but in both cases I get a TypeError saying that what I'm calling isn't a function. Is there a way to set or modify an email's subject?
Thank you for your help,

GTP

**Comment by josteink** [comment]
Checking the source, the following might work?

````js
const subjectNode = api.dom.email_subject();
subjectNode.text("New subject");
`````

**Comment by GTP95** [comment]
I think I'm not calling the right method:
```JS
const subjectNode = domEmail.email_subject();
subjectNode.text(subject);
```
gives `TypeError: domEmail.email_subject is not a function`.
```JS
const subjectNode = api.dom.email_subject();
subjectNode.text(subject);
```
gives `ReferenceError: api is not defined` and
```JS
const subjectNode = gmail.api.dom.email_subject();
subjectNode.text(subject);
```
gives `TypeError: Cannot read properties of undefined (reading 'dom')`.
How should I call the right method?

Thank you for your help,

GTP

**Comment by GTP95** [comment]
Never mind, I found that in my case I have to call it like this: `const subjectNode = gmail.dom.email_subject();`. Thank you for your help.
