### ISSUE TITLE
compose.recipients() does not work when PeopleKit suggestions are displayed

### ISSUE THREAD

**Issue by onestep** [KartikTalwar/gmail.js#713]
**Steps to reproduce:**
1. open Gmail for PeopleKit-enabled account
2. open new compose window, add some recipients you used in previous emails and wait for suggestion (unfortunately I don't know the exact way to force suggestions - most likely if you frequently send emails to the same three contacts, when you add two in the new compose, Gmail will suggest third)
![image](https://user-images.githubusercontent.com/1419318/182607281-dca2af9d-b702-491d-8f82-30dae94b38db.png)
3. try to read `gmail.dom.composes()[0].recipients()`

**Expected result:**
* object with recipients info is returned

**Actual result:**
![image](https://user-images.githubusercontent.com/1419318/182607781-7eca084f-4e66-4d5b-ba8c-34e86953509c.png)

**Comment by josteink** [comment]
Closed via https://github.com/KartikTalwar/gmail.js/pull/714.
