### ISSUE TITLE
compose event firing before content is ready

### ISSUE THREAD

**Issue by woniesong92** [KartikTalwar/gmail.js#715]
## issue

`compose` event fires before the content inside the compose element is ready.

## repro steps

```
gmail.observe.on('compose', function (compose, type) {
  console.log(compose.body()) // undefined

  setTimeout(() => {console.log(compose.body())}, 10 * 1000)) // content is ready usually after 10 seconds
}
```

## attempts to fix
- Tried waiting until `document.readyState` to become `complete` from `interactive`. However, the compose element is still not ready by then. Alternatively, I could wait for `compose.dom.body()` to not be `undefined,` which works for my usecase.

**Comment by josteink** [comment]
Not everyone needs all parts of the compose to be ready when this event fires, so I don't think there's any concrete spec or behaviour we can say is "most correct" here.

> Alternatively, I could wait for compose.dom.body() to not be undefined, which works for my usecase.

As such, this would be my suggestion too.
