### ISSUE TITLE
Issue downloading attachment(s) from compose view

### ISSUE THREAD

**Issue by GTP95** [KartikTalwar/gmail.js#716]
Greetings,

I'm failing to download an attachment (for now I tried only with one, but my code should work with any number of attachments) from the compose view. Here is how I'm trying to do this.
First I get a list of the attachments like this
```JS
const emailAttachments = compose_ref.attachments();
console.log("Attachments: ", emailAttachments);
```
And indeed in the console I get a list with an object containing information about the attachment.
Then I try to get the promises to download the attachments like this:
```JS
const listOfAttachmentPromises = [];
          for (const attachment in emailAttachments) {
            listOfAttachmentPromises.push(
              // @ts-ignore
              gmail.tools.make_request_download_promise(attachment.url, true)
            );
          }
```
I'm using JS with added type checking by the TS compiler, in the code above the error I'm ignoring is about `attachment.url` being a string and so not having the `url` property, but I think it is a false positive due to me not having set up types for this library correctly.
Then I print that list to the console and I indeed get a fulfilled promise:
```JS
console.log(
            "List of attachment promises: ",
            listOfAttachmentPromises
          );
```
![promise](https://user-images.githubusercontent.com/9197945/185795057-b4c0de83-4f31-49ea-91f7-45f7994f3d23.png)
But if I later try to use that, seems that the promise turned into a string:
```JS
for (const attachment in listOfAttachmentPromises) {
            console.log("attachment: ", attachment);
            console.log("Reported type of attachment: ", typeof attachment);
}
```
![string](https://user-images.githubusercontent.com/9197945/185795356-0471eec0-8cc2-4c38-9ce9-3b7e66c1d810.png)

How can I get the Uint8Array representing the attachment?

Thank you for your help,

GTP

**Comment by josteink** [comment]
Without doing any "deep" debugging, I can see that you are simultaneously downloading all attachments (you iterate and generate promises) without awaiting them.

This effectively means you are trying to download all in parallell.

Try downloading them one by one?

`````typescript
const attachments = [];
// use "of" not "in" to iterate over an array/collection-type object
for (const attachmentInfo of attachmentInfos) {
    // not use of await in loop. this causes one download at a time.
    const attachmentData = await  gmail.tools.make_request_download_promise(attachmentInfo.url, true);
    attachments.push(attachmentData)
}
`````

**Comment by josteink** [comment]
As for the actual attachment-result... I've been able to post that as is to other REST-endpoints without loss of data or fidelity.

It might be the browser is trying to be helpful and tries to convert it into a string if you try to access it as one? No idea.

**Comment by GTP95** [comment]
Following your suggestions it now works, thank you!
