### ISSUE TITLE
gmail.new.get.thread_data(threadId) and gmail.new.get.email_data(id) stopped working

### ISSUE THREAD

**Issue by suyogricha** [KartikTalwar/gmail.js#721]
I have updated latest gmail.js but from today both of these functions stopped working. Although, gmail.new.get.email_id() and gmail.new.get.thread_id() works fine. Kindly help asap.

**Comment by josteink** [comment]
Uh yeah. I've tested and can confirm.

It seems we still intercept the right XHR calls, but the line-format has changed somewhat, requiring someone to update the parsing-logic:

![image](https://user-images.githubusercontent.com/411338/189744320-fa28d48e-c03b-4a1f-940c-4f715ff01078.png)

If we're lucky, this is a quick fix, if not ... The old APIs still seems to work.

If you've engineered your extension to support both old API and new API (like I've done, ahem) and never got around to deprecating the old APIs... chances are still going to be OK for now.

While I'll see if I can make fix the parser, but I can't/won't make any promises about how much effort that is going to be.

For the time being, the quickest way to get your extension "back online" and to recover gracefully is to add a translation layer in your extension to be able to support both APIs versions, depending on what gives you results.

**Comment by josteink** [comment]
The good news seems to be that it seems to be a small change in the format, mostly indexes being off by 1 (across the board).

![image](https://user-images.githubusercontent.com/411338/189751091-07fed9bf-a0ae-42f9-9508-cf01619bca42.png)

That makes it likely that getting a new, working version out is fairly doable.

That said, there are small details here and there it will take some tweaks and testing to make sure everything still works right (for instance to, cc and bcc seem halfway unaffected?),

Will report more when there is more to report.

In the mean time if anyone feels to do the dirty work inside `api.tools.parse_fd_request_payload` (and friends) PRs are very much welcome.

**Comment by suyogricha** [comment]
Thanks dear. Kindly release.

**Comment by anuragphadke** [comment]
@josteink : whats the best/preferred way to revert to old API? I am using the "old API", but still getting the same issue, aka event not firing.

**Comment by josteink** [comment]
I don't think there's an old API fit events you can subscribe too. 

You will either have to wait for a fix or help create a PR for your specific part of this bigger issue.

**Comment by josteink** [comment]
I've done a very quick job at trying to fix the parsing indices for `api.new.get.email_data()` and `api.new.get.thread_data()`.

It's not ultra thoroughly tested, but I've taken more than a brief glance. From what I can tell, functionality should now be restored to what it was for these API functions.

Published as v1.1.0.

**Comment by suyogricha** [comment]
Awesome. Now it works. Hugs.

**Comment by josteink** [comment]
Actually that still has some bugs in parsing emails embedded at load. There's a `v1.1.1` out to fix it, where all NPM dependencies has also been updated to latest to silence some warnings.

**Comment by josteink** [comment]
Considering this fixed for now.

**Comment by MadcowD** [comment]
I think it's broken again

**Comment by MadcowD** [comment]
It's really strange, it'll work in one box but another. (Google Apps gmail accounts seem to work but newer ones don't.) They must be A/Bing out a change or something like that.

**Comment by MadcowD** [comment]
@josteink As for good news, it did seem to work for about a day if that's any consolation.

**Comment by MadcowD** [comment]
@josteink Doing some more testing, this error is quite intermittent.

**Comment by josteink** [comment]
I hate to be the guy who shrugs this off as "works on my machine", but I currently can't see any runtime-errors in my extension.

Can you still reproduce this?
