### ISSUE TITLE
Uncaught TypeError: Cannot read properties of undefined (reading '1')

### ISSUE THREAD

**Issue by cancan101** [KartikTalwar/gmail.js#724]
On `let thread_root = json["1"]["1"];` in `parse_bv_embedded_json`:
```js
    api.tools.parse_bv_embedded_json = function (json) {
        // ensure JSON-format is known and understood?
        // JSON-format is not simple to understand, code here is bases on hypothesis
        let thread_root = json["1"]["1"];
        if (!thread_root || !Array.isArray(thread_root)) {
            return null;
        }
```

**Comment by josteink** [comment]
I believe this is fixed in the latest version or any version above 1.1.1.

**Comment by josteink** [comment]
I hate to be the guy who shrugs this off as "works on my machine", but I currently can't see any runtime-errors in my extension.

Can you still reproduce this?

**Comment by cancan101** [comment]
I have not seen this issue since upgrading.
