### ISSUE TITLE
Attach custom UI in the sidebar of Gmail

### ISSUE THREAD

**Issue by yamini0312** [KartikTalwar/gmail.js#728]
I want to attach the custom UI in the sidebar of gmail window. 
Is it possible using gmail.js library?
Can anyone help me to guide the flow how can I attach the custom UI in the gmail dom? 
I have attached the screenshot for the reference, I want to attach the custom UI something like this in the gmail.

Thanks!

![Screenshot-from-2022-10-10-17-52-14](https://user-images.githubusercontent.com/52454626/194875952-9d9edaad-1fbd-40ad-8775-d090571ac4c2.png)

**Comment by josteink** [comment]
Gmail.js offers very little UI-support. If you want to do this, you will have to implement it yourself. 

That said, if you within that sidebar need access to contextual Gmail-data, Gmail.js will provide you with the ability to work with that. 

Hope this helps.

**Comment by MadcowD** [comment]
Thanks for all of your help @josteink . Is there a way to tip you or donate to the project.

**Comment by josteink** [comment]
The project as is has no running cost. 

All the code and docs is on GitHub. NPM covers distribution. There's literally no part of this project where (lack of) money is a reason for work not getting done. 

What _would_ help the project is more regular contributors, following up on bugs, answering questions, attempting to reproduce, gathering data, maybe even proposing their own PRs to fix registered issues, or offer help to test other, incoming PRs. 

There's a million ways to help, if you want to put in the effort 😉

**Comment by josteink** [comment]
Old issue is old. Closing.
