### ISSUE TITLE
Attachments from fd_embedded_json are not correctly parsed after Gmail update

### ISSUE THREAD

**Issue by onestep** [KartikTalwar/gmail.js#729]
After the Gmail internal API update I've noticed that attachments are not correctly parsed due to the exception:
![image](https://user-images.githubusercontent.com/1419318/195415352-d85bb2a1-6949-4955-8acf-5082c00fabe0.png)

`parse_fd_embedded_json_attachments()` should be updated to use new property indexes.

**Comment by MadcowD** [comment]
I'm also having this error.

**Comment by josteink** [comment]
A new version with a fix for this issue has now been released as version `1.1.5`.
