### ISSUE TITLE
gmail.observe.on('view_thread') not working

### ISSUE THREAD

**Issue by ZayaSerg** [KartikTalwar/gmail.js#731]

**Comment by josteink** [comment]
More info would be appreciated 🙂

**Comment by cancan101** [comment]
As of somewhat recently, a subscription to the `view_thread` event no longer seems to fire even though a thread is viewed. I will have to investigate further.

**Comment by cancan101** [comment]
I changed the `sub_selector` to: `'div.PeIF1d'` and it works

**Comment by josteink** [comment]
PRs welcome.

**Comment by josteink** [comment]
Agreed. 

If this is going to be a recurring problem, adding general support for multiple sub-selectors is probably not a bad and nothing I fundamentally have an issue with. 

Try it out and see if you can make it work?

**Comment by MadcowD** [comment]
This looks good!

**Comment by MadcowD** [comment]
@josteink is there anyway you could merge this? I'd love to update our app.

**Comment by josteink** [comment]
I was too quick in the review/testing of previous PR.

Upon proper testing I can't make this work at all. Not on new PR-code nor on old master code.

I guess that means there's more work to be done here, but I can't fix that now. I don't have time, at least until sometime next week.

**Comment by cancan101** [comment]
@josteink I am a bit confused here. Are you saying this change  _broke_ your experience?

**Comment by josteink** [comment]
No I'm saying it didn't work without this fix, but it doesn't work with it either. 

view_email event works though (no change).

**Comment by josteink** [comment]
The fix in its current state is released in new version `1.1.5`. No guarantees it will work, but at least it should make it easier to test.

**Comment by cancan101** [comment]
Okay, I just did a hard refresh of my gmail and it seems like the class name used by gmail has changed once again. So agreed, this fix does not work.

**Comment by josteink** [comment]
I guess that means we might have to use a higher level selector (.bu?) and try to filter it more intelligently in code further down (look for data-thread-id properties)?

Basically something which is generic enough to survive such changes, but not wide enough to cause performance issues.

**Comment by cancan101** [comment]
Ok, I think a better sub_selector is `iY` which given its length and proximity to `if` is more likely to be stable (?).

**Comment by josteink** [comment]
PRs welcome 🙂

**Comment by cancan101** [comment]
https://github.com/KartikTalwar/gmail.js/pull/735

**Comment by josteink** [comment]
Merged, available in 1.1.6.
