### ISSUE TITLE
gmail.get.user_email() returning undefined

### ISSUE THREAD

**Issue by MattIrineu** [KartikTalwar/gmail.js#741]
I'm trying to use gmailjs to retrieve the logged email using gmail.get.user_email() but it just returns undefined.

The previous post about it was closed but I didn't see any solutions for the problem there. anyone found a workaround?

Thank you

**Comment by josteink** [comment]
Hey there. Thanks for reporting an issue.

I assume you refer to issue https://github.com/KartikTalwar/gmail.js/issues/734 ?

If so it makes more sense to keep adding to that issue, rather than creating a new one. Closing this as a duplicate.
