### ISSUE TITLE
is_delegated_inbox is not working anymore

### ISSUE THREAD

**Issue by moodsey211** [KartikTalwar/gmail.js#753]
https://github.com/KartikTalwar/gmail.js/blob/edd1beeacf9faa9f82af7929706e95d0cd83e463/src/gmail.js#L2927

tested this on latest gmail and it seems the value of `.gb_Da` is replaced by `.gb_Ta`

**Comment by josteink** [comment]
Should now be fixed in version `1.1.9` on npmjs.
