### ISSUE TITLE
Reloading window makes the the user email undefined

### ISSUE THREAD

**Issue by RejownAhmed** [KartikTalwar/gmail.js#770]
Hi, I am using this in one of my extensions. On first page load we get the user mail by: 
```javascript 
gmail.get.user_email() // Returns: rejownahmedzisan@gmail.com
``` 
However, reloading the window returns: ``undefined``.

Additionally, if I hard reload it's the same but clearing the cache and reloading again returns the email address perfectly.
## Here's a screenshot of the pb:-
![ss](https://github.com/KartikTalwar/gmail.js/assets/91016843/f1c83a86-bff9-475f-8ca9-aea8c2708dfe)

**Comment by kamroot** [comment]
I had similar problems. Your extension is loading too early in the DOM lifecycle. If you check the hello world example and follow how they load the extension then it would work.

**Comment by RejownAhmed** [comment]
Thanks for you reply. Let me check it!
