### ISSUE TITLE
 gmail.observe.on("compose") observer returns type of "compose" when reply button is clicked

### ISSUE THREAD

**Issue by MichaelVandi** [KartikTalwar/gmail.js#772]
Here's my implementation of the compose observer. It's used to observe reply events when the reply button is clicked. This used to work perfectly before but now doesn't. It returns a type of "compose" instead of "reply" which the if statement checks for.

```
gmail.observe.on("compose", function (compose, type) {

        console.log("type", type);
        if (type == "reply") {
            alert("here reply")
            setTimeout(() => {
                const replyBox = gmail.dom.composes()[0].$el[0];
                if (replyBox) {
                    main(replyBox);
                }
            }, 6); // 
        }
        // type can be compose, reply or forward
        // console.log('api.dom.compose object:', compose, 'type is:', type );  // gmail.dom.compose object
    });
```

**Comment by MichaelVandi** [comment]
I've investigated the issue further and all evidences point to the function:  `is_inline` which checks `Is this compose instance inline (as with reply & forwards) or a popup (as with a new compose)`

Current implementation checks for the closes `td` HTML element.
I've made a temporary fix to check for the reply and forward icons instead. These icons are not present in the compose view. 

Replace the current is_inline implementation to this below and should work. Not sure if this is good enough to make a PR:

```
/**
           Is this compose instance inline (as with reply & forwards) or a popup (as with a new compose)
        */
is_inline: function() {
            // Temporary fix for is inline returning false for reply and forwards
            // This fix looks for the reply and forward icon present in the header of the reply
            // and forward views. These icons are never present in the compose view.
            // If icon is present, return true - indicating that it's reply or forward
            const composeBodyElement = this.$el;
            const replyAndForwardIcons = composeBodyElement.find('div.J-JN-M-I.J-J5-Ji.Un.L3[role="button"]');
            
            return replyAndForwardIcons ? true : false

            // return this.$el.closest("td.Bu").length > 0;
        },
```

**Comment by MykhailoDev** [comment]
Will better
`is_inline: function() {
            return this.$el.closest("td.HQ").length > 0;
        },`

**Comment by MichaelVandi** [comment]
I tried this but doesn't work for reply

**Comment by josteink** [comment]
Ive tested with the suggested solution from @MykhailoDev , which is now merged to git master. That works for me.

@MichaelVandi : Can you try the latest code from git and see if that works better for you?

**Comment by MichaelVandi** [comment]
@josteink yes. @MykhailoDev 's solution worked for me. Closing issue. Thank you for following up

**Comment by shamoons** [comment]
Still not working for me
