### ISSUE TITLE
Unable to Add Image to gmail.tools.add_compose_button

### ISSUE THREAD

**Issue by wilsonreyhan** [KartikTalwar/gmail.js#799]
Hi! Apologies, as I'm new here and have a feeling my question is pretty easy to resolve. I'm trying to create a button alongside "Send" and am having trouble adding my image icon and styling the button in general. See below my code and my output. Can someone answer: 

1. How do I properly add my png to the button? 
2. How do I style the button in general? Can someone provide a sample code if possible - I'm having a hard time picking up how I'd do this with just the documentation.

Thank you for all of the help!

```
gmail.observe.on("compose", (compose) => {
      console.log("New compose window is opened!", compose);
      console.log("Compose Ref", gmail.dom.compose());
      gmail.tools.add_compose_button(
        compose,
        '<img src="images/parrot_128.png" width="16" height="16" alt="Parrot Icon" />',
        () => console.log("Custom Compose Button Clicked!"),
        ""
      );
    });
```

![Screenshot 2024-11-05 at 8 47 11 PM](https://github.com/user-attachments/assets/a5656741-ad0b-41ac-b67f-aeb8316a5108)

**Comment by josteink** [comment]
You need to construct a fully qualified URL, based on your extensions runtime root URL/domain.

Your image URL is relative to the page, which is Gmail and not your extension.

https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/runtime/getURL

**Comment by wilsonreyhan** [comment]
@josteink Thank you! 

For anyone new who may run into the same problem - 

I generated my image url in extensionInjector and then stored in a non-script document element. Then in extension, you can access this document element to grab your image.
