### ISSUE TITLE
modify url parameters on POST request

### ISSUE THREAD

**Issue by keven425** [KartikTalwar/gmail.js#90]
I'm building an app that requires modifying email body. The url.cmml parameter represents the length of body string. If body is changed, url.cmml needs to be updated to new body length, otherwise gmail server will not send the email.

I saw the comments in api.tools.xhr_watcher():

// TODO: recreate the url if we want to support manipulating url args (is there a use case where this would be needed?)

However, url is passed in win.XMLHttpRequest.prototype.open(), while email body is passed in win.XMLHttpRequest.prototype.send(). If I modify the body, I only find out about body in send(), which happens after open().

Any ideas on how to handle this?

**Comment by josteink** [comment]
Seems this is both solved and old. Closing.
